### ISSUE TITLE
Completion failures with C++ std::vector

### ISSUE THREAD

**Issue by renewagner** [Valloric/ycmd#1016]
Hi,

I'm using ycmd Valloric/ycmd@7a4f5858 via abingham/emacs-ycmd@a35a2dd with Clang 6.0.0 under Linux and I've found that in some cases ycmd does not produce any semantic completion candidates (`RuntimeError: No completions found; errors in the file?`). I originally submitted an issue at  abingham/emacs-ycmd#466 but I believe this is a more general issue with ycmd as it happens on the server side.

I haven't been able to reduce the original problematic translation unit to a minimal test case but oddly enough even something as common as std::vector is causing trouble. I figured I'd submit this first. Perhaps it will also help with the more complex translation unit.

Depending on included headers and the choice of T, completion of std::vector\<T\> members sometimes works and sometimes doesn't. I have created three files. With `a.cc`, ycmd returns no completions (at the `a.`):
```C++
#include <stdint.h>
#include <vector>

int main(int, char **)
{
    std::vector<uint8_t> a(10);
    a.

    return 0;
}
```
With `b.cc`, ycmd does return completions:
```C++
#include <stdint.h>
#include <vector>

int main(int, char **)
{   
    std::vector<float> b(10);
    b.   

    return 0;
}
```
and with `c.cc` it once again doesn't:
```C++
// compile with -std=c++14!                                                                                                                                             
#include <cstdint>
#include <vector>

int main(int, char **)
{   
    std::vector<float> c(10);
    c.                                                                                                                                               

    return 0;
}
```

All three files produce the expected result when passed to Clang's `c-index-test` as follows:
```ShellSession
$ c-index-test -code-completion-at=a.cc:7:6 $(python .ycm_extra_conf.py) -c a.cc  | grep push_back
CXXMethod:{ResultType void}{TypedText push_back}{LeftParen (}{Placeholder const value_type &__x}{RightParen )} (34)
CXXMethod:{ResultType void}{TypedText push_back}{LeftParen (}{Placeholder value_type &&__x}{RightParen )} (34)
$ c-index-test -code-completion-at=b.cc:7:6 $(python .ycm_extra_conf.py) -c b.cc  | grep push_back
CXXMethod:{ResultType void}{TypedText push_back}{LeftParen (}{Placeholder const value_type &__x}{RightParen )} (34)
CXXMethod:{ResultType void}{TypedText push_back}{LeftParen (}{Placeholder value_type &&__x}{RightParen )} (34)
$ c-index-test -code-completion-at=c.cc:8:6 $(python .ycm_extra_conf.py) -c c.cc  | grep push_back
CXXMethod:{ResultType void}{TypedText push_back}{LeftParen (}{Placeholder const value_type &__x}{RightParen )} (34)
CXXMethod:{ResultType void}{TypedText push_back}{LeftParen (}{Placeholder value_type &&__x}{RightParen )} (34)
```

My `.ycm_extra_conf.py` is as follows:
```Python
basic_flags = ['-x', 'c++', '-std=c++14']

def compiler_search_path():
	import os
	f = os.popen("clang %s -E -v - < /dev/null 2>&1" % (" ".join(basic_flags)))
	o = f.readlines()
	f.close()
	o2 = o[0:o.index('End of search list.\n')]
	o3 = o2[o2.index('#include <...> search starts here:\n')+1:-1]
	return [p.strip() for p in o3]

def FlagsForFile( filename, **kwargs ):
	system_path = compiler_search_path()

	cxx_flags = "-mcmodel=medium;-Wall;-Wextra;-Wuninitialized;-Wno-unknown-pragmas;-Wno-enum-compare;-Wno-strict-aliasing;-Wno-strict-overflow;-Wno-unused-local-typedefs;-Wno-narrowing;-Wno-unneeded-internal-declaration"

	flags = basic_flags
	for p in system_path:
		flags.extend(['-isystem', p])
	flags.extend(cxx_flags.split(';'))
	return {'flags' : flags}

if __name__ == "__main__":
	f = FlagsForFile("");
	print " ".join(f['flags'])
```

Any suggestions towards fixing this would be very appreciated! When it works I really enjoy the ycmd experience :smiley: 

Cheers,

Rene

**Comment by puremourning** [comment]
Hmm. I can't repro with any of your examples. Are you sure that it's not just still parsing in the background? 

Can you confirm the set of flags in their entirety? (i.e. the output of the /debug_info request, equivalent to :YcmDebugInfo in Vim; sorry I  don't know the emacs command)

Could you also please gist the full ycmd log files?

Finally, can you let us know if you're getting any diagnostic in the examples ? you should get a missing unqualified-id due to the incomplete statement.

**Comment by bstaletic** [comment]
I can consistently repro when using the same extra conf as @renewagner.
For some reason ycmd doesn't like @renewagner's extra conf.

The following extra conf worked:

```py
def FlagsForFile( filename ):
  return { [ '-xc++', '-std=c++14', 
              '-isystem', '/usr/include/c++/v1', 
              '-isystem', '/usr/lib/llvm/6/bin/../../../../lib/clang/6.0.0/include`, 
              '-isystem', '/usr/include' ] }
```

I'm investigating further.

**Comment by bstaletic** [comment]
What's even weirder, the following extra conf also works:
```python
basic_flags = ['-x', 'c++', '-std=c++14']

def compiler_search_path():
	import os
	f = os.popen("clang %s -E -v - < /dev/null 2>&1" % (" ".join(basic_flags)))
	o = f.readlines()
	f.close()
	o2 = o[0:o.index('End of search list.\n')]
	o3 = o2[o2.index('#include <...> search starts here:\n')+1:-1]
	return [p.strip() for p in o3]

def FlagsForFile( filename, **kwargs ):
	system_path = compiler_search_path()

	cxx_flags = "-mcmodel=medium;-Wall;-Wextra;-Wuninitialized;-Wno-unknown-pragmas;-Wno-enum-compare;-Wno-strict-aliasing;-Wno-strict-overflow;-Wno-unused-local-typedefs;-Wno-narrowing;-Wno-unneeded-internal-declaration"

	flags = basic_flags
	#for p in system_path:
		#flags.extend(['-isystem', p])
	flags.extend(cxx_flags.split(';'))
	return {'flags' : flags}

if __name__ == "__main__":
	f = FlagsForFile("");
	print(" ".join(f['flags']))
```

The only difference from @renewagner is the commented out `flags.extend()` for system headers.

**Comment by puremourning** [comment]
Hmm. I can't repro on macOS with @renewagner's extra conf. 

What gcc version / standard library are you using ? Could be an incompatibility...

**Comment by bstaletic** [comment]
What's even weirder, the following extra conf also works:
```python
basic_flags = ['-x', 'c++', '-std=c++14']

def compiler_search_path():
	import os
	f = os.popen("clang %s -E -v - < /dev/null 2>&1" % (" ".join(basic_flags)))
	o = f.readlines()
	f.close()
	o2 = o[0:o.index('End of search list.\n')]
	o3 = o2[o2.index('#include <...> search starts here:\n')+1:-1]
	return [p.strip() for p in o3]

def FlagsForFile( filename, **kwargs ):
	system_path = compiler_search_path()

	cxx_flags = "-mcmodel=medium;-Wall;-Wextra;-Wuninitialized;-Wno-unknown-pragmas;-Wno-enum-compare;-Wno-strict-aliasing;-Wno-strict-overflow;-Wno-unused-local-typedefs;-Wno-narrowing;-Wno-unneeded-internal-declaration"

	flags = basic_flags
	#for p in system_path:
		#flags.extend(['-isystem', p])
	flags.extend(cxx_flags.split(';'))
	return {'flags' : flags}

if __name__ == "__main__":
	f = FlagsForFile("");
	print(" ".join(f['flags']))
```

The only difference from @renewagner is the commented out `flags.extend()` for system headers.

**Comment by bstaletic** [comment]
I'm using GCC 7.3.0.
Should I try compiling ycmd with clang?

**Comment by renewagner** [comment]
@puremourning I'm sure it's done parsing, yeah. I've also run `M-x ycmd-parse-buffer` which returns a message `Parsing buffer done` immediately. As for the debug info, I'm afraid I'm still in the process of wrapping my head around how the vim commands map to what I see in Emacs... There's a menu entry `YCMd->Show debug info` which gives me the following:

```
Ycmd debug information for buffer a.cc in c++-mode:

((python
  (executable . "/usr/bin/python")
  (version . "2.7.13"))
 (completer
  (items
   ((value . "None")
    (key . "compilation database path"))
   ((value . "[u'-x', u'c++', u'-std=c++14', u'-isystem', u'/usr/lib64/gcc/x86_64-suse-linux/5/../../../../include/c++/5', u'-isystem', u'/usr/lib64/gcc/x86_64-suse-li\
nux/5/../../../../include/c++/5/x86_64-suse-linux', u'-isystem', u'/usr/lib64/gcc/x86_64-suse-linux/5/../../../../include/c++/5/backward', u'-isystem', u'/usr/local/in\
clude', u'-isystem', u'/home/redacted/local/llvm-6.0.0/lib/clang/6.0.0/include', u'-mcmodel=medium', u'-Wall', u'-Wextra', u'-Wuninitialized', u'-Wno-unknow\
n-pragmas', u'-Wno-enum-compare', u'-Wno-strict-aliasing', u'-Wno-strict-overflow', u'-Wno-unused-local-typedefs', u'-Wno-narrowing', u'-Wno-unneeded-internal-declarat\
ion', u'-resource-dir=/home/redacted/local/ycmd/ycmd/../clang_includes', u'-fspell-checking']")
    (key . "flags"))
   ((value . "/home/redacted/ycmdtest/a.cc")
    (key . "translation unit")))
  (name . "C-family")
  (servers))
 (extra_conf
  (path . "/home/redacted/ycmdtest/.ycm_extra_conf.py")
  (is_loaded . t))
 (clang
  (has_support . t)
  (version . "clang version 6.0.0 (tags/RELEASE_600/final)")))


Server is running at: 127.0.0.1:35116

Ycmd Mode is enabled

--------------------

Ycmd version:   nil
Emacs version:  25.3.1
System:         x86_64-pc-linux-gnu
Window system:  nil
```

I've also created a gist with the content of the *ycmd-server* buffer which I believe contains the ycmd log output at https://gist.github.com/renewagner/1d8a81f505e3dae5c1c9583e33c26bbb. I'm afraid I'm not seeing any diagnostics in Emacs. I guess I'll need to install flycheck and flycheck-ycmd to make that work. I'll see if I can install both shortly.

@bstaletic Yay! It's not just me :smiley: So, I guess either ycmd or libclang are taking offense at the system headers from GCC (5.3.1 in my case). I wonder why that is a problem though as I'm just parsing clang defaults here. Also, the main compiler of my project is GCC, so I actually want the same headers to be used.

@puremourning Perhaps I should note that I built LLVM without libc++. macOS might be using libc++ by default rather than the GNU libstdc++ nowadays. Does `clang -x c++ -E -v - < /dev/null` return any GCC-provided include paths on your machine?

Cheers,

Rene

**Comment by renewagner** [comment]
@bstaletic Wow, how embarrassing! Thanks for spotting that one! I used to know about Python slicing. No idea why I messed up this time. I guess I've been exposed to too much Matlab code lately...

The examples above are working fine now. So is the more complex translation unit I mentioned (after a longer wait for parsing).

I suppose this issue can be closed now. On the other hand, I wonder if it might be worthwhile including a common implementation of the parsing function in ycmd so that perhaps users can just `import ycmd.confutils` in their `.ycm_extra_conf.py` and re-use it. The functionality appears to be required by many users. I've seen various re-implementations in multiple places on github and elsewhere (unfortunately after I'd written my own buggy version). What do you think?

In any case, thanks a lot everyone for your time and sorry about the noise caused by my little mistake!

**Comment by bstaletic** [comment]
>  I wonder if it might be worthwhile including a common implementation of the parsing function in ycmd

We are aware that leaving it to users to implement this is not ideal. I'd be the first in line to see a 100% working solution that is not terrible to maintain. The issue, however, is much more complex than it seems at first. The `clang++ -xc++ -E -v` trick doesn't work 100% of the time even if we take into account all the interesting flags (like `-nostdlib`, `-nostdinc`, `--gcc-toolchain`, `--sysroot` and others) that a user might have in his flags. For a more detailed discussion check #853 anbd cquery-project/cquery#641. 

While ycmd is conservative and careful not to break stuff, Cquery was bolder and decided to go for a simple implementation and hope for the best.

Given the above, I'll close the issue.

> sorry about the noise caused by my little mistake

I actually had fun debugging this.

**Comment by renewagner** [comment]
> The clang++ -xc++ -E -v trick doesn't work 100% of the time

I wasn't necessarily suggesting to use the resulting flags by default. The idea was to provide users with a tool that they can but do not need to use in their extra conf. I was thinking along the lines of:
```Python
def ParseCompilerIncludePath(compiler = "clang -x c++"):
    cmd = "%s -E -v - < /dev/null 2>&1" % (compiler)
    # run cmd, parse output
    return path_list
```

My code above would then become:
```Python
def compiler_search_path():
    from ycmd.confutils import ParseCompilerIncludePath
    return ParseCompilerIncludePath("clang -x c++ -std=c++14")
```

And this issue report would not have happened :smile: 

> if we take into account all the interesting flags (like -nostdlib, -nostdinc, --gcc-toolchain, --sysroot and others)

I'm not sure I understand the problem with those. Sure, they do influence the include paths but that should be reflected in the compiler output. You simply need to pass the exact flags you'll later use for actual compilation when you intend to parse the compiler include path output. By GCC's definition this is not a hard-coded list of paths but the exact paths that the compiler would use if it didn't stop after the preprocessing stage (-E). 

Are you saying that if you pass those flags as additional parameters to the `clang -xc++ -E -v` call its output will contain inappropriate include paths? That would be a bug in Clang then. In fact, a quick check shows differences in behavior:

```ShellSession
$ g++ -nostdinc -E -v - < /dev/null
...
#include "..." search starts here:
#include <...> search starts here:
End of search list.
...
$ clang -x c++ -nostdinc -E -v - < /dev/null
...
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib64/gcc/x86_64-suse-linux/5/../../../../include/c++/5
 /usr/lib64/gcc/x86_64-suse-linux/5/../../../../include/c++/5/x86_64-suse-linux
 /usr/lib64/gcc/x86_64-suse-linux/5/../../../../include/c++/5/backward
End of search list.
...
```

> check #853

I'm sorry I don't quite follow the reasoning behind that PR. At the end of the day you need a compiler to compile the code you're editing. Why try and replicate that logic?

> I actually had fun debugging this.

Excellent! Thanks again @bstaletic !

> Then use `gcc -E -v` in your extra conf. 

Yeah, that's what I had in there originally but Clang then chokes on some GCC-specific intrinsics in header files, emmintrin.h for SSE in my case.

**Comment by bstaletic** [comment]
> I wasn't necessarily suggesting to use the resulting flags by default. The idea was to provide users with a tool that they can but do not need to use in their extra conf. 

Thanks for the suggestion. I personally see that solution as a compromise, so I'm not sure how to feel about it. To be completely honest, I'd gladly review such a PR, but I don't see myself implementing it.
To be clear, I don't think it is a bad idea, but it is also not a perfect solution. Cquery went for something that is also not a bad idea but isn't perfect either and is now having troubles (though the proposed solutions are completely different).

> You simply need to pass the exact flags you'll later use for actual compilation when you intend to parse the compiler include path output.

Not quite... Libclang can be quite picky about flags so flags need sanitation. Also, if we parse `clang++ -E -v -isystem /path`, we will potentially have duplicated include paths, which shouldn't be harmful but creates noise. The things get even more interesting if we take into account CL driver mode.

Remember, we can't trust the user to always provide correct paths, so a lot of work is needed for making this as error resistant as the current situation is.

However, a user can use our `flags.py` to sanitize his flags, though we will make no promises to keep backwards compatibility for such a use case.

> Are you saying that if you pass those flags as additional parameters to the clang -xc++ -E -v call its output will contain inappropriate include paths?

No, I'm saying that parsing the command line to figure out what to pass along with `-xc++ -E -v` is hard and it is easy to miss things.

Also note that `-xc++` can be incorrect.

> I'm sorry I don't quite follow the reasoning behind that PR. At the end of the day you need a compiler to compile the code you're editing. Why try and replicate that logic?

Because ycmd depends on libclang, not on a compiler. I could easily provide a system that doesn't have a working compiler, but does have a working ycmd. Therefore we do not want to introduce an extra dependency.

> Yeah, that's what I had in there originally but Clang then chokes on some GCC-specific intrinsics in header files, emmintrin.h for SSE in my case.

Unfortunately, that's not something ycmd can do anything about - that;s just an incompatibility between gcc and clang.
