### ISSUE TITLE
Redundant libclang.so file with -DUSE_SYSTEM_LIBCLANG=1

### ISSUE THREAD

**Issue by yan12125** [Valloric/ycmd#102]
When I specify ```-DUSE_SYSTEM_LIBCLANG=1``` to cmake, the resulting files have the following dependencies: 
```Bash
$ ldd ycm_core.so
linux-vdso.so.1 (0x00007ffff7d98000)
libpython2.7.so.1.0 => /usr/lib/libpython2.7.so.1.0 (0x00007f9e9caf9000)
libclang.so => /usr/lib/libclang.so (0x00007f9e9bbc4000)
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f9e9b8b5000)
libm.so.6 => /usr/lib/libm.so.6 (0x00007f9e9b5af000)
libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f9e9b399000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007f9e9aff6000)
libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f9e9add8000)
libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f9e9abd4000)
libutil.so.1 => /usr/lib/libutil.so.1 (0x00007f9e9a9d1000)
libLLVM-3.6.so => /usr/lib/libLLVM-3.6.so (0x00007f9e9878b000)
/usr/lib64/ld-linux-x86-64.so.2 (0x00007f9e9d28b000)
libz.so.1 => /usr/lib/libz.so.1 (0x00007f9e98575000)
libffi.so.6 => /usr/lib/libffi.so.6 (0x00007f9e9836b000)
libedit.so.0 => /usr/lib/libedit.so.0 (0x00007f9e9812f000)
libncursesw.so.5 => /usr/lib/libncursesw.so.5 (0x00007f9e97eca000)
$ ldd ycm_client_support.so
linux-vdso.so.1 (0x00007ffc54fbf000)
libpython2.7.so.1.0 => /usr/lib/libpython2.7.so.1.0 (0x00007fa710882000)
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fa710573000)
libm.so.6 => /usr/lib/libm.so.6 (0x00007fa71026e000)
libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fa710057000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007fa70fcb4000)
libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fa70fa97000)
libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fa70f892000)
libutil.so.1 => /usr/lib/libutil.so.1 (0x00007fa70f68f000)
/usr/lib64/ld-linux-x86-64.so.2 (0x00007fa710f33000)
```
Does that mean there's no need to [copy libclang.so in this line](https://github.com/Valloric/ycmd/blob/master/cpp/ycm/CMakeLists.txt#L287) if ```-DUSE_SYSTEM_LIBCLANG=1``` specified?

**Comment by Valloric** [comment]
No, the copy is still necessary. Using the system libclang does not mean it is loaded from the location where the system libclang is placed. `ycm_core.so` expects the libclang library to be in the same folder next to it, and `@rpath` and other wonkiness is there to ensure that that libclang is loaded.

**Comment by yan12125** [comment]
Sorry for late response. If I'm correct, seems rpath is not set correctly in ```cpp/ycm/CMakeLists.txt```? ```rpath = "$ORIGIN"``` is specified at [this line](https://github.com/Valloric/ycmd/blob/master/cpp/ycm/CMakeLists.txt#L227), which is executed only if ```USE_SYSTEM_LIBCLANG``` is false. Note that I'm using Linux.

**Comment by Valloric** [comment]
Actually you're right, if you're on Linux and `USE_SYSTEM_LIBCLANG` is set, no rpath is set on the libs.  This means that the libclang.so is unnecessarily copied in that case.

The copy doesn't hurt at all, and adding special logic for this case would only increase the complexity of install conf so I don't think this is worth fixing. Seriously, what's the benefit? It's not as if `USE_SYSTEM_LIBCLANG` is even a recommended setup; quite the contrary, the README very loudly says to not use that setup, and those that do are on their own.

**Comment by yan12125** [comment]
Actually, the unofficial package provided on Arch Linux do this [1]. I propose this because there's an obviously unused file in the package, which is not a good practice in packaging. I'll contact the package maintainer and ask for further possible modifications in packaging. Anyway, thanks for the time on responding the issue.

[1] https://aur.archlinux.org/packages/vim-youcompleteme-git/
