### ISSUE TITLE
compilaton database should be preferred over g:ycm_global_ycm_extra_conf

### ISSUE THREAD

**Issue by real-or-random** [Valloric/ycmd#1030]
According to the README, ycm tries
 1. ycm_extra_conf.py
 2. g:ycm_global_ycm_extra_conf
 3. compilation database

in this order. I think it should instead be
 1. ycm_extra_conf.py
 2. compilation database
 3. g:ycm_global_ycm_extra_conf.

Reason: If you have a ycm_extra_conf.py, this should override everything. But a global extra conf should only be a fallback. The compilation is project-specific and probably better.

With the new order, you can use a compilation databases for some of your projects and fall back to a global conf if there is no database.

**Comment by micbou** [comment]
This has already been reported in https://github.com/Valloric/YouCompleteMe/issues/2777.
