### ISSUE TITLE
ClangParseError: An AST deserialization error occurred while parsing the translation unit

### ISSUE THREAD

**Issue by dunpyl** [Valloric/ycmd#1037]
I'm introducing YCM into a fairly large C++ project, which uses `cmake` with a very large number of flags and settings.
Initially I just specified some of these flags - specifically, includes - in the project's `.ycm_extra_conf.py`, which worked well.
Then I set `compilation_database_folder` to the location of `compile_commands.json`, and since then, the server crashes as soon as I request it to process a C++ file, returning the error in the title:
`ClangParseError: An AST deserialization error occurred while parsing the translation unit`

**Comment by puremourning** [comment]
This means that libclang is unable to parse the unit given the flags in your compilation database.

Without specific flags and a reproducible test case, there's not much we can do.

**Comment by micbou** [comment]
Try to do a bisect on the flags until you find which one is the culprit. We can then consider removing this flag automatically in ycmd.

**Comment by bstaletic** [comment]
You're saying that adding `-isystem /some/path` is causing an AST deserialization error?
I'm guessing you are using a lot of those headers in your project.
Apparently, libclang is choking on some header from that path. Are you able to use clang to compile your project?

**Comment by dunpyl** [comment]
@bstaletic yes, test show that the error consistently occurs with this flag, and does not occur without this flag.
I am quite surprised by this situation as well. The project regularly compiles and passes all tests with Clang 5.0.0.
What are our options?  Can we configure YCM/D to just ignore this flag?

**Comment by dunpyl** [comment]
Further discovery: If I eliminate the space between `-isystem` and `/some/path` in `compile_commands.json`, i.e. convert `-isystem /some/path` to `-isystem/some/path`, the error disappears.

**Comment by bstaletic** [comment]
Now that is really weird. I'm not sure how is that even possible. My suggestion is to remove that space if it prevents the AST error and carry on with your life.

**Comment by dunpyl** [comment]
@bstaletic thanks, I was thinking the same thing. The problem is that I don't control `compile_commands.json`'s generation, and getting rid of that space is a big hassle because of that.
Is there a way to get rid of that space programmatically, using some sort of pre-process?

**Comment by bstaletic** [comment]
You can write a `.ycm_extra_conf.py` that parses your compilation database and "fixes" the flags. For how to get an extra conf to parse a compilation database, take a look at ycmd's `.ycm_extra_conf.py`.

**Comment by dunpyl** [comment]
@bstaletic thanks!  Checking out `ycmd`'s head (4b3912ef3a54c22ea828e9261968d5f367ab6535), there are multiple `.ycm_extra_conf.py` files nested in the project. Which one of them did you mean?
```
$ find -iname '.ycm_extra_conf.py'
./tests/cs/testdata/testy-multiple-solutions/solution-not-named-like-folder/extra-conf-bad/testy/.ycm_extra_conf.py
./tests/cs/testdata/testy-multiple-solutions/solution-not-named-like-folder/extra-conf-rel/.ycm_extra_conf.py
./tests/cs/testdata/testy-multiple-solutions/solution-not-named-like-folder/extra-conf-abs/.ycm_extra_conf.py
./tests/testdata/client/.ycm_extra_conf.py
./tests/testdata/extra_conf/project/.ycm_extra_conf.py
./tests/clang/testdata/general_fallback/.ycm_extra_conf.py
./tests/clang/testdata/.ycm_extra_conf.py
./tests/clang/testdata/noflags/.ycm_extra_conf.py
./tests/clang/testdata/client_data/.ycm_extra_conf.py
./tests/clang/testdata/test-include/.ycm_extra_conf.py
./tests/clang/testdata/driver_mode_cl/flag/.ycm_extra_conf.py
./tests/clang/testdata/driver_mode_cl/executable/.ycm_extra_conf.py
```

**Comment by bstaletic** [comment]
Yeah, I forgot we have a lot of those. You also ran `find` one directory too deep. The one you should take a look at is in [`cpp/ycm/.ycm_extra_conf.py`](https://github.com/Valloric/ycmd/blob/master/cpp/ycm/.ycm_extra_conf.py).

**Comment by dunpyl** [comment]
Thanks, @bstaletic. FYI, the support for getting the flags from `compile_commands.json` in that file seems somewhat patchy.
Notably, if you request to process a file that is not listed in that JSON, `FlagsForFile()` will just return `None`, which will not only fail to provide any flags, but also cause an exception downstream (specifically: `ycmd/completers/cpp/flags.py", line 301, in _CallExtraConfFlagsForFile`) where clients expect a dictionary populated by keys like `flags`.

**Comment by micbou** [comment]
> Notably, if you request to process a file that is not listed in that JSON, FlagsForFile() will just return None, which will not only fail to provide any flags, but also cause an exception downstream (specifically: ycmd/completers/cpp/flags.py", line 301, in _CallExtraConfFlagsForFile) where clients expect a dictionary populated by keys like flags.

It's more an issue with ycmd always expecting the `flags` field in the return value of `FlagsForFile`. I'll work on a fix.

**Comment by micbou** [comment]
PR #1039 has been merged and the initial issue is resolved (though I doubt the issue was really the space between `-isystem` and some path; both `-isystem<path>` and `-isystem <path>` are valid). Closing.
