### ISSUE TITLE
C/C++: UnicodeDecodeError if documentation comment is written in an encoding other than UTF-8

### ISSUE THREAD

**Issue by Bakudankun** [Valloric/ycmd#1042]
Windows 10 Pro 64bit
Vim 8.1.0005 64bit +python3.5.4/dyn +python2.7.12/dyn with YouCompleteMe

### How to reproduce

Here is a code whose comment is written in encoding cp932: [cp932.h.txt](https://github.com/Valloric/ycmd/files/2035355/cp932.h.txt)

Its content is like:

```c++
/// 構造体a
struct a {};
```

(Note that above code block is written in UTF-8, not cp932.)

When you use it from another file:

```c++
#include "cp932.h"

a.
```

then you get:

> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 0: invalid start byte

and code completion doesn't work.

Could you convert such non-utf8 documentation comments? Otherwise, is there a way to make ycmd to ignore documentation comments? I want code completion to work.

**Comment by micbou** [comment]
Unfortunately, I don't see a way to fix the issue. I tried to deduce the encoding of the comment with [the chardet library](https://github.com/chardet/chardet) and it's unable to find it. The following code (in Python 3):
```python
import chardet
print( chardet.detect( '構造体'.encode( 'cp932' ) ) )
```
returns
```
{'encoding': None, 'confidence': 0.0, 'language': None}
```
so there is not much we can do if even a library like chardet is unable to find the encoding.

Of course, we could swallow up the exception and return an empty string for the doxygen comment but this doesn't fix the issue, only hides it. If we do that, we'll have users reporting issues that documentation is missing. Furthermore, what if an identifier contains such characters, do we completely ignore the completion in that case? Clearly, we are not going to return an empty completion. In that case, users will report that completions are missing.

No really, I think it's less trouble to state that only UTF-8 encoding is supported which we already do in [the API docs](https://valloric.github.io/ycmd#general-notes):

> All strings going into and out of the server are UTF-8 encoded.

Closing the issue as won't fix. I suggest you to convert the encoding of your cp932 file to UTF-8.
