### ISSUE TITLE
"No completions found; errors in the file" ho to diagnose?

### ISSUE THREAD

**Issue by Mafeuser** [Valloric/ycmd#1044]
I'm trying to use ycmd on my fairly large C++ project.
It is C++14/linux compiled with g++ 7.x. For completions I'm using clang 6.0 compiled from scratch.

When I'm in some file and try to complete, I get following error in *ycmd-server* buffer:

```
    raise RuntimeError( NO_COMPLETIONS_MESSAGE )
      RuntimeError: No completions found; errors in the file?
```

My first question is:
does it mean that parsing process using clang++ fails with errors counter > 0 for my source buffer?

To find these errors I do following:
In emacs I visit buffer I want to check against parsing errors, then run M-x ycmd-show-debug-info to get compilation flags (compile_commands.json is used within my project).

open up the shell terminal, and:
```
clang++ -v -fsyntax-only <FLAGS_ABOVE> /path/to/source.cpp
```

The unexpected thing is I DO NOT get any parsing errors (warnings are present, BUT no errors).
I did expect some errors thugh.

Why so? Or in other words: how Can I diagnose "errors in the file?" problem mentioned above then?

regards,
Mat

**Comment by Mafeuser** [comment]
yes I do and it does not produce any errors on that file. The weird thing is that if I add "#include <nonexistentfile.h>" flycheck will NOT highlight it as an error. If I'll do the same on other much simpler file within some other (test) project, flycheck will highlight such error.

Anyway, as I understand You correct, the source for errors of ycmd-flycheck and "errors in the file?" message above is THE SAME (clang flags or probably more the fact of using libclang instead of clang++ by ycmd), right?

Probably my next step is to figure out why "#include <nonexistentfile.h>" is not highlighted by ycmd-flycheck.

**Comment by Mafeuser** [comment]
my guess is clang itself must have some limit for the number of errors it returns to frontend (ycmd) and that threshold in my setup is like 30 or so.
Because the code contains more errors than that, ycmd has no chance to get info from clang about nonexistent file.
Why NOTHING is highlighed withing my source file? because all the errors returned by clang are related to files included by my source file.

maybe it is -ferror-limit?

**Comment by vibrys** [comment]
increase max_diagnostics_to_display in ycmd.el

**Comment by micbou** [comment]
The emacs client should allow changing the value of that option in the user configuration file. It should also provide a command to list all the diagnostics for the current file like [the `:YcmDiags` command](https://github.com/Valloric/YouCompleteMe#the-ycmdiags-command) in the Vim client. I would suggest to raise issues for these features on [the emacs repository](https://github.com/abingham/emacs-ycmd.

On ycmd's side, I think we should add a diagnostic that we would put at the start of the file when the maximum number of errors are exceeded. Anyway, this is a feature already requested in https://github.com/Valloric/YouCompleteMe/issues/2392 so I am going to close this as duplicate.

**Comment by Mafeuser** [comment]
That worked.
thank You people.
