### ISSUE TITLE
feature req: support for tsserver shims

### ISSUE THREAD

**Issue by elpddev** [Valloric/ycmd#1050]
Using tsserver under asdf installation. The script is a shim that runs on it self, without needing `node tsserver`. 

related to: 
https://github.com/Valloric/YouCompleteMe/issues/2612

Using @micbou helpfull suggestion there, the code I can see this related to is:
https://github.com/Valloric/ycmd/blob/e934520ccaee6095c0911a56e3ad2f3848b42402/ycmd/completers/typescript/typescript_completer.py#L219

There is only support for tsserver as a node runner executable.

**Comment by elpddev** [comment]
@micbou confirmed. The code worked in my installation.

I did not knew tsserver was a node executable script with shebang at the top. That makes it executable as standalone command without needing the `node` prefix`. Maybe its does not need node path too? Or is node path needed for other OS not linux.

**Comment by micbou** [comment]
> Maybe its does not need node path too? Or is node path needed for other OS not linux.

It's only for supporting Debian-based distributions where the node executable is named `nodejs`, not `node`. The shebang doesn't work in that case so we need to prefix the command with the right executable.
