### ISSUE TITLE
Purescript example?

### ISSUE THREAD

**Issue by dakom** [Valloric/ycmd#1065]
I see that there is a Language Server Protocol example completer at https://github.com/Valloric/ycmd/tree/master/ycmd/completers/language_server

And also there is a Language Server Protocol server for Purescript at https://github.com/nwolverson/purescript-language-server

Personally, I'm only getting started with Purescript (which is why I need the IDE help desperately hehe) and haven't coded any Vim plugins before - so I'm not the ideal candidate to tie these two together... though at a glance it seems like it should be straightforward...

Is there an example plugin which takes the language-server-completer and implements it? Maybe I could tinker around with that...

Would be really nice to have YCM support Purescript!

**Comment by bstaletic** [comment]
The `language_server` implementation you've found is an abstraction of LSP's generic parts. For an actual language server, take a look at https://github.com/Valloric/ycmd/tree/master/ycmd/completers/java. It shouldn't take you more than an hour or two to understand the java and then write a completer for a different language.

What will take time is writing tests for the new completer, even though it should be pretty straight forward.

**Comment by puremourning** [comment]
See also https://github.com/Valloric/ycmd/blob/master/JAVA_SUPPORT.md

**Comment by dakom** [comment]
Interesting... not sure if I'll tackle this since I know neither Python nor Purescript nor Vim internals yet..

But just in case ;)

What does the iterative development cycle look like - is this right?

```
1. fork YouCompleteMe
2. start new directory for plugin
3. make changes
4. need to re-`install.py` each change?
5. need to re-load vim/files?
```

**Comment by micbou** [comment]
Looks like the question has been answered. Feel free to ask us on [the Gitter room](https://gitter.im/Valloric/YouCompleteMe) if you have other questions.
