### ISSUE TITLE
ClangCompleter: Use compile_flags.txt

### ISSUE THREAD

**Issue by ecnerwala** [Valloric/ycmd#1067]
Clang tools support a simpler form of `compile_commands.json` called `compile_flags.txt` (https://clang.llvm.org/docs/JSONCompilationDatabase.html#alternatives). It would be nice if ycmd could automatically load these files if no `compile_commands.json` is found. I understand it could be done via `ycm_global_exta_conf` or the like, but given that we support `compile_commands.json`, it would be nice to add support for something even simpler with less untrusted code execution.

This might start the slippery slope of allowing many flag file formats (e.g. `.clang_complete`), but I think it's appropriate given this is endorsed by LLVM/Clang. Alternatively, it could be a user-supplied list of file names.

**Comment by bstaletic** [comment]
I don't see any benefit of this over the extra conf. Compilation database is nice because some tools (`bear`, `cmake`) can output that format. Is there any widely used too that can output `compile_flags.txt`?

**Comment by micbou** [comment]
Me neither. We are talking about supporting a format that can be emulated by creating a `.ycm_extra_conf.py` file with the following contents:
```python
def Settings(**kwargs):
  return {'flags': [ ... ] }
```
or that can be automatically loaded by writing a global extra conf with a few lines of code:
```python
import os


def Settings(**kwargs):
    flags = []
    previous_path = kwargs['filename']
    current_path = os.path.dirname(previous_path)
    while current_path != previous_path:
        compile_flags_path = os.path.join(current_path, 'compile_flags.txt')
        if os.path.isfile(compile_flags_path):
            with open(compile_flags_path) as compile_flags:
                for flag in compile_flags:
                    flags.append(flag.strip())
            break
        previous_path = current_path
        current_path = os.path.dirname(previous_path)
    return {'flags': flags}
```

> with less untrusted code execution.

Why untrusted? ycmd always asks users if an extra conf file is safe to load by default. In addition, users have full control on which files should be automatically loaded or ignored through [the `extra_conf_globlist` option](https://github.com/Valloric/YouCompleteMe#the-gycm_extra_conf_globlist-option).

**Comment by ecnerwala** [comment]
That sounds good, I thought it might be worth an ask. Thanks!
