### ISSUE TITLE
vim issue or YCM issue?

### ISSUE THREAD

**Issue by jungle-boogie** [Valloric/ycmd#1074]
Hi All,

I have a very simple `_vimrc` file on my Windows 8.1 machine, and yet, YCM causes vim to crash.

My `_vimrc` file:
```
execute pathogen#infect()
set encoding=utf-8
```

vim version:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 29 2018 22:08:28)
MS-Windows 32-bit GUI version with OLE support
Included patches: 1-229
```
downloaded from here:
https://github.com/vim/vim-win32-installer/releases/tag/v8.1.0229

```
 -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python36.dll\"
```

On this commit of YCM: 15362d9cb8ec054c929e9a202252825eabe47e58

Crash: `Vi Improved - A Text Editor has stopped working`

If I move the `YouCompleteMe` directory out of `C:\Users\jungle\vimfiles\bundle`, the crash doesn't occur.

I have python 3.6 32-bit installed.

Is there some issue I can check into that would explain this crash?

**Comment by jungle-boogie** [comment]
Even installing this version of vim, I have the same issue:
https://github.com/vim/vim-win32-installer/releases/tag/v8.1.0127

  version 8.1.127

Vim immediately crashes when opening.

**Comment by bstaletic** [comment]
You've given us very little info to go from. Please post the same issue in https://github.com/Valloric/YouCompleteMe and remember to fill in the whole issue template.
