### ISSUE TITLE
ycmd_core doesn't support LLVM 8?

### ISSUE THREAD

**Issue by Rakete1111** [Valloric/ycmd#1079]
ycmd_core doesn't seem to handle LLVM 8. When using YCM, I get:

```
Traceback (most recent call last):
  File "/usr/share/vim/vimfiles/third_party/ycmd/ycmd/server_utils.py", line 96, in CompatibleWithCurrentCore
    ycm_core = ImportCore()
  File "/usr/share/vim/vimfiles/third_party/ycmd/ycmd/server_utils.py", line 88, in ImportCore
    import ycm_core as ycm_core
ImportError: /usr/local/lib/libclang.so.7: version `LLVM_7' not found (required by /usr/share/vim/vimfiles/third_party/ycmd/ycmd/../ycm_core.so)
```
I do have a libclang.so.7, but it's a symlink for libclang.so.8. Is there any reason for this restriction?
Yes, I know that LLVM 8 hasn't been released yet (neither is 7; but soon) and it's experimental, but it would still be nice to support it.

**Comment by micbou** [comment]
Just tried with LLVM trunk and it's working fine. How did you build ycmd? Most straightforward way is to pass the `EXTERNAL_LIBCLANG_PATH` variable (or `PATH_TO_LLVM_ROOT`) to CMake through the `build.py` script:
```sh
CMAKE_EXTRA_ARGS="-DEXTERNAL_LIBCLANG_PATH=/path/to/libclang.so.8" ./build.py --clang-completer
```

**Comment by Rakete1111** [comment]
@micbou It looks like you're right. Thanks!

**Comment by joelhock** [comment]
for future googlers: i think you mean `EXTRA_CMAKE_ARGS` rather than `CMAKE_EXTRA_ARGS`

**Comment by micbou** [comment]
@joelhock Thanks. I edited my comment.
