### ISSUE TITLE
CMake minimum version

### ISSUE THREAD

**Issue by vheon** [Valloric/ycmd#108]
From https://github.com/Valloric/YouCompleteMe/issues/1439#issuecomment-91825098

@asenac
> I think this should be reported in ycmd project to either set the minimum cmake version required to 2.8.12, currently it is set to 8.2, or use PATH component instead to support versions between 2.8 and 2.8.12.

**Comment by shirro** [comment]
Wheezy has cmake version 2.8.9 and this change stopped me building the latest YCM. I installed with TRAVIS=1 ./install.sh

Is there a downside to doing that?

**Comment by Valloric** [comment]
@shirro If you managed to compile it, then you're fine.
