### ISSUE TITLE
Is there a way to paginate completions?

### ISSUE THREAD

**Issue by vincentwoo** [Valloric/ycmd#1083]
It seems that as of https://github.com/Valloric/ycmd/pull/830, there is a cap on the number of returned completions. If you want to fetch more of the list, is there a way to do so, or should we just set the cap very high?

**Comment by micbou** [comment]
Set [the value of `max_num_candidates` to `0`](https://github.com/Valloric/YouCompleteMe#the-gycm_max_num_candidates-option).
