### ISSUE TITLE
Incorrect completions with leading multi-byte chars in a C++ comment

### ISSUE THREAD

**Issue by abingham** [Valloric/ycmd#109]
It appears that ycmd might have some problems with multi-byte characters in C++ comments, at least in certain contexts. For example, if I do completion at the end of this example:
```
#include <vector>
/* « */ std::ve
```
I get `std::end()` as an option.

This was first noticed – and it's fairly thoroughly discussed – in [pull request 171 of emacs-ycmd](https://github.com/abingham/emacs-ycmd/pull/171).

**Comment by Valloric** [comment]
Thanks for filing this. I'll look into it when I have a bit of time.

I'm going to hate debugging this...

**Comment by Valloric** [comment]
Relevant YCM issue: https://github.com/Valloric/YouCompleteMe/issues/1378
