### ISSUE TITLE
Possible to disable syntax checking when using TSServer for JS autocompletion?

### ISSUE THREAD

**Issue by ruolin59** [Valloric/ycmd#1093]
I followed the instructions from the README for getting ycmd to work with JavaScript using TSServer, and the autocompletion works very well, but a side effect of using TSServer is that it keeps giving me warnings about syntax issues. Since my project is using ES6 with new features and such, and I'm using syntastic with eslint to do syntax checking for me, I do not need or want the syntax checking from TSServer to show up, since often times the suggestions and errors it throws are wrong. Is there a way to disable the syntax warning aspect of TSServer while still using it for autocompletion?

**Comment by micbou** [comment]
If you are using YCM, you can set [the `g:ycm_filter_diagnostics` option](https://github.com/Valloric/YouCompleteMe#the-gycm_filter_diagnostics-option) to:
```viml
let g:ycm_filter_diagnostics = { 'javascript': { 'regex': [ '.*' ] } }
```
to disable all diagnostics reported by YCM in JavaScript files. For other clients, you'll have to ask the respective maintainers.
