### ISSUE TITLE
Can't set custom gradle home for the java completer

### ISSUE THREAD

**Issue by davidebasilio** [Valloric/ycmd#1094]
Hello,

I'm trying to use the java_completer with a Gradle project and it works well for some time, but then it gets "stuck" (i.e., the server does not respond any more).

I suspect that the issue lies with the gradle daemon that jdt launches, which conflicts with gradle builds I have to run externally (not from ycm) in order to test my project.

It would be great if it were possible to completely decouple the gradle home and project files that ycmd uses, so that it doesn't clash with other instances.

**Comment by bstaletic** [comment]
The only option that mentions gradle seems to be `IMPORT_GRADLE_ENABLED`.
The full list of server preferences is [here](https://github.com/eclipse/eclipse.jdt.ls/blob/bb595f836c7fecb866422562a2ba66dbde2d5e68/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/Preferences.java). Ycmd is still missing support for LSP user configurations, but it is being worked on. You can take a look at [my branch](https://github.com/bstaletic/ycmd/tree/lsp_settings) that implements user configuration.

**Comment by micbou** [comment]
Could you please raise the issue on the YCM repository and fill [the issue template](https://github.com/Valloric/YouCompleteMe/blob/master/.github/ISSUE_TEMPLATE.md) while doing so? This would be really helpful.
