### ISSUE TITLE
Official gocode is not supported anymore

### ISSUE THREAD

**Issue by ChoppinBlockParty** [Valloric/ycmd#1097]
As it is suggested in the main page [nsf/gocode](https://github.com/nsf/gocode) is not supported anymore. Any plans to switch to a new version [mdempsy/gocode](https://github.com/mdempsky/gocode)?

**Comment by micbou** [comment]
Switching now to [mdempsky's fork](https://github.com/mdempsky/gocode) seems too premature. See https://github.com/mdempsky/gocode/issues/46#issuecomment-418087026. I think we should wait for Gocode to be ticked off in the list in issue https://github.com/golang/go/issues/24661.

**Comment by isaachier** [comment]
mdempsky's fork is more up-to-date than nsf. Eventually, it will improve further. From the original meeting notes (https://docs.google.com/document/d/1lB49VLzDrRd3wbXP1uLf-bHQyJRmH_Dc36JeEBlK-1Q):

> Current state of the nation:
> A number of tools “know” nothing about (and hence are broken from a user’s perspective) Go 1.11 module mode; e.g. goimports, gocode, guru etc
> . . .
> The work his team are doing to try and help with the migration of tools to go/packages; e.g. Rebecca Stambler will shortly (next couple of weeks) be working on fixing github.com/mdempsky/gocode (it was noted that github.com/nsf/gocode has been officially retired)

**Comment by micbou** [comment]
Implemented by PR https://github.com/Valloric/ycmd/pull/1098.
