### ISSUE TITLE
install target missing?

### ISSUE THREAD

**Issue by joakim-tjernlund** [Valloric/ycmd#1128]
I am just staring to build a ymcd for Gentoo and got some questions:
1) I cannot find install rules in CMakefile files, where and what files are supposed to be installed?
2) Playing with building a C completer I only find *.so file(s) but I read ymcd is supposed to be a server, am I missing some build step ?

Ohh, forgot to mention: I am looking for an emacs ymcd.

**Comment by joakim-tjernlund** [comment]
OK, I will try sort this out then:
ycm_core.so and the whole contents of ycmd/ycmd needs to go someplace where python looks, possibly
under /usr/lib64/python3.6/site-packages/ycmd I guess.

**Comment by bstaletic** [comment]
Yes, that is correct. There's also the ycmd/third_party which contains third_party dependencies, but I guess you figured that out already.

**Comment by bstaletic** [comment]
> Ohh, forgot to mention: I am looking for an emacs ymcd.

Are you talking about the client [emacs-ycmd](https://github.com/abingham/emacs-ycmd)? Then this is the wrong repo. This is the repo for the server component which is editor/client agnostic.

**Comment by joakim-tjernlund** [comment]
Both, I think I got emacs-ycmd under control via melpa
Now I need the server part.

Yes, there are a few third party modules but most are in Gentoo already, at least for C.
regexp seems old though(in Gentoo) so I better keep the one you use

**Comment by bstaletic** [comment]
The regex module isn't necessary. It however provides a slightly better performance and better unicode support.

**Comment by joakim-tjernlund** [comment]
I just a hour yesterday to test this but I can already now say that the lack of a
cmake install target is a major pain. Could you look at that?

**Comment by bstaletic** [comment]
Well, here's why we never saw the need for the install target.

- All developers use vim and YouCompleteMe as the client. Granted, hardcoded paths work for us, but not for other clients.
- All clients I have tried have a configuration option that point the client to the ycmd module. From there, everything is solved.
- I took a look at the emacs-ycmd instructions and here's the bit that you missed:

```
(set-variable 'ycmd-server-command '("python" "/path/to/ycmd/package/"))
```
So you could have just set that line in your emacs config and there would have been no need to fiddle with moving parts of ycmd to your system folder.

As far as I can tell the install target doesn't solve much, so pull requests are welcome.

**Comment by joakim-tjernlund** [comment]
Well, that only works well for devs. inside ycmd. Try think of whomever is
going to package this into an distribution. If you cannot work out install paths, how should
a random distr. packager do that?

**Comment by bstaletic** [comment]
Okay, package maintainers are a different story. I can look into adding the install target, but I can't make any promises regarding deadlines. Did you encounter any specific problem? You can also visit https://gitter.im/Valloric/ycmd for support.

**Comment by joakim-tjernlund** [comment]
Thanks, this will sure help !

I will be back, need to free up some time first. I do want to create a package for our us soon though. There is no way for me to maintain ycmd on many machines otherwise.

**Comment by puremourning** [comment]
Sorry, we don't support third-party packaging of ycmd. There is no install target because the installation is in-place.

**Comment by joakim-tjernlund** [comment]
@puremourning but you should really. How else is ymcd supposed gain any larger audience?
Just consider if you had to do the same to vim, emacs etc. in you system.

**Comment by bstaletic** [comment]
@joakim-tjernlund 
We're working on getting [pyinstaller](https://www.pyinstaller.org/) working. There will be binary archives available, but also packagers will be able to use that script to package ycmd for their distros.
