### ISSUE TITLE
clang-completer: Completion list should pop up despise encoding errors in a doc_string

### ISSUE THREAD

**Issue by ldonoso** [Valloric/ycmd#1162]
A utf8 doc string would cause an encoding exception. But we could just swallow the exception and present the rest of the data to the user but the doc string.
```
--- a/ycmd/completers/cpp/clang_completer.py
+++ b/ycmd/completers/cpp/clang_completer.py
@@ -486,8 +486,14 @@ def BuildExtraData( completion_data ):
   fixit = completion_data.fixit_
   if fixit.chunks:
     extra_data.update( responses.BuildFixItResponse( [ fixit ] ) )
-  if completion_data.DocString():
-    extra_data[ 'doc_string' ] = completion_data.DocString()
+
+  try:
+    if completion_data.DocString():
+      extra_data[ 'doc_string' ] = completion_data.DocString()
+  except:
+      # Not supported encoding in the `doc_string` should not prevent the activation of the completion list
+      pass
+
   return extra_data

```

**Comment by micbou** [comment]
We are not interested in supporting other encodings than UTF-8.

**Comment by ldonoso** [comment]
@micbou, please, I'm not saying ycmd should support other enconding what I'm asking is that it should be more resilient.

In case other encodings are used, the completion list could be shown anyway if the `UnicodeDecodeError` exception is discard.

**Comment by micbou** [comment]
Sorry, I should have said "dealing with".

**Comment by ldonoso** [comment]
I understand, thank you very much.
