### ISSUE TITLE
`requests` moved

### ISSUE THREAD

**Issue by Alexander-Shukaev** [Valloric/ycmd#1168]
https://github.com/Valloric/ycmd/blob/ff143810fd6d37169c6561d52ace353d9d42399c/.gitmodules#L15

It appears to be at [`https://github.com/requests/requests`](https://github.com/requests/requests) now.

**Comment by bstaletic** [comment]
Github is nice enough to not break when a repo is moved from personal project to an organization, but we should still update.

**Comment by das7pad** [comment]
I just noticed that it is back in the [`kennethreitz`](https://github.com/kennethreitz) org.

Just like many of his other repos which moved in the past few weeks, days.
