### ISSUE TITLE
Language service completer makes no distinction between GoToDeclaration and GoToDefinition

### ISSUE THREAD

**Issue by ioeric** [Valloric/ycmd#1190]
https://github.com/Valloric/ycmd/blob/master/ycmd/completers/language_server/language_server_completer.py#L52

LSP supports both textDocument/declaration and textDocument/definition requests: https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md#textDocument_declaration

**Comment by bstaletic** [comment]
The `textDocument/declaration` is a very recent addition to the protocol. When we wrote the completer there was neither `textDocument/declaration` nor do jdt.ls and clangd 7 support them.

That said, yes, `textDocument/declaration` is useful and will most likely be implemented when clangd 8 comes out.

**Comment by ioeric** [comment]
Looks like textDocument/declaration has been implemented in clangd: https://github.com/llvm-mirror/clang-tools-extra/commit/820bac171c912a763b2df27786e8e6215c3e74e4#diff-0ac995152f29b025ebe32598acf06047

**Comment by bstaletic** [comment]
Yes, two weeks ago. That commit is not in a stable release yet. That's why I said that we are waiting for clangd 8 to come out.

**Comment by ioeric** [comment]
Sorry, not trying to nag on this.

The language server release doesn't seem to be a blocker here. The completer should be able to detect whether to use `textDocument/declaration` based on the server capacities right?

**Comment by micbou** [comment]
See https://github.com/Microsoft/language-server-protocol/issues/673.
