### ISSUE TITLE
 Go Modules break compilation of --go-completer build

### ISSUE THREAD

**Issue by dan-compton** [Valloric/ycmd#1198]
#  Go module support is not compatible with the current build:  [error.log](https://github.com/Valloric/ycmd/files/2924078/error.log)

Because GOMOD111=off is not set prior to go build, go modules are created.  This causes the build to install relevant dependencies in the pkg folder.  Upon calling `go build` in the code linked below, I believe the dependencies are resolved to those in the package folder.  Because we manually `cd` to the dependency version in `GOPATH/src/.../mdemsky/`, go build fails due to references to the internal directory of the dependency found in $GOPATH/pkg/.../mdemsky.

(https://github.com/Valloric/ycmd/blob/4b022b3858a45eefad953359783111538227119c/build.py#L670_

> See the executed command and output here:  [error.log](https://github.com/Valloric/ycmd/files/2924078/error.log)

# Dependencies

## C Compiler: 
```
-- The CXX compiler identification is GNU 7.3.0
```

## go version
```go version go1.11.5 linux/amd64```

## ycmd version:
```origin/master```

# Solution

TBQH I just removed: https://github.com/Valloric/ycmd/blob/4b022b3858a45eefad953359783111538227119c/build.py#L670-L679 and pre-compiled the binaries. 

 However, I think there are two possible real approaches:

1. Modify `FindExecutableOrDie` to ensure that a call to the go binary is prefixed by `GOMOD111=off`
2. Detect go version and execute go mod init in  $GOPATH/pkg/.../mdemsky
3. Update the requirement on mdemsky

**Comment by micbou** [comment]
You should run the `build.py` script with `GO111MODULE` sets to `off` or `auto`:
```sh
GO111MODULE=off ./build.py --skip-build --no-regex --go-completer
```
Since this doesn't seem to be the default behavior (tried with Go 1.12 and didn't have to set that environment variable on any platform that we support) and the workaround is simple, I am inclined to close the issue.

**Comment by dan-compton** [comment]
GO111MODULE=off will not propagate to those calls AFAIK.  Regardless I _did_ try that and it got the same result.  Literally the same command you posted but without skip-build.  Is Go 1.12 GA?

**Comment by dan-compton** [comment]
https://stackoverflow.com/questions/53368187/go-modules-installing-go-tools

**Comment by dan-compton** [comment]
Regardless, the version of the offending library has been updated to support go modules.

**Comment by dan-compton** [comment]
No longer a user.  Have switched to coc + bingo

**Comment by micbou** [comment]
> GO111MODULE=off will not propagate to those calls AFAIK.

It sure does.
