### ISSUE TITLE
Paranthese complete

### ISSUE THREAD

**Issue by gpahlevanzadeh** [Valloric/ycmd#1202]
I code python, Can I have paranthese after complete? If yes, How write in my vimrc?

**Comment by micbou** [comment]
See https://github.com/Valloric/YouCompleteMe/issues/234 and as a Vim user, please go to [the YCM repository](https://github.com/Valloric/YouCompleteMe) to report issues. If you have questions, ask on [the Gitter room](https://gitter.im/Valloric/YouCompleteMe).
