### ISSUE TITLE
Targets may link only to libraries. CMake is dropping the item.

### ISSUE THREAD

**Issue by scarletkrath** [Valloric/ycmd#1208]
I am trying to build this with the clang and rust completers on windows 10. I have Python 3.7 and LLVM 7.0.1.

```cmake -G "Visual Studio 15 Win64" -DUSE_PYTHON2=OFF -DPYTHON_INCLUDE_DIR=C:\Users\(my user)\AppData\Local\Programs\Python\Python37-32\include -DPATH_TO_LLVM_ROOT=C:\PROGRA~2\LLVM\ -DPYTHON_LIBRARY=C:\Users\(my user)\AppData\Local\Programs\Python\Python37-32\libs ..\cpp
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
-- Found PythonLibs: C:/Users/(my user)/AppData/Local/Programs/Python/Python37-32/libs (found suitable version "3.7.2", minimum required is "3.4")
-- Using libclang to provide semantic completion for C/C++/ObjC
-- Using external libclang: C:/Program Files (x86)/LLVM/lib/libclang.lib
-- NOT using clang-tidy for static analysis.
-- Configuring done
WARNING: Target "ycm_core" requests linking to directory "C:/Users/(my user)/AppData/Local/Programs/Python/Python37-32/libs".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "ycm_core" requests linking to directory "C:/Users/(my user)/AppData/Local/Programs/Python/Python37-32/libs".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "ycm_core" requests linking to directory "C:/Users/(my user)/AppData/Local/Programs/Python/Python37-32/libs".  Targets may link only to libraries.  CMake is dropping the item.
WARNING: Target "ycm_core" requests linking to directory "C:/Users/(my user)/AppData/Local/Programs/Python/Python37-32/libs".  Targets may link only to libraries.  CMake is dropping the item.
-- Generating done
-- Build files have been written to: D:/Projectos/C-C++/ycmd/build
```

I have tried doing the same with Python 2 and the message is the same except with the `C:\Python27\libs` path. I have also tried not using the `-DPYTHON_(etc)` flags, but if I don't CMake picks the same paths.

Thank you for reading.

**Comment by micbou** [comment]
Which command did you run to get these warnings? What's your version of CMake? Did you try to follow the rest of the instructions? They are only warnings after all.

By the way, I would recommend to use the `build.py` script instead of building manually ycmd. You can set the `EXTRA_CMAKE_ARGS` environment variable to pass options to CMake and in particular `PATH_TO_LLVM_ROOT` to use a custom Clang, e.g.
```batch
set EXTRA_CMAKE_ARGS="-DPATH_TO_LLVM_ROOT=C:\Program Files (x86)\LLVM"
python build.py --clang-completer --rust-completer
```

**Comment by scarletkrath** [comment]
Wait. I'm confused. I thought you were supposed to use the build script and then do stuff with cmake. When I just use the build script, emacs-ycmd shows `REQUEST [error] Error (error) while connecting to http://127.0.0.1:(my port)/event_notification`

I believe at some point I managed to fix that but the error was `ycmd server exited abnormally with code 1`.

**Comment by micbou** [comment]
> Wait. I'm confused. I thought you were supposed to use the build script and then do stuff with cmake.

I don't see anything in the docs that would suggest this.

> When I just use the build script, emacs-ycmd shows REQUEST [error] Error (error) while connecting to http://127.0.0.1:(my port)/event_notification

Is there anything in the ycmd stderr logfile?

**Comment by scarletkrath** [comment]
Sorry, I was using the YouCompleteMe guide because I read the issues I was having had to do with how I built ycmd so I looked at it.

Where is the stderr logfile? There are many in the ycmd directory.

**Comment by micbou** [comment]
> Where is the stderr logfile? There are many in the ycmd directory.

emacs should provide a command (`'ycmd-show-debug-info` I believe) that display information on the server and in particular the path to the logfiles. The stderr logfile should be in your temporary folder and named to something like `ycmd_24160_stderr_e3y81iw6.log`. Once you found it, paste its contents here.

**Comment by scarletkrath** [comment]
Sorry, the command doesn't show the path. Something interesting though is that the server is indeed running.

```Ycmd debug information for buffer main.cpp in c++-mode:

No debug info available from server

Server is running at: 127.0.0.1:54866

Ycmd Mode is enabled

--------------------

Ycmd version:   1.3snapshot (package: 20180724.1256)
Emacs version:  26.1
System:         x86_64-w64-mingw32
Window system:  w32```

I've bulk searched "stderr" in both of my drives and there's nothing related to ycmd. The `temp` file in my C: drive only has NVIDIA stuff.

**Comment by micbou** [comment]
Looks like the emacs client doesn't create any ycmd logfiles. Isn't there a special buffer in emacs that contain the ycmd logs? If not, you can check if ycmd has been properly built by running the following commands in the ycmd folder:
```batch
copy ycmd/default_settings.json default_settings.json
python ycmd --options_file default_settings.json
```
If you see something like
```
serving on http://localhost:24804
```
then the server is working and you are most likely experiencing an issue with the emacs client.

**Comment by scarletkrath** [comment]
Hello, this is what I get when running those exact commands:
```
2019-03-19 11:21:52,850 - ERROR - DLL load failed: %1 is not a valid Win32 application.
Traceback (most recent call last):
  File "D:\Projects\C-C++\ycmd\ycmd\utils.py", line 626, in ImportAndCheckCore
    ycm_core = ImportCore()
  File "D:\Projects\C-C++\ycmd\ycmd\utils.py", line 617, in ImportCore
    import ycm_core as ycm_core
ImportError: DLL load failed: %1 is not a valid Win32 application.
```

**Comment by bstaletic** [comment]
There's something wrong with how you have compiled YCM. Run `install.py` again and show us the whole output.

**Comment by micbou** [comment]
You are getting this error because ycmd is unable to find the library `libclang.dll`. Add `C:\Program Files (x86)\LLVM\bin` to your PATH.

**Comment by scarletkrath** [comment]
There isn't any `install.py` in the directory. Do you mean `build.py`?
`C:\Program Files\LLVM\bin` is in my path. Just to be sure, I replaced it for `C:\Program Files (x86)\LLVM\bin` and it does show the `serving on ()` message only it shows my hostname instead of localhost. I don't know if it's the same.

Regardless of that, emacs still shows `Ycmd server exited abnormally with code 1`, but I believe that has more to do with emacs, right? Thank you.

**Comment by bstaletic** [comment]
> There isn't any install.py in the directory. Do you mean build.py?

The `install.py` is the vim client's wrapper for `build.py`, so yeah I did mean `build.py`.

> C:\Program Files\LLVM\bin is in my path. Just to be sure, I replaced it for C:\Program Files (x86)\LLVM\bin and it does show the serving on () message only it shows my hostname instead of localhost. I don't know if it's the same.

That sounds like ycmd is working as expected.

> Regardless of that, emacs still shows Ycmd server exited abnormally with code 1, but I believe that has more to do with emacs, right? Thank you.

If you passed `ycmd/default_settings.json` on the command line, instead of copying it somewhere and passing that other path, ycmd deleted the original. You can restore it with `git checkout ycmd/default_settings.json`. If that's not what is wrong, you should ask for help on the emacs client issue tracker.

**Comment by scarletkrath** [comment]
Yeah, it doesn't work. The same error message happens. Regardless, thank you for helping me.

**Comment by micbou** [comment]
You should raise an issue on [the emacs-ycmd repository](https://github.com/abingham/emacs-ycmd) then. Closing.
