### ISSUE TITLE
Migrate Go completer to gopls

### ISSUE THREAD

**Issue by micbou** [Valloric/ycmd#1217]
See https://github.com/golang/go/wiki/gopls.

**Comment by bstaletic** [comment]
In case anyone is following, this is ready.
https://github.com/bstaletic/ycmd/tree/gopls

The problem is that Traavis is running Ubuntu 14.04 which has an ancient go compiler, so we need to upgrade it to 16.04, which breaks the java completer.

**Comment by sebastianst** [comment]
Any ETA for when this lands in YCM? Currently, ycm is not working in module-enabled go projects and gopls would be a great solution. `vim-go`'s omnifunc completion works (using gopls) btw.

**Comment by bstaletic** [comment]
For everyone following: https://github.com/Valloric/ycmd/pull/1243

**Comment by preslavmihaylov** [comment]
Since the related PRs are merged, shouldn't this issue be closed?

**Comment by bstaletic** [comment]
Yes, it should be closed. It should have been taken care of by the bot, but oh well.
