### ISSUE TITLE
Enhacement question: can we use ycmd to autoinsert header names?

### ISSUE THREAD

**Issue by amno1** [Valloric/ycmd#1218]
Just a thought, I wonder if we could use ycmd to autoinsert include headers?

I just saw this package: https://github.com/syohex/emacs-cpp-auto-include which uses lots of regexes to parse typed text and include header files for some functions in standard library. That is probably quite heavy on Emacs which already isn't fastest app around.

Question is, can we achieve same effect with ycmd? Ycmd can autocomplete based on include headers, and since include std library headers are always present, can we simply always search those when some variable is set, say ycmd-autocomplete-stdlib-p. Then we could just type symbols from stdlib and have ycmd autoinsert the header for symbol if inclusion line is not already present, as well as the corresponding _using_ statement when coding c++.

Maybe it would be even possible to add custom headers to autocomplete function which could potentialy save even more typing. 

I see some gotchas with it, say when forward declaring classes and stuff, but I don't know. I haven't tested _emacs-cpp-auto-include_ yet so I don't really know. I just stumbled upon it by looking for something else and it seems as an interesting idea but I really don't know how well it works.

**Comment by bstaletic** [comment]
Something like this is already possible with the clangd completer. If an index of your project is available (even if only in ram) and you have used, say, a `std::vector` in one TU, but not in other, clangd is able to suggest `std::vector` and will automatically add `#include <vector>`.

A few things are needed for this to work:

0. A compilation database (at least for now, support for extra confs is planned)
1. `-background-index` to let clangd create an in-memory index in the background (will be default in clangd 9)
2. `-index` to enable "global completion" across translation units
3. Optionally `-header-insertion-decorators=1` to have a sort of marker next to any completion entry that would result in include statement insertion.

**Comment by micbou** [comment]
In addition to what @bstaletic said, the client needs to support applying [FixIt](https://valloric.github.io/ycmd/#definition-FixIt)s to buffers after selecting a completion. I believe only the Vim client currently support that feature.

**Comment by micbou** [comment]
Closing as the question has been answered.
