### ISSUE TITLE
Update Jedi to v0.0.9

### ISSUE THREAD

**Issue by renstrom** [Valloric/ycmd#122]
It's been a while since the Jedi completer got updated, and v0.0.9 got released about a week ago. So I figured this would be a good time to bump that dependency since there's been over [900 commits](https://github.com/davidhalter/jedi/compare/68378a146828a9521f7ac1c0f02d2a95abf3fac3...master) (10,284 additions, 7,243 deletions) since. Unless there's something specific keeping this back?

**Comment by Valloric** [comment]
Fixed in 813b936a994ec21ca7ca108058426a35a87cc8f1
