### ISSUE TITLE
Future + Certifi module - I had to install with pip

### ISSUE THREAD

**Issue by amno1** [Valloric/ycmd#1221]
I had ycmd working just fine yesterday. Today I updated system (arch linux) and when I started Emacs (I use ycmd with Emacs), ycmd crashed. 

Long story short, I had to install future and certifi modules through pip.

Long story: I recompiled everything, ycmd & co, from git and reinstalled, but I still got core crashing. Whatever I did I got "Ycmd server exited abnormally with code 1". When I run ycmd manually form cmd line 

`python /usr/share/ycmd/ycmd `

I got missing modules, first 'future' and than 'certifi':

```
$ python /usr/share/ycmd/ycmd/
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/share/ycmd/ycmd/__main__.py", line 44, in <module>
    from ycmd.hmac_plugin import HmacPlugin
  File "/usr/share/ycmd/ycmd/hmac_plugin.py", line 25, in <module>
    import requests
  File "/usr/share/ycmd/third_party/requests_deps/requests/requests/__init__.py", line 112, in <module>
    from . import utils
  File "/usr/share/ycmd/third_party/requests_deps/requests/requests/utils.py", line 24, in <module>
    from . import certs
  File "/usr/share/ycmd/third_party/requests_deps/requests/requests/certs.py", line 15, in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'
```
_sudo pip install future_ and sudo _pip install certifi_ solved problems. When I look into source code, third_party on git, I see python-future is included, and I also see that arch PKGBUILD script does build it. Maybe certifi should be included as a 3rd party too or listed as a dependency?

I also have no idea why I needed to install future through pip when it is included in 3rd party, I can see it installed via pacman from what I build with PKGBUILD:

> $ ls /usr/share/ycmd/third_party/
> totalt 28
> drwxr-xr-x 5 root root 4096 29 mar 16.29 bottle
> drwxr-xr-x 3 root root 4096 29 mar 15.32 clang
> drwxr-xr-x 3 root root 4096 29 mar 16.29 frozendict
> drwxr-xr-x 4 root root 4096 29 mar 15.32 jedi_deps
> drwxr-xr-x 5 root root 4096 29 mar 16.29 python-future
> drwxr-xr-x 7 root root 4096 29 mar 15.32 requests_deps
> drwxr-xr-x 4 root root 4096 29 mar 16.29 waitress

If anyone could enlighten me on that issue I am glad to hear :-)

**Comment by bstaletic** [comment]
`requests` used to bundle its dependencies. That's no longer the case, so ycmd moved `request` to `ycmd/third_party/requests_deps/requests` and put `certifi`, `idna`, `chardet` and `urllib3` in their respectice directories in `requests_deps`.

So `certifi` and others are definitely in `third_party`. I'd usually tell you that you forgot `git submodule update --init --recursive`, but you're using a `PKGBUILD`.

**Comment by puremourning** [comment]
> ls /usr/share/ycmd/third_party/

I’m sorry we don’t support third party packaging.

**Comment by puremourning** [comment]
Wait maybe I misunderstood. Can you please list the commands you ran to install ycmd and include the build output.

**Comment by amno1** [comment]
I used pkgbuild from aur (ycmd-git). Unfortunatly I am not at home now so I can post what it exactly does. I don't know before I look at it tomorrow if it handles git correctly or not.


Skickat från min Samsung Galaxy-smartphone.


-------- Originalmeddelande --------
Från: Ben Jackson <notifications@github.com>
Datum: 2019-03-29 20:00 (GMT+01:00)
Till: Valloric/ycmd <ycmd@noreply.github.com>
Kopia: amno1 <arthur.miller@live.com>, Author <author@noreply.github.com>
Ämne: Re: [Valloric/ycmd] Future + Certifi module - I had to install with pip (#1221)


Wait maybe I misunderstood. Can you please list the commands you ran to install ycmd and include the build output.

**Comment by puremourning** [comment]
>I used pkgbuild from aur (ycmd-git).

ok in that case raise with the maintainer of that
