### ISSUE TITLE
Allow to configure number of threads

### ISSUE THREAD

**Issue by blueyed** [Valloric/ycmd#123]
ycmd starts waitress with 30 threads, which is way more than the default of waitress (4) (Code ref: https://github.com/Valloric/ycmd/blob/master/ycmd/__main__.py#L160).

Is there a particular reason to use so many threads, especially since this gets multiplied by the number of Vim processes (via YouCompleteMe).

It would be nice if this could be made configurable, and then e.g. YouCompleteMe could use a lower number by default?!

**Comment by Valloric** [comment]
There _are_ good reasons for this number of threads, and it's because some C++ completions can take a substantial amount of time to return (for files with large TUs).

I haven't see any data that shows that this number of threads is hurting performance of the system.
