### ISSUE TITLE
C++ `new` keyword not showing constructors

### ISSUE THREAD

**Issue by qinq-net** [Valloric/ycmd#1230]
When I use `new` to create a C++ object from a class, it does not show constructors in the candidate list. Only if I create an object by non-pointer style will it trigger completion for constructors.

**Comment by micbou** [comment]
Works fine for me with the libclang and Clangd completers. Please be more specific and provide a reproducible test case. See [CONTRIBUTING.md](https://github.com/Valloric/ycmd/blob/master/CONTRIBUTING.md) for more detail.
