### ISSUE TITLE
Can't work with company-quickhelp.And can't complete function arguments

### ISSUE THREAD

**Issue by kong13661** [Valloric/ycmd#1237]
company-ycmd can not be compatible with company-quickhelp. Besides, there are no function arguments in candicates when inside a function. But if I use company-jedi, both work well. Is there any way to handle it？

**Comment by bstaletic** [comment]
Company-ycmd is a ycmd plugin, if I'm not mistaken. Either way we're not the maintainers of that thing.

**Comment by micbou** [comment]
Please report issues on the appropriate repository.

**Comment by kong13661** [comment]
I'm sorry. I didn't notice this...
