### ISSUE TITLE
 []( py::object o ) -> py::bytes, the parameter 'o' is copied for each invocation but only used as a const reference; consider making it a const reference

### ISSUE THREAD

**Issue by leihuxi** [Valloric/ycmd#1238]
I think it's bitter to use refrence as below:
 third_party/ycmd/cpp/ycm/ycm_core.cpp:72:44
  mod.def( "GetUtf8String", []( const py::object & o ) -> py::bytes {

**Comment by micbou** [comment]
No, it's not. See PR https://github.com/Valloric/ycmd/pull/1231.
