### ISSUE TITLE
Compiling ycm with GCC throws warnings and terminates

### ISSUE THREAD

**Issue by redkite** [Valloric/ycmd#1268]
Since move semantics have been patched into ycm, GCC complains about useless call to `std::move` if it's called on primitive types.

Example error message:
```
~/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/CodePoint.cpp:95:14: error: std::move of the expression of the trivially-copyable type 'const char *' has no effect; remove std::move() [performance-move-const-arg,-warnings-as-errors]
  : normal_( std::move( code_point.normal ) ),
             ^~~~~~~~~~~~~~~~~~~~~        ~~~
```

I am running GCC 9.1, but also tested with GCC8. Would be nice to have this fixed, I could also prepare a patch if that makes things easier.

**Comment by puremourning** [comment]
Does this prevent building or cause any actual problem?

@bsaletic were you looking at this at one point?

**Comment by redkite** [comment]
If I use the `install.py` script of YouCompleteMe (which uses this repo as a submodule) it treats all warnings as errors, so yes. It abort building due to the raised warnings.

You could probably treat warnings as errors, but it IMHO the better solution is to fix the warnings.

**Comment by puremourning** [comment]
Agree. We should resolve these.

**Comment by puremourning** [comment]
Then again, I compiled ycmd with GCC 8 earlier today with no issue.

**Comment by redkite** [comment]
Just as a quick update: I tried to build with `build.py` in the ycmd and this builds without issues. I only seem to have issues with `install.py` in [YouCompleteMe](https://github.com/Valloric/YouCompleteMe).

Exact versions are: 
`g++ (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0`
`g++ (Ubuntu 9.1.0-1ubuntu1~18.04.york0) 9.1.0`

I can dig deeper into this tomorrow. Seems to be very strange since `install.py` only seems to be a wrapper for building.

**Comment by bstaletic** [comment]
GCC 9 does have this type of warnings and ycmd did at one point raise these.

I'm on a phone, so I can't dig pull requests up, but I have fixed this and I use gcc 9 to compile ycmd routinely.

@redkite Please check your ycmd commit and update.

Also "warnings as errors" is only set up for debug build (`--enable-debug`) flag, though some `$CXXFLAGS` can implicitly persist across builds under some circumstances.

@redkite How exactly are you running `install.py`?

**Comment by redkite** [comment]
I am running it directly from the folder and using system Python on Ubuntu 18.04, which is 2.7: `./install.py --clang-completer --clang-tidy --enable-coverage --rust-completer`

The current HEAD for the ycmd submodule is `1827ebee82fd41dac408ffe4c7b1e867ac72ee7c`. Just noticed that there is one more commit (in the cpp subfolder) on the master of this repository, which seems to fix this. If that's the case sorry for the issue, it seems I should rather file one against the YouCompleteMe repo to get the submodule updated?

**Comment by bstaletic** [comment]
`--enable-coverage` implies `--enable-debug`, so that the coverage information is correct. It also means you're not running a fully optimized build. This definitely results in bad performance.

Also `--clang-tidy` flag only runs clang tidy against ycmd's codebase. If you want clang-tidy integration, you will have to switch to the clang**d** completer.

Anyway, this is user error. Closing.

**Comment by puremourning** [comment]
@redkite what led you to choose to add those switches?

**Comment by redkite** [comment]
The first one just to tinker around, clang-tidy because I hoped it would enable clang-tidy. In hindsight obviously a bit stupid, my brain skipped over the developer part in the description, because I of course use it for development. Might help to separate internal dev-options a bit more from the regular ones, on the other hand I could've just read it a bit more thorough I suppose.
