### ISSUE TITLE
Move cursor after completion

### ISSUE THREAD

**Issue by pwntester** [Valloric/ycmd#133]
Hi,

Is it possible to move the cursor to a specific positon after the completion? I have seen this is possible with UltiSnip where cursor goes to the first placeholder.

I have written a custom completer which can complete xml tags and I would like to move the cursor after the opening tag. Is it possible using BuildCompletionData?

Thanks

**Comment by Shougo** [comment]
> Is it possible to move the cursor to a specific positon after the completion? I have seen this is possible with UltiSnip where cursor goes to the first placeholder.

Unfortunatelly, plugins cannot move cursor after completion.
It is limited by Vim.

**Comment by pwntester** [comment]
Thanks, UltiSnip seems to be able to do it so I will take a look and see if it's possible somehow otherwise will just complete the opening tag and add a second completion for the closing one. 

Thanks, 
A

**Comment by vheon** [comment]
@pwntester Ultisnips is not a completion plugin so it is not limited by the `omnifunc` feature of vim.

**Comment by pwntester** [comment]
Oh, I see, thanks!

**Comment by Valloric** [comment]
Closing per @Shougo.
