### ISSUE TITLE
Mixing custom completer and ycmd completers

### ISSUE THREAD

**Issue by pwntester** [Valloric/ycmd#134]
Hi,

I have implemented a custom completer and I would like ycmd to return the custom suggestions along with the ycmd ones (eg: Ultisnip and identifier) but Im only getting my own completer suggetions, and no UltiSnip anymore. Is it possible to merge the suggestions?

Thanks

**Comment by vheon** [comment]
No it isn't. If you think about it you write a semantic triggers and you're completer kick in, at that moment the user expect a certain kind of completion, i.e. a semantic completion for the point where you're typing. If you mix them together then I would have candidate relevant for the point I'm typing and candidate which could be taken from the identifier-based engine that aren't relevant for this particular point.

**Comment by JazzCore** [comment]
>No it isn't. If you think about it you write a semantic triggers and you're completer kick in, at that moment the user expect a certain kind of completion, i.e. a semantic completion for the point where you're typing. If you mix them together then I would have candidate relevant for the point I'm typing and candidate which could be taken from the identifier-based engine that aren't relevant for this particular point.

Actually it is, [general completers](https://github.com/Valloric/ycmd/tree/master/ycmd/completers/general) made exactly for what author wants (both UltiSnips and filename completers are general completers).
Such completer is a subclass of ``GeneralCompleter`` class. Basically you need to make your own completer implement ``GeneralCompleter`` interface and then add it to ``general_completer_store.py`` to properly work along with other general completers. Code for general completers is pretty self-documenting, so it should not be hard to do.

**Comment by pwntester** [comment]
That makes sense if there is a context (already typed characters, a dot, etc ...) but if user hits ctrl-space with no context, it makes sense to me to return all candidates. In my case, my completer returns possible xml elements according to the schema and ultisnip returns snippets that includes more complex xml elements with predifined values, nested tags, etc.

Could it be possible to merge candidates when there is no context?

**Comment by pwntester** [comment]
Thanks @JazzCore!

**Comment by Valloric** [comment]
Note that there is no support for user-level custom completers that haven't been upstreamed to ycmd. The Completer API is internal-only.
