### ISSUE TITLE
hardcoded libclang.dll in ycmd\cpp\ycm\CMakeLists.txt

### ISSUE THREAD

**Issue by strrchr** [Valloric/ycmd#165]
In Line 317:
COMMAND ${CMAKE_COMMAND} -E copy "${PATH_TO_LLVM_ROOT}/bin/libclang.dll" "$")
I think it should be:
COMMAND ${CMAKE_COMMAND} -E copy "${LIBCLANG_TARGET}" "$")
I made the modification and the build using cmake+ninja is OK.

I encounter error when compile ycm_support_libs using msys2.
There is clang.dll in msys2\mingw64\bin, but not libclang.dll.

Sorry, I haven't learned how to make a PR.
So I just commit this issue.

**Comment by micbou** [comment]
`${LIBCLANG_TARGET}` is `libclang.lib` when compiling with MSVC and we need `libclang.dll` hence the hardcoded `libclang.dll`. I will send a PR to only do this with MSVC.

Anyway, I recommend you to compile ycmd with MSVC. Clang support is better than MinGW one.

**Comment by Valloric** [comment]
Fixed by #166.
