### ISSUE TITLE
How to config ycm to support completion of function parameters and completion of override functions

### ISSUE THREAD

**Issue by talkw-liu** [Valloric/ycmd#170]
I need your help,I'm waiting for your idea...

**Comment by vheon** [comment]
it is not possible at the moment to complete function's parameters.

**Comment by talkw-liu** [comment]
Why cannot it complete like visual studio?

**Comment by vheon** [comment]
There is a proposal in the vim client Valloric/YouCompleteMe#1300 but we're waiting at least for clang 3.7 and there's still some design to figure out.

**Comment by Valloric** [comment]
We're already tracking this work; closing this issue.
