### ISSUE TITLE
Make ycmd check ycm_core version for compatibility

### ISSUE THREAD

**Issue by Valloric** [Valloric/ycmd#171]
ycmd has always had a compiled component (ycm_core) and a Python component (the rest of ycmd). YCM has always been checking that the API version that was [compiled into the ycm_core library](https://github.com/Valloric/ycmd/blob/master/cpp/ycm/versioning.cpp#L23) matches the version that [the Python code expects](https://github.com/Valloric/YouCompleteMe/blob/master/python/ycm/base.py#L176).

For historical reasons, this API version check is currently being done in the YCM client and not ycmd. Since ycmd now has multiple clients, there's no guarantee that the other clients are performing this check; in cases where they aren't, a poor user experience (unintelligible Python tracebacks) will result in case of API mismatch which can easily happen if they pull in a more recent version of the ycmd code without recompiling ycm_core. 

The idea is to move this check into ycmd.

From now on, ycmd will verify the API version and will exit with a status code of 2 if there's a mismatch. Since it might be burdensome for clients to first start ycmd and then examine did it crash after a few seconds, a separate script (`check_core_version.py`) will be provided whose sole job is to quickly check the API version and exit with code 0 on sucess and 2 on mismatch. This script can then be called by editors in a blocking fashion on startup.

@abingham @ptrv @mawww @Qusic

**Comment by micbou** [comment]
I think it would be easier to maintain if there was only one place to set the core version. One way to achieve this would be to get the core version with cmake and create the corresponding preprocessor variable which will be used in the C++ code. I tried this approach in commit 48e0d3b242e8215f4e0f9abc9915647a44f11f8a and it is working well. I could send a PR if you agree with this.

**Comment by Valloric** [comment]
I did in fact think of that approach, but the thing is that YCM has a different build system for the Google-internal build and reproducing that preprocessor variable approach there would be a pain.

I appreciate you trying this out though; your commit also reminded me that I forgot to add the copyright comment. :)

**Comment by micbou** [comment]
Oh, I see. I will keep the commit just in case. Could be useful later.

**Comment by r4nt** [comment]
I think we'd be able to do this in our internal build system, as long as there's a generated header we need to #include to get at the version (we can generate headers just fine)

**Comment by Valloric** [comment]
@r4nt Oh we could, it would just be a hassle. I don't think it's worth it. I could be wrong.

**Comment by micbou** [comment]
@Valloric From issue #1620, I was wondering if we could reconsider the approach discussed here where we only need to maintain the core version in one place.

**Comment by Valloric** [comment]
Since @r4nt is maintaining that Google-internal part now, if he's fine with the compiler define approach, then I'm fine with it too. Send a PR.
