### ISSUE TITLE
Scheme identifier matching

### ISSUE THREAD

**Issue by sullyj3** [Valloric/ycmd#172]
I've had a shot at creating a regex which matches scheme identifiers, according to http://www.schemers.org/Documents/Standards/R5RS/HTML/ (section 2.1)
sullyj3/ycmd@c9f91dc2c73b6d7aff31138d605db697d93995c0
I ran into some trouble, as you can see in the commit message. I decided not to open a pull request, but I thought I'd throw it out here in case anyone better at regex than me has a 5 second fix :)

**Comment by Valloric** [comment]
Thanks for posting that; someone might want to build upon your work in the future.
