### ISSUE TITLE
MacPorts python + MacVim

### ISSUE THREAD

**Issue by joeroback** [Valloric/ycmd#174]
I found a fix for using MacPorts python + MacVim with YouCompleteMe and ycmd.

$ sudo port select --set python python27
$ sudo port select --set python2 python27

Now patch ycmd. without this, PythonLibs correctly finds 2.7 libraries, but PythonInterp is set to python2.6 (which is wrong version plus comes from /usr/bin)

Once I removed the 2.6 everything worked perfectly.

diff --git a/cpp/ycm/CMakeLists.txt b/cpp/ycm/CMakeLists.txt
index e5df44f..7a9ff0b 100644
--- a/cpp/ycm/CMakeLists.txt
+++ b/cpp/ycm/CMakeLists.txt
@@ -22,10 +22,10 @@ set( CLIENT_LIB "ycm_client_support" )
 set( SERVER_LIB "ycm_core" )
 
 set( Python_ADDITIONAL_VERSIONS 2.7 2.6 )
-find_package( PythonLibs 2.6 REQUIRED )
+find_package( PythonLibs 2.7 REQUIRED )
 # The version of PythonInterp controls the version of boost.python which
 # is pulled in later, otherwise the highest python version is used
-find_package( PythonInterp 2.6 REQUIRED )
+find_package( PythonInterp 2.7 REQUIRED )

**Comment by Valloric** [comment]
Thanks for sending this in, others might find it useful. Note that using anything other than system python on Mac OS X is unsupported.

**Comment by joeroback** [comment]
ok, so your CMake finds python libs 2.7 and python interp 2.6.. its not a question of supporting, that cmake is broken.

**Comment by joeroback** [comment]
i guess its a bug in cmake. oh well. python is such a piece of garbage.

**Comment by joeroback** [comment]
I actually dont know what happened here. Maybe I had a really old version of ycmd or what.. but in build.py, CustomPythonCmakeArgs() correctly overrides the python paths for Mac (and only Mac).

I deleted my vim bundle, installed it fresh via Vundle, and re-ran ./install.sh --clang-completor and everything works with MacPorts now. MacPorts MacVim, MacPorts python2.7 (port select --set python python27 && port select --set python2 python27)

Sorry for the confusions.
