### ISSUE TITLE
Feature Request: New general completer (or, pluggable completer)

### ISSUE THREAD

**Issue by wladston** [Valloric/ycmd#190]
I wanted to create another general completer, in addition to `filename_completer.py`, `general_completer_store.py` and `ultisnips_completer.py`: `emoji_completer.py`!

Since the user might want to insert emoji in the most various types of source code, it makes sense to create a general completer plugin for emoji.

In this case, do I make a pull request to this repository, or do I create another external plugin to ycmd? In this case, how to "plug" my external completer into ycmd without having to edit ycmd's source?

Thanks!

**Comment by vheon** [comment]
At the moment external completers are not pluggable, they have to be in the repo. Anyway since by default YCM is not enabled in text, markdown or anything that it isn't code, I don't think that it makes much sense to include a completer for emoji into YCM.

**Comment by wladston** [comment]
@vheon well, I use YMC for text. And I like to add emojis to my comments. in the code, makes them more compact. Either way, we can all agree that ycmd should allow pluggable completers, right?

**Comment by Valloric** [comment]
@wladston I'm happy to hear that YCM works for you when completing text, but @vheon is correct in saying that text completion support is not in scope for YCM. So an emoji completer is not something we'd merge in.
