### ISSUE TITLE
Licensing for a new completer

### ISSUE THREAD

**Issue by sztomi** [Valloric/ycmd#21]
If I were to implement a new completer (subclassing the Completer class), would I be required to license my code under the GPLv3? I would prefer to license it under MIT or similar.

**Comment by tony** [comment]
@Valloric What is your rationale behind making ycmd and YouCompleteMe virally licensed?

**Comment by vheon** [comment]
@tony I'm no expert but if you do not provide a licence, then how can other clients use ycmd for example?

**Comment by Valloric** [comment]
Discussing why YCM is using one license and not another will not result in fruitful debate.
