### ISSUE TITLE
Use libclang 3.7

### ISSUE THREAD

**Issue by Valloric** [Valloric/ycmd#214]
[It came out today.](http://llvm.org/releases/download.html#3.7.0) We need to update the links and hashes in the CMakeLists.txt file.

**Comment by vheon** [comment]
So we could look forward for https://github.com/Valloric/YouCompleteMe/pull/1300 :stuck_out_tongue_winking_eye:

**Comment by oblitum** [comment]
hey! no pressure. =)
Em 02/09/2015 18:24, "Andrea Cedraro" <notifications@github.com> escreveu:

**Comment by vheon** [comment]
Since #217 has been merged we can close this.
