### ISSUE TITLE
Vim 7.4-865 crashes with SEGV when typing `.` in a Ruby file

### ISSUE THREAD

**Issue by exchgr** [Valloric/ycmd#220]
Steps to reproduce:
1. Install and update YouCompleteMe to the latest version.
1. Open a new or existing Ruby file in Vim.
1. Type `.` in insert mode.

Expected: Vim continues working

Actual: Vim crashes with SEGV

Note: Typing `.` with YouCompleteMe disabled works fine in Vim 7.4-865.

System: OS X 10.10.5, iTerm2 2.1.1, YCM revision `a2808ee`

**Comment by vheon** [comment]
This smell like a rbenv/rvm kind of version. Could you try to:

- Disable YouCompleteMe
- Start vim
- `:ruby puts 1`

If it craches then it isn't YCM fault.

**Comment by exchgr** [comment]
Yep, it crashes. That reminds me that I was cleaning out some old ruby versions earlier today. Thanks!
