### ISSUE TITLE
c++: internal compiler error: Killed (program cc1plus)

### ISSUE THREAD

**Issue by zhongke** [Valloric/ycmd#224]
I try to run the command:
./build.py --clang-completer --omnisharp-completer --gocode-completer

My environment:
    Ubuntu 14.04
    g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
    gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
    Python 2.7.6

If you need more information, please let me know.
Thanks 

BRs
Kevin

Error shows below;

[ 86%] Building CXX object ycm/CMakeFiles/ycm_core.dir/ycm_core.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[3]: *** [ycm/CMakeFiles/ycm_core.dir/ycm_core.cpp.o] Error 4
make[2]: *** [ycm/CMakeFiles/ycm_core.dir/all] Error 2
make[1]: *** [ycm/CMakeFiles/ycm_support_libs.dir/rule] Error 2
make: *** [ycm_support_libs] Error 2
Traceback (most recent call last):
  File "./build.py", line 196, in <module>
    Main()
  File "./build.py", line 189, in Main
    BuildYcmdLibs( GetCmakeArgs( args ) )
  File "./build.py", line 159, in BuildYcmdLibs
    subprocess.check_call( build_command )
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'ycm_support_libs', '--', '-j', '1']' returned non-zero exit status 2

**Comment by micbou** [comment]
Likely a memory issue. Check the [documentation](https://github.com/Valloric/YouCompleteMe#i-get-an-internal-compiler-error-when-installing) and my answer in this [issue](https://github.com/Valloric/YouCompleteMe/issues/1618). I am closing this since this is not a YCM issue but a configuration one.

**Comment by zhongke** [comment]
ok. Thanks for your information!

**Comment by iceonsun** [comment]
https://bitcointalk.org/index.php?topic=304389.0

`free
dd if=/dev/zero of=/var/swap.img bs=1024k count=1000
mkswap /var/swap.img
swapon /var/swap.img
free`
hope this help
