### ISSUE TITLE
Protocol documentation

### ISSUE THREAD

**Issue by hydrargyrum** [Valloric/ycmd#242]
I think there should be a somehow more formal documentation of the protocol than just example_client.py. The example_client has messy code (uses multiple HTTP client libraries) and doesn't use all the features.
Something like this: https://gist.github.com/hydrargyrum/78c6fccc9de622ad9d7b

**Comment by Valloric** [comment]
Agreed, we should have more docs. :)

I currently don't have time to write any, so PRs adding docs would be very welcome.

**Comment by puremourning** [comment]
Wow @hydrargyrum that's a great start! A PR for API docs would be very cool.

**Comment by puremourning** [comment]
For anyone stumbling across this, I made a start on this over here: http://puremourning.github.io/ycmd-1/

**Comment by Valloric** [comment]
@puremourning That looks fantastic! PR? :)
