### ISSUE TITLE
ycm can't find std lib relative to compiler path.

### ISSUE THREAD

**Issue by d0k** [Valloric/ycmd#250]
If I have a cmdline in my compilation database like '/foo/bar/bin/clang -c test.cc' and my stdlib is relative to the clang binary, i. e. /foo/bar/include/c++, ycmd won't find it. This is a libclang issue and ycm is currently cutting of argv[0] when it passes it on.

See also http://lists.llvm.org/pipermail/cfe-dev/2015-October/045537.html

**Comment by puremourning** [comment]
As you point out in the attached cfe-dev posting, indict think there is anything ycmd can do about this. Can you not include the library directories in your build flags?

**Comment by micbou** [comment]
Fixed by PR #353.
