### ISSUE TITLE
Is possible to package ycmd for a GNU/Linux distribution?

### ISSUE THREAD

**Issue by shackra** [Valloric/ycmd#252]
Because I'm trying to make a [PKGBUILD](https://aur4.archlinux.org/) and I really don't understand what to do after calling `build.py`.

And the check of CMake for the `third-party`  directory makes harder to omit the `git submodule init` step, which is not ideal because any dependency would be provided by the Distribution's repository of software.

And how are you supposed to add support for completing, let's say, Go code if you compiled the server without the `--gocode-completer` flag for `build.py`?

This project really need more precise and clear documentation...

**Comment by Valloric** [comment]
Well, ycmd isn't really designed to be used by itself. It's meant to be bundled as part of a larger application than needs code-comprehension features. All current users of ycmd are editor plugins which bundle it together (YCM, emacs-ycmd, the Atom client etc) and distribute it through whatever mechanism the editor uses for plugins.

So while one _could_ package ycmd into an OS distro, I don't really see much point to that (I could be missing something). The clients would most likely still end up bundling one themselves.

> And the check of CMake for the third-party directory makes harder to omit the git submodule init step, which is not ideal because any dependency would be provided by the Distribution's repository of software.

I'm not sure I understand what you're trying to say here; could you elaborate a bit?

> And how are you supposed to add support for completing, let's say, Go code if you compiled the server without the --gocode-completer flag for build.py?

Well, you're supposed to build ycmd for the configuration you need. You're not meant to add support for new features post-build. It's a lot like the `configure` step of autotools.

**Comment by shackra** [comment]
> I'm not sure I understand what you're trying to say here; could you elaborate a bit?

uh, nothing. Forget it.

> All current users of ycmd are editor plugins which bundle it together (YCM, emacs-ycmd, the Atom client etc) and distribute it through whatever mechanism the editor uses for plugins.

Well, [emacs-ycmd](https://github.com/abingham/emacs-ycmd#quickstart) assumes you have ycmd installed in your system :-/

**Comment by micbou** [comment]
> Is possible to package ycmd for a GNU/Linux distribution?

Yes, see this [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vim-youcompleteme-git).
