### ISSUE TITLE
OS X El Capitan (Xcode 7.1): Cannot find system includes

### ISSUE THREAD

**Issue by puremourning** [Valloric/ycmd#254]
Problem
====
By default, `ycmd` no longer includes all system headers on OS X when using OS X El Capitan (10.11.1) and Xcode 7.1. Possibly, just Xcode 7.1 is enough.

Detail
====
`ycmd` has special case handling for the system paths on OS X which are used by `clang` but not by `libclang`.

Under Xcode 7.1, the system paths appear to have changed, and standard headers (such as `unistd.h` cannot be found). Unfortunately it does not seem trivial to know the canonical set of paths to use.

Currently `ycmd` adds the following paths in `ycmd/completers/cpp/flags.py`:

```
MAC_INCLUDE_PATHS = [
 '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1',
 '/usr/local/include',
 '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include',
 '/usr/include',
 '/System/Library/Frameworks',
 '/Library/Frameworks',
]
```

On my mac with Xcode 7.1, editing ycmd source reports the following error:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__config|23 col 10 error| 'unistd.h' file not found
```

The command from YCM's README.md gives the following output on Xcode 7.1/OS X El Capitan:

```
BeniMac:ycm ben$ echo | clang -v -E -x c++ - 
<snip>
#include "..." search starts here:
#include <...> search starts here:
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks (framework directory)
End of search list.
</snip>
```

Annoyingly the new paths include the OS SDK version, e.g. `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/*MacOSX10.11.sdk*/usr/include`

I've confirmed adding the above to the paths solves the issue, but it is likely to break again in the next release of OS X and/or Xcode.

Possible Resolutions
====

Open to ideas. 

I keep thinking that using @vheon's code which actually just parses the result of `echo | clang -v -E -x c++ -` might well be the right approach going forward, but it does rely on `clang` being installed and available (where that isn't strictly a requirement now). I have used this myself successfully in the past (in my own `.ycm_extra_conf.py` files).

Alternatively, there must be a way of discovering the INCLUDE path on OS X. It would seem bonkers if there wasn't.

**Comment by vheon** [comment]
@puremourning even if we cannot rely on `clang` being install, we can actually rely on a compiler being installed which by today standards is either `clang` or `gcc` on which the statement `echo | gcc -v -E -x c++ -` should work the same way.

**Comment by puremourning** [comment]
True, but I would still be surprised if the correct `--sysroot` (or at least any working value) to pass to the compiler wasn't available in some place or via some standard mechanism on the OS. I understand Apple's problem with the different platforms, but it is somewhat annoying of them to no longer have a `/usr/include`. It's also annoying of `libclang` to not find the system paths automatically. Headscratcher.

For now, I'm thinking of just PRing adding the one path that makes it work (on my system) while we consider more scalable alternatives.

It would appear that my 10.11 VM does have a `/usr/include` which explains why it worked when i tested it a while back (when it went gold master). I'm updating Xcode command line tools on the VM to see if it ends up the same. Otherwise the workaround might be (regrettably) to install the command line tools, rather than just using the ones that come with Xcode. This has caused serious problems for me in the past though.

**Comment by Valloric** [comment]
Agreed, this is massively annoying. I don't know of a better way of doing it except hard-coding the include paths; note that clang itself actually does this. All the include paths are hard-coded in their C++ code and are picked by examining the system.

> we can actually rely on a compiler being installed

I'm not sure we can. I don't think OS X ships with either gcc or clang in the base install; I think one needs to install Xcode.

Adding include paths for folders that don't exist on the user's system does no harm, so while adding an include or two for El Capitan is hacky, it just might be the simplest solution.

**Comment by puremourning** [comment]
> I don't think OS X ships with either gcc or clang in the base install; 

You're right it doesn't. And while we require a compiler to build, we don't require a compiler to run, so you can (like I do at work) build the `ycm_*.so` on one system and make that build available anywhere. So in theory at least we can't assume there will be a compiler installed on the machine running `ycmd`. 

>I think one needs to install Xcode.

You have to either install Xcode or install the "command line developer tools" for which there's a magic prompt the first time you try to use one. `clang`/`gcc`/etc. commands on OS X are actually shims whose real location is controlled by `xcode-select`. `xcode-select --install` is the simplest way to install the command line tools.

Anyway, I'm thinking this is not entirely a new issue, or at least, my initial thoughts weren't spot on. I just cloned a new VM from my original snapshot of OS X Yosemite prior to installing Xcode or the command line tools. There is no `/usr/include`. I know that on my other VMs I have installed the command line developer tools which (apparently) add the `/usr/include`. I'm going to install Xcode alone on Yosemite and see what the status is.

Just adding the additional directory is still probably the simplest fix for us, but I'm hard-wired to understand a problem before fixing/hacking it :)

**Comment by puremourning** [comment]
Yep. After installing Xcode 7.1 on Yosemite, there is no `/usr/include` and the include paths are as above.

If you then install the command line developer tools via `xcode-select --install`, then `/usr/include` appears and so changes the include paths from `echo | clang -v -E -x c++ -`.

So certainly the workaround is to install the command line tools via `xcode-select --install`. This is a slightly unsatisfying solution though. I still might close it however, as the workaround seems sane enough.

**Comment by puremourning** [comment]
Closing this because installing using the above workaround is basically the simplest, most portable solution.
