### ISSUE TITLE
Use MSVC version of the Rust compiler on AppVeyor

### ISSUE THREAD

**Issue by micbou** [Valloric/ycmd#293]
In PR #268, we use the gnu version of the Rust compiler on AppVeyor because the [MSVC version does not support the new windows 10 SDK](https://github.com/rust-lang/rust/issues/30229). [This is fixed in the development branch of Rust](https://github.com/rust-lang/rust/pull/30233) but it will take some time to land in the stable version. According to [Rust release process](https://doc.rust-lang.org/book/release-channels.html), the fix should be available in the 1.7 version (in about two months).

Meanwhile, we cannot apply [the vcvars workaround](https://github.com/jmquigs/rsnotify/commit/696d2d4a82da2a1aec7fffede9c21763b1c4f52a) because it sets the Omnisharp build configuration to 64-bit release mode, resulting in a failed build.

Our plan is to use the gnu version on AppVeyor until the stable release contains the fix. We will then replace it with the MSVC version.

**Comment by Valloric** [comment]
Thanks for filing this!
