### ISSUE TITLE
Why do objective-c completion candidates have a trailing : in insertion text

### ISSUE THREAD

**Issue by ptrv** [Valloric/ycmd#294]
I noticed that objective-c completion candidates have a trailing `:` at the end of `incertion_text`. Is this by intention? Despite I am not a objective-c programmer I know the syntax of functions in objc and that the last part/word of the function name is often/always? the name of the first argument.

I stumbled upon this while working on adding some extended objective-c support to `company-ycmd` for Emacs (https://github.com/abingham/emacs-ycmd/pull/249) and I am wondering if the client should handle to remove this or the server.

**Comment by Valloric** [comment]
AFAIK we don't add it ourselves, it comes from libclang that way. I too know nothing about Objective C so can't really comment on does that make sense or not. I'll say that while we've had issue reports from Objective C users about various things (most notably complex semantic triggers which we implemented with regex triggers), I've never heard an Objective C user complain about the trailing `:`.

**Comment by ptrv** [comment]
I see, then I guess we will handle the issue on the client side in `emacs-ycmd`. Thanks.

**Comment by puremourning** [comment]
@ptrv could you give an example? Obj C calls are of the form:

```objc
[whatsit doAction: action toThing: thing withX: x Y: y]
```

Libclang returns all of those bits with `doAction:` as typed text. Iirc we made a change to return it to prevent users having to type it. 

Certainly, `action` should not have trailing `:` but `doAction:‘ should. 

If you have an example, eg dump of the json I can take a look.

**Comment by ptrv** [comment]
I understand the rationale behind it.

But isn't the colon already part of the function parameters and therefore shouldn't be included in the `insertion_text` field?

Wouldn't it be the same in c++ if the first opening parenthesis would be part of `insertion_text`. Which of course would not be desired.

I think this is just a matter of perspective.
