### ISSUE TITLE
Rust completion doesn't work when completion trigger encountered on the new line

### ISSUE THREAD

**Issue by yazevnul** [Valloric/ycmd#301]
I was going through Rust Book ([Guessing Game example](https://doc.rust-lang.org/stable/book/guessing-game.html)), when encountered this problem. Here, I made a screencast https://asciinema.org/a/3ih4eakk757n0tsf23344ehsc?theme=solarized-dark

**Comment by vheon** [comment]
Yes, is a known issue and I believe @oblitum want to fix this in the near future, but I don't know how "near" it is. We will keep this open to track it. Thanks for the report :+1:

**Comment by micbou** [comment]
No, this is an issue specific to the Rust completer. It does not happen in C-family languages. See this screencast (sorry for the ugly interface, i am using a minimal vimrc):

![ycmd-newline-completion](https://cloud.githubusercontent.com/assets/10026824/12216291/aee281b8-b6dc-11e5-9fbb-a9b273a1ad80.gif)

I think this is an issue with `racerd`.

**Comment by vheon** [comment]
Oh, sorry. I remember though that @oblitum was talking about something like this in https://github.com/Valloric/YouCompleteMe/pull/1300 but apparently I'm wrong.

**Comment by micbou** [comment]
I confirm that `racerd` response is None when completing on multiple lines. Ping @jwilm.

**Comment by jwilm** [comment]
This appear to be an issue with racer not supporting completions on different line. I [wrote a failing test](https://github.com/phildawes/racer/compare/master...jwilm:completion-on-another-line) for racer that _i think_ fails for the right reason. It's strange that racerd isn't returning a 500 in this case; the racer test panics during `complete_from_file`.

**Comment by yazevnul** [comment]
So, should we close this issue and open a new one for racer? It's really uncomfortable to write everything in one line.

**Comment by puremourning** [comment]
@vheon IIRC the issue with multi-line is where the trigger is on the previous line, like

```c++
Class myclass;
myclass.
   meth<ctrl-space>
```

In my tests we don't get suggestions there, though it is strictly legal code. 

I'm not worried, because it is a fairly strange convention that way round :)

**Comment by micbou** [comment]
@puremourning Are you sure? It works for me.

**Comment by puremourning** [comment]
Hmmmm. Lemme retry

**Comment by puremourning** [comment]
Hmm yes ok works for small file for me (e.g. the ycmd testcase `basic.cpp`).

Explanation for my case: I have a problem with libclang performance and timeouts due to large codebase and SAN, which prevents this working ideally because it seems to always drop back to the identifier completer (due to not finding a semantic trigger before the cursor - it's on the previous line).

**Comment by Valloric** [comment]
@yazevnul Let's keep this open here as well since ycmd users are impacted.

**Comment by micbou** [comment]
Fixed by PR #699.
