### ISSUE TITLE
Add /Library/Developer/CommandLineTools/... to MAC_INCLUDE_PATHS

### ISSUE THREAD

**Issue by richardtsai** [Valloric/ycmd#304]
[`MAC_INCLUDE_PATHS`](https://github.com/Valloric/ycmd/blob/master/ycmd/completers/cpp/flags.py#L45) contains some standard header search paths for mac, but if there's only CommandLineTools but not xcode, there would be no `/Applications/Xcode.app/...`, and the headers files should be in `/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1`. Would it be better to include this path in `MAC_INCLUDE_PATHS`?

**Comment by puremourning** [comment]
I suppose one concern would be that in cases like everyone else where we have both command line and Xcode installed, then there are 2 copies of the standard library in the include path. Not sure if that would have an adverse impact...

Otherwise, have you tried adding it? Does it work for you?

**Comment by richardtsai** [comment]
Yes. After adding this path to `MAC_INCLUDE_PATHS` my header files completion works well without the `isystem` stuff in `ycm_extra_conf.py`. I haven't tested it with Xcode installed but I think libclang will just pick the first one if multiple matches are found.
