### ISSUE TITLE
Implement GoTo for Go

### ISSUE THREAD

**Issue by Manishearth** [Valloric/ycmd#333]
Backstory: After I had just fixed up the Sublime plugin to work with Rust, it turned out that I would be reading a lot of Go code for a while and I didn't actually had a chance to play with YCM for Rust much even though I usually program in it. The universe is cruel :unamused: 

I miss GoTo a lot in Go (doubly so than Rust since the docs are less usable for me), and while I tried fixing up gocode to have GoTo, there are some core issues with its design which make this hard.

Anyway, someone pointed me to https://github.com/rogpeppe/godef, which I'd like to integrate. At first glance it seems easy; but that's what they always say :laughing: 

I plan (at least for now) to do the work here; just opening this issue so that I can post notes/ask for help and in case you don't actually want this integration :smile: 

Tips welcome!

**Comment by Valloric** [comment]
Hm, having two engines (one for completion, the other for GoTo) for separate parts of a language's semantic support would be a first for us. 

@micbou @puremourning @vheon @ekfriis Thoughts?

**Comment by Manishearth** [comment]
Yeah, that's one issue I expected.

Note that godef is a simple binary, without a server. (Gocode is also a simple binary, but it internally does cool stuff with spinning up a server and using unix sockets or something to communicate). Nor does godef _need_ a server, since GoTo perf isn't that important as long as it's within a few hundred milliseconds (unlike autocomplete which should be buttery smooth).

IMO it should be fine to call a different standalone binary for goto.

Also, godef seems to mostly let the Go AST/parse libraries do the heavy lifting, though it contains a copy of them for some reason (backcompat probably)

**Comment by Valloric** [comment]
The only issue is that our build system becomes more complicated; we bundle and build _everything_ for the user. This being Go, it shouldn't be much of an issue.

If godef is this simple, why not simply use it as a library from within gocode? I'm guessing upstream wouldn't be too happy about that idea, but might be worth asking.

**Comment by Valloric** [comment]
Forgot to mention: I'm personally OK with this idea. I'm not a _fan_ of it, but I can see how it would make users happy for not too much hackery. I would like to see how intrusive it would be code-wise though. (I don't expect this to be an issue.)

Other ycmd devs might have different insights.

**Comment by vheon** [comment]
The golang community follow the UNIX philosophy, so every functionality that you might want is actually a separate executable. For this reason I find this

> If godef is this simple, why not simply use it as a library from within gocode? I'm guessing upstream wouldn't be too happy about that idea, but might be worth asking.

to be unlikely accepted upstream. The downside that I see are:

- a "IDE like system" would reuse the AST for the code if it could.
- on our side we wouldn't spawn a new process every time we want a GoTo

On the other hand I don't see this as a drama as it would be for other languages:

- The Go language was designed to be easy to parse and to compile (removing also circular imports), so creating the AST for the source code is really fast.
- Being statically compiled we don't pay for the time of runtime linking which means that spawning a go tool is actually fast.

So I would say that it would be absolutely ok to integrate a different tool for different functionality.

P.S: I know that is not a good excuse but every other system supporting Go as a language would do exactly what we would do here.

**Comment by Manishearth** [comment]
Needs: https://github.com/rogpeppe/godef/pull/24
