### ISSUE TITLE
Refactor tests to reuse semantic servers

### ISSUE THREAD

**Issue by Valloric** [Valloric/ycmd#338]
We currently bring up a new instance of omnisharp, gocode, racerd etc for every single test that needs them. It makes tests take _forever_, especially the omnisharp tests. 

We need to figure out a way to reuse the server instances once they're up without making tests clobber each other. If we only manage to get C# tests to reuse omnisharp, I'll call that a win.

@puremourning @micbou @vheon Any takers? :)

**Comment by mispencer** [comment]
I already have [a implementation](https://github.com/Valloric/ycmd/compare/master...mispencer:PersistentOmnisharp) of this, though it's quite out of date at the moment.

**Comment by mispencer** [comment]
https://github.com/Valloric/ycmd/pull/339 implements this for Omnisharp

**Comment by vheon** [comment]
@Valloric apparently @mispencer got here first...
