### ISSUE TITLE
Go completion kicking in even when built without --gocode-completer

### ISSUE THREAD

**Issue by forty8bits** [Valloric/ycmd#354]
Leading on from https://github.com/Valloric/YouCompleteMe/issues/1603#issuecomment-135237881, it seems that ycmd is enabling Go completion even when the `--gocode-completer` flag isn't provided on build; this is because if `gocode` and `godef` aren't found where they would be built given that flag, if they're in `PATH` they'll still be found and used regardless.

This seems like a bug, since I may want to make use of another plugin (vim-go in this case) for providing completion for Go files, while still making use of YCM for other languages.

**Comment by Valloric** [comment]
Have you tried using [this YCM option](https://github.com/Valloric/YouCompleteMe#the-gycm_filetype_specific_completion_to_disable-option)?

Turning semantic completion on/off is a client-level decision (so done in YCM for instance).

**Comment by vheon** [comment]
@Valloric he doesn't want to disable semantic completion for `go` entirely but use the `omnifunc` which is backed by `gocode` as well but `vim-go` add more stuff to it like parameter completion. IMHO we should not allow our implementation to use binary found on the PATH, but only use the one we ship.

**Comment by forty8bits** [comment]
@vheon is right; it seems to me as though `--gocode-completer` should be treated as opt-in, otherwise deferring to `omnifunc` as usual. I don't want to disable YCM completely, I just don't want it enabling features I specifically chose to leave out.

**Comment by Valloric** [comment]
@forty8bits Fair point. :)
