### ISSUE TITLE
Boost 1.6 trait compilation error

### ISSUE THREAD

**Issue by fallenengine** [Valloric/ycmd#360]
https://github.com/libavg/libavg/issues/727
Same error occurs when compiling wihat GCC 5.1 on Windows. 
MSVC 12 throws C1001 when compiled with it when processing another header from trait directory.

**Comment by micbou** [comment]
> Same error occurs when compiling wihat GCC 5.1 on Windows. 

Not supported.

> MSVC 12 throws C1001 when compiled with it when processing another header from trait directory.

It compiles fine on [AppVeyor](https://ci.appveyor.com/project/Valloric/ycmd/build/638).
