### ISSUE TITLE
Ycmd sever timeout 

### ISSUE THREAD

**Issue by zhuzhongshu** [Valloric/ycmd#375]
I can't start the ycmd server after update my ycmd server and emacs-ycmd package. The error message is as follow:

Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 162, in run_module_as_main
"__main_", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in run_code
exec code in run_globals
File "/home/zzs/.emacs.d/ycmd/ycmd/__main_.py", line 22, in
from future import standard_library
ImportError: No module named future

Process ycmd-server exited abnormally with code 1

**Comment by puremourning** [comment]
You need to git submodule update --init --recursive

**Comment by zhuzhongshu** [comment]
I do this but nothing happen......

**Comment by Valloric** [comment]
This is almost certainly a system configuration issue, not a ycmd bug. Closing.
