### ISSUE TITLE
AttributeError: 'module' object has no attribute 'AddNearestThirdPartyFoldersToSysPath'

### ISSUE THREAD

**Issue by sarrow104** [Valloric/ycmd#388]
platform and vim version:
   Ubuntu 14.04
   VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:47)

tonight, I decide update my YCM.

I did it by these command-line:
$ git pull
$ ./install.py --clang-completer  --system-libclang --tern-completer

all gone OK;

But, When I invoke gVIM, I got these messages:

> Messages maintainer: Bram Moolenaar <Bram@vim.org>
> Error detected while processing function youcompleteme#Enable..<SNR>132_SetUpPython:
> line   34:
> Traceback (most recent call last):
> Error detected while processing function youcompleteme#Enable..<SNR>132_SetUpPython:
> line   34:
>   File "<string>", line 10, in <module>
> Error detected while processing function youcompleteme#Enable..<SNR>132_SetUpPython:
> line   34:
> AttributeError: 'module' object has no attribute 'AddNearestThirdPartyFoldersToSysPath'

What is 'AddNearestThirdPartyFoldersToSysPath' ? I cont find its definition!

**Comment by puremourning** [comment]
You need to update the submodules. 

`git submodule update --init --recursive`

**Comment by micbou** [comment]
Your issue should be fixed by following @puremourning comment. Closing.
