### ISSUE TITLE
Investigate whether or not the new 'keep-going' flag would be useful

### ISSUE THREAD

**Issue by puremourning** [Valloric/ycmd#421]
Reference: http://reviews.llvm.org/rL262318

This new flag `CXTranslationUnit_KeepGoing` allows the `libclang` parser to attempt to continue, even after fatal errors:

> Optionally demote fatal errors to non-fatal errors.

> This behavior is enabled when the new CXTranslationUnit_KeepGoing
option is passed to clang_parseTranslationUnit{,2}. It is geared
towards use by IDEs and similar consumers of the clang-c API where
fatal errors may arise when parsing incomplete code mid-edit, or
when include paths are not properly configured yet. In such situations
one still wants to get as much information as possible about a TU.
Previously, the semantic analysis would not instantiate templates
or report additional fatal errors after the first fatal error was
encountered.

It's probably worth taking a look to see if this improves the ycmd feature set.

**Comment by Valloric** [comment]
Oooh, looks fancy.

@d0k @r4nt Thoughts? Seems like something we might want to use, but you guys have the inside scoop.

**Comment by r4nt** [comment]
This patch was by a KDevelop dev, so I do believe it will be useful for YCM in general. It's fairly new though, so I don't know how well it'll turn out in practice.
