### ISSUE TITLE
When using the YCMD api, is it necessary that the files exist on-disk?

### ISSUE THREAD

**Issue by vincentwoo** [Valloric/ycmd#426]
I am trying to integrate remotely with YCMD. According to the docs, the best way to do this is by reading the example client, which is certainly helpful.

However, in my own implementation, I am getting a lot of mysterious effects. One guess I have about why is that I am supplying imaginary filepaths, like so:

```coffee
payload =
    line_num: 1
    column_num: 2
    filepath: '/home/user/notarealfile.py'
    file_data:
      '/home/user/notarealfile.py':
        contents: code
        filetypes: [ 'python' ]
```

In Python/Jedi's case, this seems to work okay for completing identifiers defined within the file itself (sometimes) but offers no completions when you type something like `import date` (looking for datetime).

From the example client, it's not clear whether having the files exist on-disk is necessary for the underlying engines. The API suggests that it's not, but it's a bit strange to me that the API would call for both sending the file path as a top-level request parameter as well as the entire contents of the file as a separate entry.

Any chance we could get a bit of clarity around this part of the API? A general writeup about the API would be great, too! I stumbled for an hour before I realized that sending `ReadyToParse` was a required precursor to asking for code completions.

**Comment by Valloric** [comment]
> The API suggests that it's not, but it's a bit strange to me that the API would call for both sending the file path as a top-level request parameter as well as the entire contents of the file as a separate entry.

The reason why we accept the contents as well is because it's very likely that the caller wants to override the contents of the file on disk in case of unsaved changes in an editor.

But the file should exist on disk. If you get away with it not existing, it's luck.

> A general writeup about the API would be great, too!

We need API docs, yes. Nobody has found the time and the energy to write them. (We welcome PRs. :))

> I stumbled for an hour before I realized that sending ReadyToParse was a required precursor to asking for code completions.

Ha, it's actually worse that that because it's likely that only _some_ semantic engines require it.

**Comment by vincentwoo** [comment]
Thanks for the response, @Valloric!

If the contents in the API call supersede the contents of the file, is it sufficient to simply have a blank file at the given location, or would it be better to write out the file to disk everytime as we make the API call, "just to be safe"?

Do you know offhand which semantic engines require `ReadyToParse` or if there would at least ever be a reason to *not* send it? Are there any other pitfalls someone trying to make an "autocomplete as an API service" should watch out for?

**Comment by Valloric** [comment]
Off the top of my head, I don't know the answers to these questions. You're going to have to take a look at the code.

In general, the filepaths provided should exist as files on disk.
