### ISSUE TITLE
Question regarding Boost.Python and Python 3

### ISSUE THREAD

**Issue by bchretien** [Valloric/ycmd#435]
After seeing that [Python 3 support](https://github.com/Valloric/YouCompleteMe/pull/2016) was recently added, I tried to install/run YCM with Python 3 on Arch Linux:

```sh
$ python3 ./install.py --clang-completer --system-libclang --system-boost
```

The only issue I encountered was in ycmd's [cpp/ycm/CMakeLists.txt](https://github.com/Valloric/ycmd/blob/master/cpp/ycm/CMakeLists.txt#L196):

```cmake
find_package( Boost REQUIRED COMPONENTS python filesystem system regex thread )
```

Because of this, `ycm_core.so` is linked to `libboost_python.so`, which is the Python 2 library. As a result, some symbols were missing at runtime:

```sh
ImportError: /usr/lib/libboost_python.so.1.60.0: undefined symbol: PyClass_Type 
```

If I change this line to:

```cmake
set( BOOST_COMPONENTS filesystem system regex thread )
if( USE_PYTHON2 )
  list( APPEND BOOST_COMPONENTS python)
else()
  list( APPEND BOOST_COMPONENTS python3)
endif()
find_package( Boost REQUIRED COMPONENTS ${BOOST_COMPONENTS} )
```

`ycm_core.so` is properly linked to `libboost_python3.so` on Arch, and YCM runs normally. However, it seems that naming conventions differ between Linux distributions, for instance [on Debian Sid](https://packages.debian.org/sid/amd64/libboost-python1.58-dev/filelist):

> /usr/lib/x86_64-linux-gnu/libboost_python-py27.so
> /usr/lib/x86_64-linux-gnu/libboost_python-py34.so
> /usr/lib/x86_64-linux-gnu/libboost_python-py35.so
> /usr/lib/x86_64-linux-gnu/libboost_python.so

While [on Arch Linux](https://www.archlinux.org/packages/extra/i686/boost-libs/):

> /usr/lib/libboost_python.so
> /usr/lib/libboost_python.so.1.60.0
> /usr/lib/libboost_python3.so
> /usr/lib/libboost_python3.so.1.60.0

Thus we may need a slightly more complex solution if we want it to work for any OS/distribution.

Note: tested with ycm's current master (https://github.com/Valloric/YouCompleteMe/commit/f44435b88ec98156d17869aa67ad15f38cfecbf3), and I patched the associated ycmd head (6df0fe50cacb8887eda0785b845e8dc049ca0408), since apparently the related CMake line has not been changed since anyway.

**Comment by micbou** [comment]
You should use the [`Boost_PYTHON_LIBRARY_RELEASE` flag](https://github.com/Kitware/CMake/blob/master/Modules/FindBoost.cmake#L55). In your case, you could do:
```sh
EXTRA_CMAKE_ARGS="-DBoost_PYTHON_LIBRARY_RELEASE=/usr/lib/libboost_python3.so" python3 ./install.py --system-boost
```
to use the Python 3 component.

**Comment by bchretien** [comment]
@micbou thanks! I guess this will need to appear in YCM's doc then.

**Comment by puremourning** [comment]
Actually I believe this is a cmake option, and googlers should find this issue or cmake docs. We can't document every workaround for every not-officially-supported distro, sorry :/

**Comment by micbou** [comment]
It is rather that we don't support the `--system-boost` option.
