### ISSUE TITLE
RuntimeError: Gocode returned empty JSON response.

### ISSUE THREAD

**Issue by elithrar** [Valloric/ycmd#444]
Ref: https://github.com/nsf/gocode/issues/340

- Running gocode @ 61468c3 (latest as of this post)
- YouCompleteMe @ 429e04a (latest as of this post)
- vim-go @ fc682ce (latest)
- neovim stable 0.1.2 (latest)

ycmd is returning a `RuntimeError: Gocode returned empty JSON response.` when hitting [here](https://github.com/Valloric/ycmd/blob/6df0fe50cacb8887eda0785b845e8dc049ca0408/ycmd/completers/go/go_completer.py#L125-L128):

```go
    try:
      resultdata = json.loads( ToUnicode( stdoutdata ) )
    except ValueError:
      _logger.error( PARSE_ERROR_MESSAGE )
      raise RuntimeError( PARSE_ERROR_MESSAGE )
```

`json.loads` appears to raise an exception on 'some' responses from gocode, but debugging further is challenging as there is not currently a way to capture the data. 

The error is frustrating as it will occur for an identifier that was previously autocompleted. A restart of neovim resolves it temporarily, and it occasionally resolves itself (making it even harder to debug).

This happens across 3x machines running the same [vimrc](https://github.com/elithrar/dotfiles/blob/master/vimrc).

**Comment by vheon** [comment]
Please don't remove the issue template, just fill it out. We need a minimal reproducible test case.

> neovim stable 0.1.2 (latest)

We don't support neovim but just regular vim. It probably won't change much here, but just in case retry with vanilla vim.

**Comment by elithrar** [comment]
Sorry, there was no auto-populated (aka new GitHub feature) template in the textarea.

Here's the re-production (noting that is is extremely temperamental: if this failed 100% of the time, it'd be easier to fix):

1. Open a .go file on your $GOPATH - package does not matter.
2. Write code - e.g. `testClient := &http.Client{}` (this autocompletes)
3. Write more code - `testClient.httpClient.` - fails here with `RuntimeError: Gocode returned empty JSON response` when attempting to show autocompletion results (*this is the part that fails unreliably, but once it fails it stays failed for some amount of time*)
4. Restart neovim, or write some more code (which will continue to fail), and eventually it recovers (until it fails again).

Note that this is probably the worst bug report I've ever written because the issue cannot be replicated reliably. At best I can show you a gif screencap.

**Comment by puremourning** [comment]
> Sorry, there was no auto-populated (aka new GitHub feature) template in the texture

Yep, not in this repo - most issue reports are made against the YouCompleteMe repo :)

https://github.com/Valloric/YouCompleteMe/blob/master/CONTRIBUTING.md

**Comment by elithrar** [comment]
Got it!

Log output (triggered the error during this):

```
561 2016-03-26 12:19:16,295 - DEBUG - Event name: InsertLeave
562 2016-03-26 12:19:16,669 - INFO - Received event notification
563 2016-03-26 12:19:16,670 - DEBUG - Event name: FileReadyToParse
564 2016-03-26 12:19:16,670 - INFO - Adding buffer identifiers for file: /Users/matt/.go/src/github.com/jamesog/cloudflare-go/cloudflare_test.go
565 2016-03-26 12:19:22,271 - INFO - Received event notification
566 2016-03-26 12:19:22,272 - DEBUG - Event name: BufferVisit
```

Debug info:
```
-- Server has Clang support compiled in: False
--
-- Server running at: http://127.0.0.1:61269
-- Server process ID: 12303
-- Server logfiles:
--   /var/folders/3k/30m3dj_57dv9c2n4b3z6cbxm0000gn/T/ycm_temp/server_61269_stdout.log
--   /var/folders/3k/30m3dj_57dv9c2n4b3z6cbxm0000gn/T/ycm_temp/server_61269_stderr.log
```

Replicate with (any Go package, but here's a simple one):

```go
package main

import (
	"log"
	"net/http"
)

func main() {
	http.HandleFunc("/", Handler)
	log.Fatal(http.ListenAndServe("localhost:8000", nil))
}

func Handler(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("hello\n"))
}
```

**Comment by puremourning** [comment]
Strange. Firstly, I can't repro, and secondly, there is no error or backtrace in the log file.

In the code you posted, we print the exception to the log:
```python
    except ValueError:
      _logger.error( PARSE_ERROR_MESSAGE )
```

So should it have happened in ycmd, then we would see it.

Could you maybe try disabling vim-go and see if the problem goes away? If not, could you do a gif like you suggested so that we can see it happening.

One thing you could do is edit `ycmd/conmpleters/go/go_completer.py` (the code you pasted), to output some useful debug:

```python
    try:
      resultdata = json.loads( ToUnicode( stdoutdata ) )
    except ValueError:
      _logger.error( PARSE_ERROR_MESSAGE )
      _logger.debug( 'The failed response was: ' + ToUnicode( stdoutdata ) )
      raise RuntimeError( PARSE_ERROR_MESSAGE )
```

I understand it is frustrating when it is intermittent, and when it isn't clear which product is to blame for an issue, so thank you for your patience.

**Comment by puremourning** [comment]
wait. CorrectIon to all of the above, the returned message is not `PARSE_ERROR_MESSAGE` it is `NO_COMPLETIONS_MESSAGE`. which is the following code:

```
    if len( resultdata ) != 2:
      _logger.error( NO_COMPLETIONS_MESSAGE )
      raise RuntimeError( NO_COMPLETIONS_MESSAGE )
```

Which is nothing to do with `json`.

All the rest still applies, and it looks to me like it is a `gocode` issue. They aren't returning any completions.

Also. I *can* now reproduce it, after leaving Vim running for a while. Stranger still.

**Comment by elithrar** [comment]
OK, that makes more sense. What is ycmd expecting in the event of gocode finding no completions? gocode should return something that makes sense (which I'll look into), and ycmd should be able to provide a friendly "no completion" notification rather than the current error.

**Comment by puremourning** [comment]
Where do you see the error? I don't see it in the client, I only see it in the ycmd log file.

**Comment by puremourning** [comment]
In answer to the question, gocode is returning and empty list 

```
2016-03-26 22:51:29,483 - DEBUG - resultdata was length: 0 and contents: []
```

**Comment by elithrar** [comment]
![screen shot 2016-03-26 at 3 55 36 pm](https://cloud.githubusercontent.com/assets/18544/14062841/34163436-f36b-11e5-87e8-e9f3dadd5938.png)

Doing some digging: in some cases this message appears to be valid - i.e. there are no completions for a certain symbol, but it manifests as an error message.

**Comment by puremourning** [comment]
OK well, I think what we're sending to gocode is legit and it is just returning nothing:

```
2016-03-26 22:57:49,555 - DEBUG - gocode_debug: Execute: [u'/Users/lindsayjackson/.vim/bundle/YouCompleteMe-Clean/third_party/ycmd/ycmd/completers/go/../../../third_party/gocode/gocode', u'-f=json', u'autocomplete', u'/Users/lindsayjackson/ben/test/repro.go', '118']
2016-03-26 22:57:49,558 - DEBUG - gocode_debug: Contents: b'package main\n\nimport (\n    "log"\n    "net/http"\n)\n\nfunc main() {\n    http.HandleFunc("/", Handler)\n    http.\n    http.\n    log.Fatal(http.ListenAndServe("localhost:8000", nil))\n}\n\nfunc Handler(w http.ResponseWriter, r *http.Request) {\n    w.Write([]byte("hello\\n"))\n}\n'
2016-03-26 22:57:49,566 - DEBUG - gocode_debug: Response stdout: '[]'
2016-03-26 22:57:49,567 - DEBUG - gocode_debug: Response stderr: ''
2016-03-26 22:57:49,567 - DEBUG - resultdata was length: 0 and contents: []
2016-03-26 22:57:49,567 - ERROR - Gocode returned empty JSON response.
```

**Comment by micbou** [comment]
We should change the message `Gocode returned empty JSON response` to something like `No completions returned by Gocode`.

**Comment by puremourning** [comment]
Agreed. Though I'm still baffled why the user is seeing it... `GetCompletions` should eat the exception.

@elithrar are you using `<Ctrl-Space>` to trigger the completion when you see the error?

**Comment by puremourning** [comment]
Also, I can only reproduce the exception (in the log file) when the code is invalid.

**Comment by elithrar** [comment]
I see the error before triggering the completion - e.g. type the symbol, YCM returns the error in the status bar instead of showing the completions list.

**Comment by puremourning** [comment]
Oh I get it. You have `:set noshowmode`. Sorry - brain fart on my part.

Minimal test case:

```go
package main
import ( "log" )
func main() {
    log.
    log.
    //  ^
}
```

The exception is raised when `gocode` returns no completions. This happens when typing the `.` next to the caret above. This is displayed via `echo` in Vim.

The main problem is that the text isn't very good, or that we just shouldn't raise an exception. It's not really an error - `gocode` can't offer suggestions because of the syntax.

**Comment by elithrar** [comment]
OK, that makes a lot more sense to me as well.

https://github.com/Valloric/ycmd/blob/6df0fe50cacb8887eda0785b845e8dc049ca0408/ycmd/completers/go/go_completer.py#L130-L132 should then change to return "gocode returned no completions for the current context" (i.e. be specific) and trade the `RuntimeError` for something more appropriate. 

(There was likely some confusion on my part as the RuntimeError in the status bar persists until something clears it, which makes it look more 'permanent' than it is)

**Comment by micbou** [comment]
The error message was changed by PR #505. It should be clearer now.

Concerning the `RuntimeError`, it is fine to raise this kind of exception. If you want it to be removed from the error message, feel free to [open an issue in YCM repository](https://github.com/Valloric/YouCompleteMe/issues) so that we can discuss it.
