### ISSUE TITLE
Error while editing xml file

### ISSUE THREAD

**Issue by icholy** [Valloric/ycmd#461]
I'm occasionally getting this weird error. It doesn't make sense to me, because the filetype is `xml`, so YouCompleteMe shouldn't even be kicking in right? I'm using neovim, but I get the same thing with regular vim. I checked the logs, but there was nothing in there.

![](http://i.imgur.com/ntVglED.gif)

![](http://i.imgur.com/YoZR62A.png)

**Comment by vheon** [comment]
I think it happens because the file is greater than 1Mb which is the limit of the request bottle can handle. Is strange though because YCM should have detected that the file is greater than what we can handle and disable YCM for that buffer :confused:

**Comment by vheon** [comment]
How big is the file?

**Comment by icholy** [comment]
Almost a MB (980K). How can I debug this?

**Comment by icholy** [comment]
I guess I'll start looking here https://github.com/Valloric/YouCompleteMe/blob/7f419101feb01f32bc1595798291e9cd5143948b/autoload/youcompleteme.vim#L421

**Comment by icholy** [comment]
The threshold is 1024000 and the filesize is 1001429. Lowering the `g:ycm_disable_for_files_larger_than_kb` value works fine.

A strange thing happened. When I initially looked at the filesize, it was 960K. Then, when I opened it in gedit and saved it from there (no modifications). The filesize jumped to 1016K.

**Comment by icholy** [comment]
Ok, so gedit saved the files with windows style line endings.

**Comment by icholy** [comment]
I'm thinking it might have something to do with it using those `\n` when creating the contents

https://github.com/Valloric/YouCompleteMe/blob/7f419101feb01f32bc1595798291e9cd5143948b/python/ycm/vimsupport.py#L126

**Comment by icholy** [comment]
Eh, lowering `g:ycm_disable_for_files_larger_than_kb` did the trick. Good enough.
