### ISSUE TITLE
README doesn't specify all dependencies

### ISSUE THREAD

**Issue by pscollins** [Valloric/ycmd#464]
The readme says on Ubuntu I just need `build-essential`, `cmake`, and `python-dev`, but running `./build.py --all` errors out with:

> msbuild or xbuild is required to build Omnisharp

It would be clearer if either one of those was listed as a dependency to grab from `apt-get`, or the list of possible YCM completers was repeated here with a note that different targets have different dependencies.

**Comment by puremourning** [comment]
> For more detailed instructions on building ycmd, see YCM's instructions (ignore the Vim-specific parts).

From that README: 

> To simply compile with everything enabled, there's a --all flag. So, to install with all language features, ensure npm, go, mono, rust, and typescript API are installed and in your PATH, then simply run:

> cd ~/.vim/bundle/YouCompleteMe
./install.py --all

Along with links and instructions. I'm not sure how much clearer we could make it without repeating everything in ycmd and YCM repos.
