### ISSUE TITLE
MSYS2-x64 build

### ISSUE THREAD

**Issue by danielmario** [Valloric/ycmd#469]
Hello,
I use YCM on Linux and Windows, but it does not build on MSYS2-x64 because of missing/incorrect definitions.
The following patch applies to ycmd and make "python2 install.py" work.
https://gist.github.com/danielmario/639a487949837422485740dbacf09509

**Comment by vheon** [comment]
What you're proposing is to patch a boost file which is not under our direct control, we merely include some boost library in this project. What you should do is to propose this patch upstream to the boost dev team and one is merged we will just update the boost version. I believe there were other issues about it in the past so I don't know if some other user already tried to propose a similar change upstream. For this reason and for the fact that we don't officially support MSYS2 (but only MSVC) I'm going to close this.
