### ISSUE TITLE
post install changes required for anaconda distribution.

### ISSUE THREAD

**Issue by dalejung** [Valloric/ycmd#485]
Just a heads up. After https://github.com/Valloric/ycmd/pull/481, all anaconda pythons need to work is to change the linked path like:

```
install_name_tool -change libpython3.5m.dylib /Users/datacaliber/miniconda3/lib/libpython3.5m.dylib ycm_core.so
```

https://github.com/ContinuumIO/anaconda-issues/issues/498 is the related upstream anaconda issue.

Can this be put into ycmd build script? If not, I can PR a note on the YouCompleteMe FAQ to show how to get conda envs to work.

**Comment by puremourning** [comment]
I'm sorry we do not support anaconda. Only stock python is supported.

Believe me, it is hard enough supporting all the installations of stock Python, let alone any other Python flavours.

**Comment by dalejung** [comment]
Yeah no worries. It was a PITA to figure out how to get conda to work. Either way, I think once conda fixes their upstrream, the new build stuff should work anyways.

**Comment by puremourning** [comment]
That would be neat. Thanks for the note. Closed 'cos it's not a bug and not something we're going to officially support. Hopefully this will help someone via google or whatever ! :)
