### ISSUE TITLE
Not compatible with virtualenv.

### ISSUE THREAD

**Issue by Cissoid** [Valloric/ycmd#486]
I use a Mac machine and created a python virtual environment use virtualenv on `~/pyvenv`, so the  `sys.exec_prefix` is `'~/pyvenv/bin/..'`

When I run install.py in virtualenv, the `FindPythonLibrariesOnMac()` function expect to find the python library  `~/pyvenv/lib/libpython2.7.dylib`, it seems that virtualenv not made the symlink, so the script  report "unable to find an appropriate Python library", and I have to manual add this link.

Prior version of ycmd could find correct path of python library, so keep the original behaviour when FindPythonLibraries* functions find nothing may be a better choice for backward compatibility.

**Comment by micbou** [comment]
Thanks for the report. Could you try PR #488 and tell us if it works for you? It would be greatly appreciated.

**Comment by Cissoid** [comment]
@micbou It works well now, thanks for your work!

Here is my building log output:

```
$ ./install.py
Searching Python 2.7 libraries...
Found Python library: /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib
Found Python headers folder: /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7
......

-- Found PythonLibs: /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib (found suitable version "2.7.11", minimum required is "2.6")
NOT using libclang, no semantic completion for C/C++/ObjC will be available
-- Found PythonInterp: /Users/Cissoid/pyvenv/bin/python2.7 (found version "2.7.11")
......
```
