### ISSUE TITLE
Why do I need a .ycm_extra_conf.py?

### ISSUE THREAD

**Issue by mprobst** [Valloric/ycmd#489]
I just set up YCM with both VIM and Sublime Text. It works, hurray!

That being said, I'm a bit mystified by the setup process. I copied some `.ycm_extra_conf.py` file from somewhere, removed some code I don't understand, added some code I don't understand, but overall the entire file looks completely plain vanilla to me. There is nothing in it that would be specific to my setup, machine, or projects.

Couldn't this just work out of the box, assuming I have a `compile_commands.json` file?

**Comment by Valloric** [comment]
Please refer to [the relevant section in the README](https://github.com/Valloric/YouCompleteMe#c-family-semantic-completion) that explains why you need it if writing C/C++/ObjC code.

Short story: _every_ project has custom compilation flags and you need to provide them to YCM so that it can compile your code.

**Comment by mprobst** [comment]
I'm using Clang's compile database format. Would it make sense to look for that by default? Getting that python file (a language I'm not comfortable with) into the right place was a substantial hurdle for adoption for me.

Having something that works (even just a bit more) out of the box would make using YCM a lot easier.

TypeScript seems to be a good example, where the service just picks up a `tsconfig.json` it finds and does the right thing automatically.

**Comment by puremourning** [comment]
Right, if you wrote a tsconfig.json and put it in the right place. Just as arbitrary IMO

**Comment by mprobst** [comment]
@puremourning YMMV. `tsconfig.json` is a declarative format that's understood by all TS tools, and very succinct. As it stands now, for YCM I need a Python file I don't understand, plus the compile lines from Clang, which seems worse in any case.

**Comment by Valloric** [comment]
@mprobst 

> tsconfig.json is a declarative format that's understood by all TS tools

That's the problem; C and C++ don't have that. For every user using the clang compilation database, there's 1000 more that aren't and they also use YCM. This is the reason why we have _one_ file for all of these users. You can use it to integrate YCM with whatever your build system may be.

**Comment by mprobst** [comment]
@Valloric the flexibility makes sense to me, but I think you could help a lot of users substantially by having some sane defaults, e.g. by probing for a `compile_commands.json` and just doing the right thing (tm) if it exists.

**Comment by puremourning** [comment]
Exists... where?

**Comment by mprobst** [comment]
@puremourning in an ancestor directory of whatever file you're touching.

**Comment by puremourning** [comment]
@mprobst Starting with the example from within ycmd, it took me just a few minutes to write a `.ycm_extra_conf.py` which will find the `compile_commands.json` and use `ycmd` built-in support for parsing the database and extracting the files.

You should be able to put this file anywhere in your system and set `g:ycm_global_ycm_extra_conf` option to point at it, or just put it in the root of your home directory (or whatever maximal parent directory you would normally use). It should find your compile_commands.json and apply the flags.

All I really did was:
 - remove the stuff for manually supplying flags
 - reorganise slightly to make it simpler
 - add some additional commentary to help understand what is going on
 - write it in such a way that it can be used as a global extra conf file.

Hopefully, you'll see why we use this "arbitrary execution" model. It means any use case can easily be accommodated with a small amount of effort. If this doesn't work for you, I hope you'll agree that you could easily modify it to do so.

```python
# This file is NOT licensed under the GPLv3, which is the license for the rest
# of ycmd.
#
# Here's the license text for this file:
#
# This is free and unencumbered software released into the public domain.
#
# Anyone is free to copy, modify, publish, use, compile, sell, or
# distribute this software, either in source code form or as a compiled
# binary, for any purpose, commercial or non-commercial, and by any
# means.
#
# In jurisdictions that recognize copyright laws, the author or authors
# of this software dedicate any and all copyright interest in the
# software to the public domain. We make this dedication for the benefit
# of the public at large and to the detriment of our heirs and
# successors. We intend this dedication to be an overt act of
# relinquishment in perpetuity of all present and future rights to this
# software under copyright law.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# For more information, please refer to <http://unlicense.org/>

import os

from ycmd import utils
import ycm_core

SOURCE_EXTENSIONS = [ '.cpp', '.cxx', '.cc', '.c', '.m', '.mm' ]
HEADER_EXTENSIONS = [ '.h', '.hxx', '.hpp', '.hh' ]

# We cache the database for any given source directory
compilation_database_dir_map = dict()


# Return a compilation database object for the supplied path or None if none
# could be found.
#
# We search up the directory hierarchy, to first see if we have a compilation
# database already for that path, or if a compile_commands.json file exists in
# that directory.
def FindCompilationDatabase( wd ):
  # Find all the ancestor directories of the supplied directory
  for folder in utils.PathsToAllParentFolders( wd ):
    # Did we already cache a datbase for this path?
    if folder in compilation_database_dir_map:
      # Yep. Return that.
      return compilation_database_dir_map[ folder ]

    # Guess not. Let's see if a compile_commands.json file already exists...
    compile_commands = os.path.join( folder, 'compile_commands.json' )
    if os.path.exists( compile_commands ):
      # Yes, it exists. Create a database and cache it in our map.
      database = ycm_core.CompilationDatabase( folder )
      compilation_database_dir_map[ folder ] = database
      return database

    # Doesn't exist. Check the next ancestor

  # Nothing was found. No compilation flags are available.
  return None


# Find the compilation info structure from the supplied database for the
# supplied file. If the source file is a header, try and find an appropriate
# source file and return the compilation_info for that.
def GetCompilationInfoForFile( database, file_name ):

  # The compilation_commands.json file generated by CMake does not have entries
  # for header files. So we do our best by asking the db for flags for a
  # corresponding source file, if any. If one exists, the flags for that file
  # should be good enough.
  if os.path.splitext( file_name )[ 1 ] in HEADER_EXTENSIONS:
    # It's a header file
    basename = os.path.splitext( file_name )[ 0 ]
    for extension in SOURCE_EXTENSIONS:
      replacement_file = basename + extension
      if os.path.exists( replacement_file ):
        # We found a corresponding source file with the same basename. Try and
        # get the flags for that file.
        compilation_info = database.GetCompilationInfoForFile(
          replacement_file )
        if compilation_info.compiler_flags_:
          return compilation_info

    # No corresponding source file was found, so we can't generate any flags for
    # this header file.
    return None

  # It's a source file. Just ask the database for the flags.
  return database.GetCompilationInfoForFile( file_name )


# ycmd calls this method to get the compile flags for a given file. It returns a
# dictionary with 2 keys: 'flags' and 'do_cache', or None if no flags can be
# found.
def FlagsForFile( file_name, **kwargs ):
  # Create or retrieve the cached compilation database object
  database = FindCompilationDatabase( os.path.dirname( file_name ) )
  if database is None:
    return None

  compilation_info = GetCompilationInfoForFile( database, file_name )
  if compilation_info is None:
    return None

  return {
    # We pass the compiler flags from the database unmodified.
    'flags': compilation_info.compiler_flags_,

    # We always want to use ycmd's cache, as this significantly improves
    # performance.
    'do_cache': True
  }
```

**Comment by mprobst** [comment]
@puremourning thanks for the example. I think I've made my point, it's up to the maintainers of YCM if they want to remove this stumbling stone for users.

**Comment by puremourning** [comment]
I don't think we do b
