### ISSUE TITLE
Should forced semantic completion bring cached information?

### ISSUE THREAD

**Issue by oblitum** [Valloric/ycmd#491]
Consider the following

```c++
struct S { int a; };

int main() {
    S s;
    s.<forced semantic completion>
}
```

At `<forced semantic completion>`, `a` is suggested. Now changing the `struct` without introducing new lines, like for example:

```c++
struct S { int b; };

int main() {
    S s;
    s.<forced semantic completion>
}
```

`a` is still suggested. IMO, I think it's better behaviour for forced semantic completion to never rely on cache, because otherwise it defies its purpose. Without an operation to really ask for fresh information in a simply manner, we're left with this option of internal knowledge of the system, to force it by changing code in some crafted manner to bring fresh information. What you think?

**Comment by oblitum** [comment]
Another solution would be to have another kind of "really" forced semantic completion. Soft forced semantic completion and hard forced semantic completion.

**Comment by Valloric** [comment]
> Now changing the struct without introducing new lines, like for example:

I agree that this is an issue, but the example shows how unlikely it is for someone to hit this.

Still, I'm not against having forced semantic completion bust the cache. I would like to hear what others think on this. @puremourning @vheon @micbou

**Comment by mispencer** [comment]
This is the same change as https://github.com/Valloric/ycmd/pull/443#issuecomment-201582280 and I'm opposed to it for the same reason.

My comment there:
> It's common for me to force completions, have it time out, force it again, and get completions from the cache. I just tested this, and with this change, I can't get any completions at all, since it always times out.

**Comment by oblitum** [comment]
Agreed this sample makes the problem seem unlikely, but also, personally, I don't like to rely on unpredictable behavior as the sole option. On a side-note, It's more likely when having hints as implemented in my fork, it has been brought up in my endeavours like with https://github.com/Valloric/YouCompleteMe/issues/2141.

**Comment by puremourning** [comment]
I agree with @mispencer. I often have to force to get cached returns on massive c++ code base on slow SAN storage. IIRC @micbou looked at this recently and decided that typing a single char in the file is enough to flush the cache.

**Comment by oblitum** [comment]
@mispencer thanks for linking that issue, my github fu for some reason missed that one. I indeed realized the issue you mention, but still opened it. I'm not sure what's more widely useful.

**Comment by oblitum** [comment]
@puremourning it may be less trivial than that, for example, deleting many chars without changing line count, doesn't flush.

**Comment by Valloric** [comment]
@mispencer Thanks for reminding me. I had it in the back of my head that we had discussed this at some point, but I couldn't remember the details. It's why I @-mentioned others because I knew one of you would remember. :)

The counterarguments were as convincing then as they are now: we won't be busting the cache on forced semantic completions. Sorry @oblitum.

**Comment by oblitum** [comment]
I've applied this in my fork, even realizing the issue @mispencer refers to, because I think I can live better with the complementary reality. Before I had forced semantic completion that relied on cache, so, at random, I'd have the risk of not getting fresh information, if that would happen for some reason, I'd known from incantation knowledge that I'd just need to type a char. Now I'll always have fresh data, and in the few cases it times-out, I know from incantation knowledge that forcing it again is not the way, but just typing some char after trigger, and deleting it again.

**Comment by oblitum** [comment]
By the way, the it's was also a question about having soft and hard.

**Comment by oblitum** [comment]
I may have realized a best of both worlds solution, which is to immediately return cached data if available but ask still ask for cache renewing in background, since I've checked cache is already thread protected, this should be trivial, if there's any interesting with following on with a pull request ping me.

**Comment by oblitum** [comment]
My final solution I'm adopting: https://github.com/Valloric/ycmd/compare/master...oblitum:forced-semantic-completion-with-background-cache-update

Tries to get fresh data, if not available in a timely fashion, let the cache update in the background while returning previously cached data.

**Comment by oblitum** [comment]
Just to register. This could be improved if completion relied on the `complete_add` API and cache swapping and menu content updates could happen while user types. Also, the mechanism could be relaxed to be used for forced semantic completion on global scope on any location since it brings _almost_ the same data most of the time, which can be a helper to https://github.com/Valloric/YouCompleteMe/issues/777#issuecomment-236626561 and related.

**Comment by micbou** [comment]
The caching behavior has been improved in PR #958. Cache is now invalidated in your example.

**Comment by oblitum** [comment]
@micbou I wonder what would happen with #958's solution if `struct S { int a; };` changed inside a header, while leaving current source contents intact.

**Comment by bstaletic** [comment]
That case still odesn't work.

- I made `a.h` have `struct S { int a; };`.
- Opened `a.cpp` and included the header.
- `a.cpp`
```c++
#include "a.h"
int main() {
    S s;
    s.<cursor>
}
```
- `a` got suggested
- From a different shell `sed -i -e 's/a/b/' a.h` changed the contents of the struct.
- Exit insert mode, re-enter and press `<C-Space>`.
- `a` still suggested.
- Changing `a.cpp` to:
```c++
#include "a.h"
int main() {
    struct S s;
    s.<cursor>
}
```
- `b` finally got suggested.

**Comment by oblitum** [comment]
OK. The solution I've adopted and commented before don't have such issues.

**Comment by micbou** [comment]
The issue with your approach is that if the semantic engine takes more than 400ms to return completions, cached completions will only be returned after 400ms while it is immediate with the current approach. This delay of 400ms will occur for all typed characters within that completion. This results in sluggish filtering of completions when semantic completion is forced and the semantic engine is slow. Also, it doesn't prevent the caching issue in that case since the cache is not invalidated.

**Comment by oblitum** [comment]
> The issue with your approach is that if the semantic engine takes more than 400ms to return completions, cached completions will only be returned after 400ms while it is immediate with the current approach.

Right, I've weighted 400ms as a reasonable timeout to return the old cache in case the new semantic info doesn't arrive in time. Notice though the important part of this is that it's expected that new semantic info will come in <400ms in most cases, and it will indeed cover both cases mentioned in this issue, having a header or not. 

> This delay of 400ms will occur for all typed characters within that completion. This results in sluggish filtering of completions when semantic completion is forced and the semantic engine is slow.

I don't get this. I don't recall it happening before and if I recall correctly, I just do the background cache swap logic solely on the forced semantic completion request. 

> Also, it doesn't prevent the caching issue in that case since the cache is not invalidated.

Why it's not? The cache should be always replaced with fresh info if it arrives before <400ms, and if it times out, it will come fresh on the next forced semantic completion request.

**Comment by oblitum** [comment]
> Why it's not?

Not asking solely because of I explain how this shouldn't be true, I also simply can't reproduce https://github.com/Valloric/ycmd/issues/491#issuecomment-377674932.

**Comment by micbou** [comment]
> I don't get this. I don't recall it happening before and if I recall correctly, I just do the background cache swap logic solely on the forced semantic completion request.

If semantic completion is forced at some position in the file, it's still going to be forced for the next typed characters (until a non-identifier character is typed, e.g. a space). Otherwise, ycmd would fall back to the identifier completer.

> Not asking solely because I explain how this shouldn't be true, I also simply can't reproduce #491 (comment).

You can't reproduce because the semantic completion takes less than 400ms but also because the Clang completer raises an exception if it is still parsing the file so even if it takes more than 400ms to return completions, the background cache thread may immediately end and the old cached completions will be returned. Instead, try to add a sleep of 500ms in the `_ComputeCandidatesUpdatingCache` function (simulating a slow semantic engine), force semantic completion somewhere, and type characters to filter down the suggestions. You'll notice that each time you type a character (or remove one), it takes ~400ms to update the list of suggestions.

**Comment by oblitum** [comment]
If that should happen, I think there can be a fix to the solution to amend this extreme situation, though personally I don't bother as I've never been hit by it and I simply think if semantic completion is to arrive with such delay then it's not usable altogether.

**Comment by oblitum** [comment]
At the time I designed it, the intention was to trigger background caching solely at forced semantic completion request when it's requested at first, not to request the same semantic completion info for each typed char onwards, it'd be stupid behavior, when it happens.
