### ISSUE TITLE
racerd submodule link outdated

### ISSUE THREAD

**Issue by rompetroll** [Valloric/ycmd#492]
In a freshly installed YouCompleteMe, the racerd submodule in ycmd is locked to racer version 1.1.0. The current version is 1.2.9.

This is a problem with the current rust version 1.8.0, where some files have been moved/removed in the codebase. Completion with racer 1.1.0 only works for parts of the rust-1.8.0-codebase. This has been fixed in racer 1.2.6, see https://github.com/phildawes/racer/issues/511

I have completion working on my machine after manually checking out the `master` branch in `Valloric/YouCompleteMe/third_party/ycmd/third_party/racerd` and rebuilding racerd and YouCompleteMe.

**Comment by puremourning** [comment]
Ping @jwilm for comment :)

**Comment by jwilm** [comment]
I've been holding off updating the ref since racerd is currently broken on Windows. I haven't had time lately to set up an environment to test it, but I could try to this afternoon. Sorry about this!

**Comment by Valloric** [comment]
@rompetroll Since racerd was created specifically for YCM, you can rest assured that if we're linking to an older copy, it's because Joe has a damn good reason for it. :)

Closing per @jwilm's comment.
