### ISSUE TITLE
Fails to install on 64-bit fedora core 23

### ISSUE THREAD

**Issue by llogiq** [Valloric/ycmd#502]
The reason is that libpython is under `/usr/lib64/libpython2.7.so` (whereas `build.py` expects it in `/usr/lib/libpython2.7.so`), so the installation fails. I believe this may also occur on other distros.

**Comment by micbou** [comment]
I guess that the following command:
```sh
python -c "from distutils import sysconfig; print( sysconfig.get_config_var( 'LIBDIR' ) )"
```
returns `/usr/lib` instead of `/usr/lib64` on Fedora, which is why the `build.py` script is failing.

Could you tell us what is the output of the command
```sh
python -c "from distutils import sysconfig; print( sysconfig.get_python_lib( standard_lib = True ) )"
```
on your config?

**Comment by llogiq** [comment]
`/usr/lib64/python2.7`
