### ISSUE TITLE
ycmd should return valid JSON instead of empty HTML for 2 requests

### ISSUE THREAD

**Issue by hydrargyrum** [Valloric/ycmd#536]
/load_extra_conf_file and /ignore_extra_conf_file requests currently return an empty body
in case of success, which is not valid JSON. Instead, ycmd should return valid JSON body, for example just "true".

**Comment by puremourning** [comment]
Please can you explain why you believe this change is necessary and generally useful? Is it causing you a problem?

FWIW we have some in-progress API documentation here: http://puremourning.github.io/ycmd-1/

**Comment by hydrargyrum** [comment]
> Please can you explain why you believe this change is necessary and generally useful?

Well, if ycmd wants to have a clean and consistent API, then all replies should follow some kind of rule. Considering almost all replies already are in JSON format, even errors, it may not be unreasonable to think that ALL replies should be JSON.
Even the documentation link *you* gave says the results of the request should be JSON :)
Allowing YCM clients to assume all ycmd replies are in the same format (JSON) can simplify clients code as you can imagine. (I assume it must not be too complicated for ycmd to just return 4 bytes ("true") instead of one)

This is the kind of detail that differenciates a good, predictable API from an average API, with gotchas awaiting at the corner.

**Comment by puremourning** [comment]
Nobody is going to deny the "cleanliness of API" argument. I was just curious as to whether there was a more pressing reason to make a (potentially breaking) API change (such as you're trying to do X and Y is not working). Changing the API for cosmetic reasons is hard to justify :/

IIRC this has come up before, though I forget the context.

**Comment by vheon** [comment]
The change we're talking about is really simple https://github.com/vheon/ycmd/commit/17cf01a9ee911189d1b9c5aaf99a230b1d8d35f4. So we only need to decide if it really makes sense.

**Comment by Valloric** [comment]
I'm not against this change. I can't see how it would be backwards incompatible; we weren't returning anything in the body before and I can't imagine how any client would break if the body they were ignoring before suddenly starting having content. The only thing clients did up to now is look at the status code.

So IMO this should be fine. We can just make these handlers return `{}` and be done with it.

If someone can make a convincing case that this would be a breaking change, then of course we wouldn't do it. It's entirely a cosmetic improvement.
