### ISSUE TITLE
How do I set .ycm_extra_conf.py to support MacOS App 

### ISSUE THREAD

**Issue by eschao** [Valloric/ycmd#540]
I'm trying to program mac app with YCMD and spacemacs. Previously my configuration can work for my iOS app, that means I can get completion for iOS functions. But for MacOS, the first **'#import \<Cocoa/Cocoa.h\>**' is error reported by YCMD, which says 'Cococa/Cocoa.h' file not found. Here is my part of .ycm_extra_conf.py:

```
'-isysroot',
'/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk',
'-isysroot',
'/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk',
'-I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Headers',
'-I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include',
'-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Foundation.framework/Headers',
'-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Cocoa.framework',

```
I don't know what's wrong with my configuration, How could I do it for MacOs App? Could you please give some instructions? Thank you very very much!

**Comment by puremourning** [comment]
I'm not sure that you can have 2 -isysroots

Try removing this?

```
'-isysroot',
'/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk',
```

Anyway, this is really a question about what flags you need to make a macOS project compile under clang, not a ycmd issue, so i'm closing it.

If you need more advice, please check [CONTRIBUTING.md](https://github.com/Valloric/ycmd/blob/master/CONTRIBUTING.md) which says where to seek it.
