### ISSUE TITLE
Why is clang_completer requesting `unloaded_buffer` key in OnBufferUnload

### ISSUE THREAD

**Issue by ptrv** [Valloric/ycmd#541]
Would it be possible to just reuse `filepath` in `OnBufferUnload` in `clang_completer` instead of having to specify `unloaded_buffer`. The typescript completer is already using `filepath`. It would be nice to align both.

**Comment by micbou** [comment]
This is a bug in the TypeScript completer. It should use `unloaded_buffer` instead of `filepath` because a buffer can be unloaded while not being the current buffer. I'll send a PR to fix this.

**Comment by ptrv** [comment]
Ok I see. Thanks for clarifying. We have a pull request regading adding `BufferVisit` and `BufferUnload` in `emacs-ycmd` which brought up this.
