### ISSUE TITLE
ycmd does not pass on many fixits

### ISSUE THREAD

**Issue by quicknir** [Valloric/ycmd#546]
I'm finding that ycmd occasionally suggests fixits for things like missing semi-colons, but for many other things it does not suggest a fixit even though clang does. For instance, if I write `std::strng x;`, when compiling in clang it offers the correction to `string`, but ycmd does not offer this fixit. Is this a bug with ycmd, something wrong with my setup, or is the fixit feature constrained somehow?

**Comment by Valloric** [comment]
@puremourning You'd probably know best.

**Comment by puremourning** [comment]
Can you check you are on the latest commit? We recently (like last week) merged a change which reports FixIts for notes, which should include typo correction (which is the type of case to which you are referring as I understand it)

It is also possible that your client doesn't handle multiple fix it options. Which client are you using ?

**Comment by puremourning** [comment]
Just as

**Comment by quicknir** [comment]
@puremourning I'm not exactly sure about being on the latest commit, the ycmd I use is built by someone else and distributed. The build is dated June 11 but I'm not necessarily sure whether they pulled that day. Is there some way I could tell from the released build whether that commit has been included?

I'm using the emacs-ycmd client. I'm not sure what you mean by multiple fixit options; I typed in `std::strng  x;` so the correction to string should have been the only fixit. Do you mean a situation whether I typed in `std::strng x`? It seems like emacs ycmd supports multi line fixits because when I do a fixit, it asks me to confirm whether I want to perform all fixits on that line.

**Comment by micbou** [comment]
@quicknir Could you provide the link to the build?

**Comment by quicknir** [comment]
@micbou Sorry I should have been more clear. We have a sort of package manager where I work so developers can install things easily without needing root. ycmd is available through that package manager. So I'm afraid I can't provide the link. If you can tell me the commit hash that adds multiple fixits I can ask the guy who's in charge of it, or if there's another way to tell from the built project.

**Comment by micbou** [comment]
It's this commit: cc87a9c5fc659f488879c3cb5bce090a966cbb70

**Comment by puremourning** [comment]
In fact, it doesn't look like typo correction is kicking in in the following test case:

```c++
#include <string>

int main( int argc, char ** argv )
{
  std::strng this_is_a_string;
}
```

Diags reported:

```
fixit.cc|5 col 8 error| no type named 'strng' in namespace 'std'
fixit.cc|3 col 15 warning| unused parameter 'argc'
fixit.cc|3 col 29 warning| unused parameter 'argv'
```

And `:YcmShowDetailedDiagnostic`:

```
Forcing compilation, this will block Vim until done.
/Users/ben/Development/tmp/fixit.cc:5:8: error: no type named 'strng' in namespace 'std'
```

So, `libclang` isn't reporting a note or a FixIt (therefore there isn't much we can do).

Just to be sure, I checked and it is not related to the `Incomplete` flag that we use.

Maybe @r4nt or @d0k know if libclang would be expected to offer fixits for typo correction as in the above example? 

Compiling with clang `-fsyntax-only` gives this:

```
BeniMac:tmp ben$ clang -x c++ -fsyntax-only -Wall -Wextra -Werror fixit.cc
fixit.cc:5:8: error: no type named 'strng' in namespace 'std'; did you mean 'string'?
  std::strng this_is_a_string;
  ~~~~~^~~~~
       string
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:194:65: note: 'string' declared here
typedef basic_string<char, char_traits<char>, allocator<char> > string;
                                                                ^
1 error generated.
```

**Comment by puremourning** [comment]
Ahah. You need to add `-fspell-checking` to your flags to enable this.

![ycm-fixit-spell-check](https://cloud.githubusercontent.com/assets/10584846/16895966/6480ece6-4b7d-11e6-893d-42000b83b408.gif)

**Comment by Valloric** [comment]
@puremourning Do we perhaps want to pass that by default? Something to consider.

**Comment by puremourning** [comment]
I was considering it. 

The slight con is that typo correction is guesswork, whereas FixIts are generally not going to change the semantics of your program. I guess I sort of ignored that for fixits on notes, principally because there are usually multiple options. In this case, the user doesn't get a "choice", but it is clear in the diagnostic message "; Did you mean 'string'?" So we are probably good to go with it.

At least it is good enough to be on by default when using the `clang` driver, so i don't see why we can't always turn it on.

**Comment by Valloric** [comment]
Seems like a plan; let's turn it on always. We already add some flags by default so it's not without precedent.

**Comment by puremourning** [comment]
PR on its way to fix this and the other bug we had recently with flags (to do with the preprocessor flags: https://github.com/Valloric/ycmd/issues/534). 

Happy to do them together? They're really closely related.

**Comment by Valloric** [comment]
> Happy to do them together? They're really closely related.

Sure. :)

**Comment by quicknir** [comment]
@puremourning Very cool, that makes it work for me, thanks for the fix. As always, thanks to all of you guys, ycmd is just amazing. I'm using Spacemacs w/ rtags and ycmd, and the auto completion, and especially flycheck is superior to anything that any Linux IDE provides; definitely the killer feature of my setup.
