### ISSUE TITLE
bump tern version to 0.19

### ISSUE THREAD

**Issue by aliceriot** [Valloric/ycmd#553]
0.19 has some good stability and usability increases over 0.17.

Would you accept a trivial PR that bumps the ternjs version?

**Comment by Valloric** [comment]
> Would you accept a trivial PR that bumps the ternjs version?

If all tests pass, sure! :)

**Comment by puremourning** [comment]
https://github.com/Valloric/ycmd/pull/544

Didn't we already do this?

**Comment by micbou** [comment]
Already done. See PR https://github.com/Valloric/ycmd/pull/544.

**Comment by puremourning** [comment]
Maybe we need to update the commit in YCM. But the ycmd issue can be closed.

**Comment by aliceriot** [comment]
Oh! Sorry for the noise! I'm filing useless issues all over the place today. I looked at `package.json` in the version of YouCompleteMe I have cloned on my computer, but didn't check the file in this repo T_T

**Comment by puremourning** [comment]
DOn't worry about it. Happy to help :)
