### ISSUE TITLE
hash mismatch while builing ycmd

### ISSUE THREAD

**Issue by manishtoons** [Valloric/ycmd#554]
Downloading Clang 3.8.0                                                                                                                                                                                           
CMake Error at ycm/CMakeLists.txt:89 (file):                                                                                                                                                                      
  file DOWNLOAD HASH mismatch                                                                                                                                                                                     

    for file: [~/prefs/ycmd/cpp/../clang_archives/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz]
      expected hash: [3120c3055ea78bbbb6848510a2af70c68538b990cb0545bac8dad01df8ff69d7]                                            
        actual hash: [e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855]                                            
             status: [56;"Failure when receiving data from the peer"]

**Comment by micbou** [comment]
This is a connection issue. You should try again. If it still doesn't work, you can directly download [the clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz file](http://llvm.org/releases/3.8.0/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz), put it in the `clang_archives` folder and run again the `build.py` script.
