### ISSUE TITLE
libclang.dll Assert failed!Expression: !T->isBeingDefined() && "Cannot serialize in the middle of a type definition"

### ISSUE THREAD

**Issue by pass86** [Valloric/ycmd#563]
libclang.dll Assert failed!Expression: !T->isBeingDefined() && "Cannot serialize in the middle of a type definition"

Upgrade to 3.8.1?

**Comment by Valloric** [comment]
Could you provide a reproducible test case?

**Comment by Valloric** [comment]
Also, please don't delete our issue template, but fill it in.

**Comment by micbou** [comment]
@Valloric We don't have an issue template in the ycmd repository.

@pass86 Could you update your report by following the instructions in [CONTRIBUTING.md](https://github.com/Valloric/YouCompleteMe/blob/master/CONTRIBUTING.md#writing-good-issue-reports)?

**Comment by Valloric** [comment]
@micbou You'd think I'd know that... :disappointed:

**Comment by micbou** [comment]
No answer. Closing.
