### ISSUE TITLE
Goto command going to host instead of toolchain system headers when cross-compiling

### ISSUE THREAD

**Issue by deb0ch** [Valloric/ycmd#564]
Hi,

I'm having a bit of trouble telling ycmd that the system headers to be used are the ones of my toolchain, as `ycmd-goto` keeps bringing me to my system headers instead of my toolchain ones.

For my current example, i do it on `SIG_IGN` defined in `signum.h`, which exists both in my toolchain and my system headers.

The flags for my file are fetched from my compile_commands.json, built using `bear`. I tried to add to it many variations and combinations of the following flags:

`-isystem`, `-sysroot`, `-isysroot`, `-gcc-toolchain`, `--gcc-toolchain`, `--with-gcc-toolchain`

and setting it (using a `=` or a ` ` as separator) to various locations within my toolchain directory, without any effect:

```
/opt/arm-2014.11-linaro/
/opt/arm-2014.11-linaro/arm-linux-gnueabihf/
/opt/arm-2014.11-linaro/arm-linux-gnueabihf/libc/
/opt/arm-2014.11-linaro/arm-linux-gnueabihf/libc/usr/
/opt/arm-2014.11-linaro/bin/arm-linux-gnueabihf-
```

I am using the [emacs-ycmd](https://github.com/abingham/emacs-ycmd) front-end, but I assume that this issue should not be related to the frontend in use.

Is it normal, is it a bug, or am I missing something ?

Thanks in advance.

**EDIT:** The solution for me was to add the `--sysroot=/opt/arm-2014.11-linaro/arm-linux-gnueabihf/libc/`.
General solution would therefore be to add `--sysroot=/path/to/libc/`

**Comment by vheon** [comment]
The fact that you're using `Bear` and a `compile_commands.json` means that you're using the exact same flags that you use to build your project, so the question is: why would you want `goto` to bring you to a different file than the one you use in your build?? 😕

**Comment by deb0ch** [comment]
This is precisely the problem, I'm cross-compiling and my host system headers are *not* used in the build, so `goto` brings me to the wrong file.

This code is supposed to run on a robot using a very different linux version from my system's.

I am using a separate toolchain for arm (my system is classical x86), so it doesnt need command line flags to use its own libc headers. That's why I need to manually add them, and even then `goto` brings me to my host libc/system headers instead of my target's.

**NB:** host = the linux on my own x86 computer
target = the linux on my arm robot

**Comment by micbou** [comment]
Could you paste the output of the command `ycmd-show-debug-info`?

> and setting it (using a = or a as separator) to various locations within my toolchain directory, without any effect:

Using spaces will not work. You need to separate each part of the flags with commas e.g. `[ ... , '-gcc-toolchain', '/some/path', ... ]`

**Comment by deb0ch** [comment]
```
ycmd debug information for buffer main.c in c-mode:

Server has Clang support compiled in: True
Clang version: clang version 3.8.0 (tags/RELEASE_380/final)
C-family completer debug information:
  Configuration file found and loaded
  Configuration path: /home/myusername/.spacemacs.d/global_conf.py
  Flags: ['cc', '-x', 'c', '-I/home/myusername/path/to/my/project/out/project-target/build/autopilot', '-I/home/myusername/path/to/my/project/packages/autopilot', '-I/home/myusername/path/to/my/project/packages/autopilot/src', '-I/home/myusername/path/to/my/project/packages/libcolibry/Includes', '-I/home/myusername/path/to/my/project/packages/libcolibry/Sources/nav', '-I/home/myusername/path/to/my/project/packages/libcolibry/Sources/logic/mykonos3/exported_headers', '-I/home/myusername/path/to/my/project/packages/ulog/libulog-redirect/include', '-I/home/myusername/path/to/my/project/packages/libshsettings/include', '-I/home/myusername/path/to/my/project/packages/libdmip/libdmip-ng/include', '-I/home/myusername/path/to/my/project/packages/libsensors/include', '-I/home/myusername/path/to/my/project/packages/libschedcfg/include', '-I/home/myusername/path/to/my/project/packages/tools/libvar/lib', '-I/home/myusername/path/to/my/project/packages/tools/libFSM', '-I/home/myusername/path/to/my/project/packages/telemetry/libtelemetry/include', '-I/home/myusername/path/to/my/project/packages/eigen', '-I/home/myusername/path/to/my/project/out/project-target/staging/usr/include/eigen3', '-I/home/myusername/path/to/my/project/packages/libhal/Includes', '-I/home/myusername/path/to/my/project/packages/libputils/include', '-I/home/myusername/path/to/my/project/packages/wifid/libwifid/include', '-I/home/myusername/path/to/my/project/packages/wifid/include', '-I/home/myusername/path/to/my/project/packages/libpomp/include', '-I/home/myusername/path/to/my/project/packages/libshdata/include', '-I/home/myusername/path/to/my/project/packages/libfutils/include', '-I/home/myusername/path/to/my/project/packages/ulog/libulog/include', '-I/home/myusername/path/to/my/project/packages/libhardware/include', '-I/home/myusername/path/to/my/project/packages/libgps/Sources', '-I/home/myusername/path/to/my/project/packages/libgps/Includes', '-I/home/myusername/path/to/my/project/packages/libgps/Sources/common', '-I/home/myusername/path/to/my/project/build/alchemy/pbuild-hook', '-isystem', '/home/myusername/path/to/my/project/out/project-target/staging/usr/include', '-isystem', '/home/myusername/path/to/my/project/out/project-target/staging/usr/include/arm-linux-gnueabihf', '-D_FORTIFY_SOURCE=2', '-pipe', '-g', '-O2', '-fno-short-enums', '-ffunction-sections', '-DALCHEMY_BUILD', '-fPIC', '-funwind-tables', '-Wmissing-prototypes', '-Wno-strict-prototypes', '-Wall', '-Wextra', '-Wno-unused', '-Wno-unused-parameter', '-Wunused-value', '-Wunused-variable', '-Wunused-label', '-Wpointer-arith', '-Wformat-nonliteral', '-Wformat-security', '-Winit-self', '-Werror=implicit-function-declaration', '-Werror=return-type', '-Werror=array-bounds', '-Wjump-misses-init', '-fdiagnostics-show-option', '-fdiagnostics-color', '-Wstrict-aliasing=3', '-Wunreachable-code', '-Wlogical-op', '-Os', '-fomit-frame-pointer', '-fno-strict-aliasing', '-finline-limit=64', '-DEIGEN_MPL2_ONLY', '-DEIGEN_QUATERNIONBASE_PLUGIN="QuaternionBaseAddons.hpp"', '-DARDRONE3', '-include', '/home/myusername/path/to/my/project/out/project-target/build/libColibry/autoconf-libColibry.h', '-include', '/home/myusername/path/to/my/project/out/project-target/build/libsensors/autoconf-libsensors.h', '-DBUILD_LIBCOLIBRY', '-DBUILD_LIBULOG_STDCERR', '-DBUILD_LIBSHS', '-DBUILD_LIBDMIPNG', '-DBUILD_LIBSENSORS', '-DBUILD_LIBSCHEDCFG', '-DBUILD_LIBCRYPTO', '-DBUILD_LIBVAR', '-DBUILD_LIBFSM', '-DBUILD_LIBTELEMETRY', '-DBUILD_EIGEN', '-DBUILD_LIBHAL_HEADERS', '-DBUILD_LIBPUTILS', '-DBUILD_LIBWIFID', '-DBUILD_LIBPOMP', '-DBUILD_LIBSHDATA', '-DBUILD_LIBFUTILS', '-DBUILD_LIBULOG', '-DBUILD_LIBCONFIG', '-funsigned-char', '-gcc-toolchain', '/opt/arm-2014.11-linaro/arm-linux-gnueabihf/', '-resource-dir=/home/myusername/.emacs.d/private/YouCompleteMe/third_party/ycmd/ycmd/../clang_includes']

Server running at: 127.0.0.1:42053

```

**Comment by micbou** [comment]
According to [this](https://developer.android.com/ndk/guides/standalone_toolchain.html#itc), you need to set the `--sysroot`, `-target`, and `-gcc-toolchain` flags. I guess in your case `-target` must be set to `armv7-none-linux-androideabi`.

**Comment by deb0ch** [comment]
Just tried with
```
		-gcc-toolchain
		/opt/arm-2014.11-linaro/
		-target=arm-linux-gnueabihf
		--sysroot=/opt/arm-2014.11-linaro/arm-linux-gnueabihf/libc/
```

same result :confused:

**Comment by micbou** [comment]
I downloaded and extracted [the gcc-linaro-4.9-2014.11-x86_64_arm-linux-gnueabihf.tar.xz archive](https://releases.linaro.org/14.11/components/toolchain/binaries/arm-linux-gnueabihf/) (is this the right archive to download?) and was able to jump to the right `signal.h` file by using the following `.ycm_extra_conf.py` file:
```python
flags = [
  '-x', 'c',
  '--sysroot=/path/to/linaro/libc'
]

def FlagsForFile( filename, **kwargs ):
    return {
      'flags': flags,
      'do_cache': True
    }
```
I just appended `libc`  to the `linaro` path in the `--sysroot` flag. The other flags `-target` and `-gcc-toolchain` was not needed (at least for jumping). It looks like this is what you tried in your last post so I am surprised it doesn't work for you. Could you try on a minimal case like this one:
```c
#include <signal.h>

int main() {
	SIG_IGN;
}
```
?

**Comment by deb0ch** [comment]
Hi Micbou,

Thanks so much for looking into my issue and actually trying that out.
I have to deal with an urgent matter at work right now, I will get back to you as soon as I'm out of the rush.

Again, thanks and see you soon ! Cheers.

**Comment by deb0ch** [comment]
Hi,

I just tried your example and it works.

I tried again in my project, adding only the `--sysroot=/opt/arm-2014.11-linaro/arm-linux-gnueabihf/libc/` flag to my compilation flags and `ycmd-goto` brought me to the correct header file from my toolchain.

I don't know what exactly went wrong in my previous tries. Maybe I did not provide the correct flag (`-sysroot` instead of `--sysroot`, maybe the other flags like `-gcc-toolchain`  or `-target` got in the way, or something else...).

Anyways, I didn't know which to choose and that the `--sysroot=/path/to/libc` was the one.

Thank you so much for your help, I was going crazy solving this.

**PS:** I actually tried to google up what was causing my issue and it was very hard to find useful information.
Do you think it would be worth adding a line or a reference to this issue to the documentation for people in my case ?  
  
**PS2:** I also faced another problem as some `-msomestuff` flags triggered libclang errors because they were only known by my toolchain and not libclang. I worked it arround by filtering out all `-m` flags from my global_conf.py.
As those flags are not relevant for parsing anyways, do you think it would be a good idea to filter them out from inside ycmd ?
Should I open a separate issue for that ?

**Comment by micbou** [comment]
> PS: I actually tried to google up what was causing my issue and it was very hard to find useful information.
Do you think it would be worth adding a line or a reference to this issue to the documentation for people in my case ?

I don't think that's necessary. Users will search the issue tracker and find your report. In fact, they can already find it on Google.

> PS2: I also faced another problem as some -msomestuff flags triggered libclang errors because they were only known by my toolchain and not libclang. I worked it arround by filtering out all -m flags from my global_conf.py.
As those flags are not relevant for parsing anyways, do you think it would be a good idea to filter them out from inside ycmd ?

If we are sure that [all `-m*` flags](https://gcc.gnu.org/onlinedocs/gcc/Submodel-Options.html#Submodel-Options) can be safely ignored then yes, we should strip them.

> Should I open a separate issue for that ?

Feel free to open a new issue. I am closing this one since the initial issue is resolved.
