### ISSUE TITLE
Options file?

### ISSUE THREAD

**Issue by agauniyal** [Valloric/ycmd#567]
Pardon my ignorance, I'm trying to build some sort of autocompletion and was looking at using ycmd as backend. I have correctly built the project and after a little while looking for a built binary, I realized I have to start `project_root/ycmd/__main__.py`, right? It requires certain arguments to be passed along with it such as `port` and `options file`. 

Here is the example from the repo - https://github.com/Valloric/ycmd/blob/master/examples/example_client.py#L81

What exactly should be the contents of that options file? And why is it deleted by ycmd during startup? I tried looking elsewhere - https://github.com/Qusic/atom-youcompleteme/blob/master/lib/handler.coffee#L60 , but couldn't get an answer.

Thankyou :)

**Comment by agauniyal** [comment]
Oops - https://github.com/Valloric/ycmd#user-level-customization.

**Comment by puremourning** [comment]
http://puremourning.github.io/ycmd-1/

Might also be useful

**Comment by agauniyal** [comment]
@puremourning indeed it is. Thankyou 😄

**Comment by puremourning** [comment]
No problem. Be aware that it hasn't been reviewed and isn't totally up to date, but I hope it is nonzero helpful anyway :)
