### ISSUE TITLE
exit code not correct if importing ycm_core in global config fails

### ISSUE THREAD

**Issue by ptrv** [Valloric/ycmd#569]
Hi,

I am not sure this is a real bug, but I encountered this while implementing handling of exit code in `emacs-ycmd`.

I had a `import ycm_core` in my global config. If importing fails there the line with `code = CompatibleWithCurrentCore()` in `__main__.py` will never be reached to return the correct exit code and then I just get an exit code 1.

**Comment by Valloric** [comment]
Ugh, that does sound like a bug.
