### ISSUE TITLE
Clang Compliation Database Windows

### ISSUE THREAD

**Issue by LukeMauldin** [Valloric/ycmd#582]
I have attached a simple test application.  It uses clang-cl from the LLVM distro and Ninja to build C++ on Windows.  I have installed the latest ycmd integration with Vim.  You can see the debug information below.  It looks like the .ycm_extra_conf.py is getting confused when reading the compile database on Windows.  As a result, auto complete and syntax checking isn't working.  If you look at the file `.ycm_extra_conf-Works.py`, that works for me but I would prefer not to hard-code all of my flags and include directories manually and have ycmd correctly read from the compile database. 

```
Printing YouCompleteMe debug information...
-- Server has Clang support compiled in: True
-- Clang version: clang version 3.8.0 (branches/release_38)
-- C-family completer debug information:
--   Configuration file found and loaded
--   Configuration path: c:\Users\lukem\Documents\Visual Studio 2015\Projects\CmakeCpp\.ycm_extra_conf.py
--   Flags: ['/nologo', '-x', 'c', '-IC:/Users/lukem/Documents/Visual Studio 2015/Projects/CmakeCpp/build-ninja-debug\\..deps', 'C:UserslukemDocumentsVisual Studio 2015ProjectsCmakeCppsrcEmployee.cpp', '-resource-dir=C:\\Users\\lukem\\vimfiles\\bundle\\YouCompleteMe\\third_party\\ycmd\\ycmd\\..\\clang_includes', '-fno-delayed-template-parsing', '-fspell-checking']
-- Server running at: http://127.0.0.1:57921
-- Server process ID: 9508
-- Server logfiles:
--   C:\Users\lukem\AppData\Local\Temp\ycm_temp\server_57921_stdout.log
--   C:\Users\lukem\AppData\Local\Temp\ycm_temp\server_57921_stderr.log
```

**Comment by micbou** [comment]
> I have attached a simple test application.

I don't see the link.

**Comment by LukeMauldin** [comment]
[CmakeCpp.zip](https://github.com/Valloric/ycmd/files/440104/CmakeCpp.zip)

See attached

**Comment by comicfans** [comment]
[this](https://github.com/Valloric/ycmd/pull/602) may helps
 
1. you need to add --driver-mode=cl 
2. ycmd needs a little modify (see link)
3. windows style path separator needs to be '////' , not '//'. your YcmDebugInfo shows that C:UserslukemDocumentsVisual Studio 2015ProjectsCmakeCppsrcEmployee.cpp  is not correct

**Comment by micbou** [comment]
This is now working thanks to PRs https://github.com/Valloric/ycmd/pull/789, https://github.com/Valloric/ycmd/pull/936, and https://github.com/Valloric/ycmd/pull/938.
