### ISSUE TITLE
had to symlink some libs on Arch Linux

### ISSUE THREAD

**Issue by unhammer** [Valloric/ycmd#59]
On Arch Linux, I had to do

```
$ ln -s /usr/lib/libncurses.so.5 libtinfo.so.5
$ ln -s /usr/lib/libedit.so libedit.so.2 
```

to get it running. Maybe this could go in a readme (or ideally ycmd would find the right files, though I don't know how hard that is).

**Comment by waltsims** [comment]
which directory does the link have to be in? Also i only found a /usr/lib/libncurses.so.6 not [...].s0.5.  Would that still work?  Thanks

**Comment by oblitum** [comment]
@waltsims I've provided a solution on #778 comments.
