### ISSUE TITLE
Backend for flow

### ISSUE THREAD

**Issue by aaronjensen** [Valloric/ycmd#597]
Like typescript, [flow](https://flowtype.org/) has a completion server. It'd be nice to have a backend for flow.

**Comment by aaronjensen** [comment]
It is a static type checker, but it also has an autocomplete capability:

```
$ flow autocomplete --help
Usage: flow autocomplete [OPTION] [FILE] [LINE COLUMN]...

Queries autocompletion information.

If line and column is specified, then the magic autocomplete token is
automatically inserted at the specified position.

Example usage:
        flow autocomplete < foo.js
        flow autocomplete path/to/foo.js < foo.js
        flow autocomplete 12 35 < foo.js

  --from                            Specify client (for use by editor plugins)
  --help                            This list of options
  --ignore-version                  Ignore the version constraint in .flowconfig
  --json                            Output results in JSON format
  --no-auto-start                   If the server is not running, do not start it; just exit
  --retries                         Set the number of retries. (default: 3)
  --retry-if-init                   retry if the server is initializing (default: true)
  --root                            Project root directory containing the .flowconfig
  --sharedmemory-dep-table-pow      The exponent for the size of the shared memory dependency table. The default is 17, implying a size of 2^17 bytes
  --sharedmemory-dirs               Directory in which to store shared memory heap (default: /dev/shm/)
  --sharedmemory-hash-table-pow     The exponent for the size of the shared memory hash table. The default is 19, implying a size of 2^19 bytes
  --sharedmemory-log-level          The logging level for shared memory statistics. 0=none, 1=some
  --sharedmemory-minimum-available  Flow will only use a filesystem for shared memory if it has at least these many bytes available (default: 536870912 - which is 512MB)
  --strip-root                      Print paths without the root
  --temp-dir                        Directory in which to store temp files (default: /tmp/flow/)
  --timeout                         Maximum time to wait, in seconds
```

Here's a company backend for it: https://github.com/aaronjensen/company-flow/

**Comment by vheon** [comment]
Ok, so is not a programming language but rather a tool for javascript, but for javascript we already use [Tern.js](https://github.com/ternjs/tern). Is this better than Tern in some way? Can you present the benefits of using this instead of Tern?

**Comment by aaronjensen** [comment]
Flow is capable of very deep type inspection just like typescript. Unlike tern, you cannot just use it on any project, the project must be configured for flow. If it is then you can get auto completion like typescript, that is, like a static language. 

To be succinct, flow provides the same benefits as typescript but with annotations and an annotation stripper rather than a different language and a compiler.

**Comment by Valloric** [comment]
Eh, I don't see much benefits of supporting both the flow completion server and tern.js. They both provide completion for javascript. I'm not sure how we would even go about supporting two backends for the same filetype.

**Comment by aaronjensen** [comment]
tern has never impressed me w/ its completion, whereas flow and typescript by their nature have significantly more information about types and completions. That said, I'll stick to company-flow, thanks for considering.
