### ISSUE TITLE
`working_dir` is ignored in tern completer

### ISSUE THREAD

**Issue by Qusic** [Valloric/ycmd#605]
https://github.com/Valloric/ycmd/blob/master/ycmd/completers/javascript/tern_completer.py#L142

This is called on the event `OnFileReadyToParse` but it searches for tern project file in `os.getcwd()` instead of `working_dir` parameter provided by clients.

And it's better if it can even handle the changes of `working_dir`.

**Comment by puremourning** [comment]
Please can you give a description of the actual problem you are seeing and a list of steps to reproduce? We recently made changes in this area and the way it handles this is quite precise due to the behaviour of tern server.

**Comment by Qusic** [comment]
The problem is that semantic completion and diagnostic display won't work when the working directory(where ycmd is launched from) is different from the actual project directory.

**Comment by micbou** [comment]
The `working_dir` parameter only purpose is to set the root directory for relative paths in the filename completer when the `filepath_completion_use_working_dir` option is enabled. It should only be passed when sending a completion request.

> The problem is that semantic completion and diagnostic display won't work when the working directory(where ycmd is launched from) is different from the actual project directory.

This is intended. From the YCM documentation:

> Multiple Tern servers, are not supported. To switch to a different JavaScript project, you can do one of the following:
> - start a new instance of Vim from the new project's directory
> - change Vim's working directory (:cd /path/to/new/project) and restart the ycmd server (:YcmRestartServer)
> - change Vim's working directory (:cd /path/to/new/project), open a JavaScript file (or set filetype to JavaScript) and restart the Tern server using YCM completer subcommands :YcmCompleter StopServer and :YcmCompleter StartServer.

In last item, the `:YcmCompleter RestartServer` subcommand should be used instead of both subcommands. We forgot to update the docs.

**Comment by Qusic** [comment]
Ok. Thanks for explaining it. I will add commands for users to restart ycmd server and completer server in the Atom client.
