### ISSUE TITLE
GetType eats up lots of memory

### ISSUE THREAD

**Issue by agauniyal** [Valloric/ycmd#606]
It doesn't depends on which editor I use, vim, nvim or vscode... whenever a call is made for GetType, the memory consumption increases by `~.4%`. So if I've 10 variables, which for which I call GetType, it keeps on eating memory and soon the memory consumption is beyond 20% on my system and I've to restart my editor. Aaaand to make it worse, it still increases if I'm calling it on the same var each time.

I couldn't spot this problem with vim/nvim + ycm because I've to voluntarily call GetType on each var which I usually skipped out of laziness. But with vscode version it was enabled by default. Here's the issue I filed - https://github.com/richard1122/vscode-youcompleteme/issues/11

Here's my ycm config - 

```
import os
import ycm_core

flags = [
'-Wall',
'-Wextra',
'-Werror',
'-fexceptions',
'-DNDEBUG',
'-std=c++14',
'-I/usr/include/c++',
]


compilation_database_folder = 'build'

if os.path.exists( compilation_database_folder ):
  database = ycm_core.CompilationDatabase( compilation_database_folder )
else:
  database = None

SOURCE_EXTENSIONS = [ '.cpp', '.cxx', '.cc', '.c' ]

def DirectoryOfThisScript():
  return os.path.dirname( os.path.abspath( __file__ ) )


def MakeRelativePathsInFlagsAbsolute( flags, working_directory ):
  if not working_directory:
    return list( flags )
  new_flags = []
  make_next_absolute = False
  path_flags = [ '-isystem', '-I', '-iquote', '--sysroot=' ]
  for flag in flags:
    new_flag = flag

    if make_next_absolute:
      make_next_absolute = False
      if not flag.startswith( '/' ):
        new_flag = os.path.join( working_directory, flag )

    for path_flag in path_flags:
      if flag == path_flag:
        make_next_absolute = True
        break

      if flag.startswith( path_flag ):
        path = flag[ len( path_flag ): ]
        new_flag = path_flag + os.path.join( working_directory, path )
        break

    if new_flag:
      new_flags.append( new_flag )
  return new_flags


def IsHeaderFile( filename ):
  extension = os.path.splitext( filename )[ 1 ]
  return extension in [ '.h', '.hxx', '.hpp', '.hh' ]


def GetCompilationInfoForFile( filename ):
  # The compilation_commands.json file generated by CMake does not have entries
  # for header files. So we do our best by asking the db for flags for a
  # corresponding source file, if any. If one exists, the flags for that file
  # should be good enough.
  if IsHeaderFile( filename ):
    basename = os.path.splitext( filename )[ 0 ]
    for extension in SOURCE_EXTENSIONS:
      replacement_file = basename + extension
      if os.path.exists( replacement_file ):
        compilation_info = database.GetCompilationInfoForFile(
          replacement_file )
        if compilation_info.compiler_flags_:
          return compilation_info
    return None
  return database.GetCompilationInfoForFile( filename )


# This is the entry point; this function is called by ycmd to produce flags for
# a file.
def FlagsForFile( filename, **kwargs ):
  if database:
    # Bear in mind that compilation_info.compiler_flags_ does NOT return a
    # python list, but a "list-like" StringVec object
    compilation_info = GetCompilationInfoForFile( filename )
    if not compilation_info:
      return None

    final_flags = MakeRelativePathsInFlagsAbsolute(
      compilation_info.compiler_flags_,
      compilation_info.compiler_working_dir_ )
  else:
    relative_to = DirectoryOfThisScript()
    final_flags = MakeRelativePathsInFlagsAbsolute( flags, relative_to )

  return {
    'flags': final_flags,
    'do_cache': True
  }
```

**Comment by agauniyal** [comment]
https://sendvid.com/9wgm18l4

Latest ycm so the version of ycmd is the latest bundled with it.

**Comment by puremourning** [comment]
That's worrying. We're going to need a reliably reproducible test case. 

Does this also happen for any other command m, like GetParent, GetDoc, FixIt etc or is it exclusive to GetType? Does it happen for every project or is there something specific to one project?

I've never noticed this and while there is a remote possibility of a mem leak in ycmd, this is likely to be libclang AST issue.

**Comment by agauniyal** [comment]
I'll do some testing with few oss projects and currently I'm building ycm with system clang too, I'll do the test without system clang version too and report back.

**Comment by bstaletic** [comment]
I did a quick test with a [randomly chosen file](https://github.com/vim/vim/blob/master/src/eval.c) from vim source itself. With every call to `:YcmCompleter GetType` the memory usage increased by 2MiB. The identifier I requested the type of did not matter. I know it is hardly noticeable, but the memory leak is there. The I tried the same thing with `:YcmCompleter GetParent` and have gotten the same results, i.e. a steady increase of memory usage for every time I issue `:YcmCompleter GetParent` in increments of about 2MiB and sometimes a bit more. `.ycm_extra_conf.py` generated by using `:YcmGenerateConfig` from [`YCM-Generator`](https://github.com/rdnetto/YCM-Generator).

**Comment by agauniyal** [comment]
I can confirm it happens with both system clang and the bundled clang which ycm downloads. I've tried in past to build it with `-O3`, so I dropped down to `-O2`, then no flags too, it happens in all cases.

Here's what I'm testing on - https://github.com/agauniyal/isaac-core/tree/develop/

**Comment by agauniyal** [comment]
I've also noticed something strange, it keeps going upto 12% (out of 4GB) per file and then it kinda slows down and goes to 15%. If I open next file and begin calling again, it will readily shoot to 25% + memory...

**Comment by bstaletic** [comment]
I have also tried testing on this file
```c
#include <stdio.h>

int i;

int main()
{
        printf("%d",i);
        i++;
        return 0;
}
```
Either it is not happening with such a small file or the leak is somehow related to the file size (translation unit size?) and the memory leak is just too small to notice.

**Comment by puremourning** [comment]
In my fork there is a command GetTypeQuick which gets the type without reparsing. I would like to see if that has the same issue, which would tell us something about the where it happens. Anyone care to try it out? Sorry I can't at work.

**Comment by agauniyal** [comment]
@puremourning I can do it, should I clone this YCM - https://github.com/puremourning/YouCompleteMe ? Or would I've to somehow replace ycmd module only..

**Comment by puremourning** [comment]
Thanks. 

You just want this commit. https://github.com/puremourning/ycmd-1/commit/1a572fb37a8a5b19977c9eb3c4d6c4d71b95a77b

**Comment by bstaletic** [comment]
@puremourning I have tried GetTypeQuick with [puremourning/YouCompleteMe](https://github.com/puremourning/YouCOmpleteMe) and [puremourning/ycmd-1](https://github.com/puremourning/ycmd-1) which I have renamed to ycmd in the YouCompleteMe/third_party/ directory. Repeating `:YcmdCompleter GetTypeFast` on a random variable/function in [eval.c](https://github.com/vim/vim/blob/master/src/eval.c) resulted in an even bigger increase in memory consumption. The memory consumption is still far from alarming, but it got from 2MiB per call to `:YcmCompleter GetType` to 4MiB per call to `:YcmCompleter GetTypeQuick`

**Comment by agauniyal** [comment]
No increase in memory on my system, tried across files but ycm stays at 3.5% at all times. However I did use original ycm and ycmd, just introduced @puremourning 's commit.

**Comment by bstaletic** [comment]
Alright, maybe my test was a little too short to provide a solid conclusion. I'll test a bit more and see what happens.

**Comment by agauniyal** [comment]
```
'GetType'                  : ( lambda self, request_data, args:
   self._GetSemanticInfo( request_data, func = 'GetTypeAtLocation' ) ),

'GetTypeQuick'             : ( lambda self, request_data, args:
   self._GetSemanticInfo( request_data,
                          func = 'GetTypeAtLocation',
                          reparse = False ) ),
```

I've interchanged these two and it works great, no more increase in memory on GetType.

However I still want to ask, how much memory does ycm usually takes per file? Is 120-150MBs allright for parsing of each file? Mine's not even a medium sized project.

**Comment by bstaletic** [comment]
My previous test was too short. The difference in memory increase does not actually exist, but the memory increase is still there, no matter if I use GetType, GetTypeQuick or GetParent. I have tried more files this time and the results are the same - there is a memory increase of about 2MiB for every call to any of the three functions.

**Comment by agauniyal** [comment]
It would be great if we could get `'GetTypeQuick'` inside ycmd too, then I could ask other plugin maintainers to provide a config for switching b/w these two functions for usage like GetType on hover.

**Comment by puremourning** [comment]
> It would be great if we could get 'GetTypeQuick' inside ycmd too
#609 opened.

I will try and take a look at the memory issue this evening. I have a branch somewhere which reports the resource usages of the AST. Running valgrind/purify/asan on python is a bit of a pain, so i hope that shows it isn't ycmd &_&

**Comment by puremourning** [comment]
I have tried to reproduce this on OS X and Linux with no success.

If I run the following a few times in vim:

```viml
:for i in range(100)
:  YcmCompleter GetType
:endfor
```

The memory usage of ycmd fluctuates, but ends up exactly the same.

```
PID    COMMAND      %CPU TIME     #TH  #WQ  #POR MEM   PURG CMPR PGRP  PPID STATE    BOOSTS     %CPU_ME %CPU_OTHRS UID  FAULTS   COW   MSGS MSGR SYSBSD SYSMA CSW    PAGEI IDLE POWE
15710  Python       0.0  01:28.74 32   0    106  175M  0B   0B   15710 15704 sleeping *0[1]      0.00000 0.00000    501  3085641  9353  289  122  500322+ 3334  42109+ 1073  462  0.0

... 100 later

PID    COMMAND      %CPU TIME     #TH  #WQ  #POR MEM   PURG CMPR PGRP  PPID STATE    BOOSTS     %CPU_ME %CPU_OTHRS UID  FAULTS   COW   MSGS MSGR SYSBSD SYSMA CSW    PAGEI IDLE POWE
15710  Python       0.0  01:28.74 32   0    106  175M  0B   0B   15710 15704 sleeping *0[1]      0.00000 0.00000    501  3085641  9353  289  122  500322+ 3334  42109+ 1073  462  0.0

... 200 later

PID    COMMAND      %CPU TIME     #TH  #WQ  #POR MEM   PURG CMPR PGRP  PPID STATE    BOOSTS     %CPU_ME %CPU_OTHRS UID  FAULTS   COW   MSGS MSGR SYSBSD SYSMA CSW    PAGEI IDLE POWE
15710  Python       0.0  01:28.74 32   0    106  175M  0B   0B   15710 15704 sleeping *0[1]      0.00000 0.00000    501  3085641  
```

And the resource usage reported by `libclang` (using my branch which adds this to the `:YcmDebugInfo`) is completely stable (within a few % - `libclang` has some caches and things which fluctuate).

So... what's the difference?

**Comment by puremourning** [comment]
Hold that thought. Using `eval.c` from Vim, i *can* repro.

However, the pattern is that the mem usage grows and grows, and then shrinks in a sawtooth pattern akin to garbage collection in many languages.

```
after 100, at rem usage 210MB

-- TU /Users/ben/Development/vim/src/eval.c using 6843976 bytes as:
--   - AST: 4660956
--   - Results Cache: 6078172
--   - Identifiers: 6160092
--   - Preprocessor: 6454144
--   - Selectors: 6454144
--   - Source Manager: 6843976

after 200, 265M

-- TU /Users/ben/Development/vim/src/eval.c using 6843976 bytes as:
--   - AST: 4660956
--   - Results Cache: 6078172
--   - Identifiers: 6160092
--   - Preprocessor: 6454144
--   - Selectors: 6454144
--   - Source Manager: 6843976

running 1000...
peaks at around 359M
then drops back to 90M
```

So it is not `libclang` doing this, nor is it `ycmd`'s c++ code leaking, but most likely python's internal memory management which we have little control over.

There's not much we can really do about this, though. While I can't 100% rule out that our python code might possibly be optimised around this, I don't think there's a lot of excitement around the team to go fiddling in the python layer at this level of detail.

Importantly, I can show that this is not a leak in the unbounded sense, but a sawtooth that is common in dynamic languages, so I'm going to close this for now. We can re-open it if you find you have new evidence.

**Comment by bstaletic** [comment]
Alright, that sounds reasonable. I wouldn't expect anyone to tackle garbage collector issues like this one, as it sounds almost like fighting windmills.

**Comment by puremourning** [comment]
> fighting windmills

Heh. Totally!

**Comment by Valloric** [comment]
@puremourning Nice analysis! :)

**Comment by agauniyal** [comment]
I'm okay with it since we're getting `GetTypeQuick` so I'll have a choice here :)
