### ISSUE TITLE
--system-libclang

### ISSUE THREAD

**Issue by yudengqing** [Valloric/ycmd#611]
My OS is Mac OS X10.11.6, and I have installed Xcode with command line tools. When I build ycmd with ./build.py --all, it is fine. However when I ran ./build.py --clang-completer --system-libclang, it  will crashed. How can I solve it?

**Comment by vheon** [comment]
Why would you solve a thing that already works? The `--system-libclang` was introduced for those platform (like FreeBSD) where the precompiled libclang weren't available and is supported on our best effort. On macOS the libclang that we automatically download works fine, as you've experienced with `./build.py --all`, so I don't see an issue here. Anyway if you only need the clang completer, just use `./build.py --clang-completer`. I don't see any issue with ycmd for your platform so closing.
