### ISSUE TITLE
Processing .ycm_extra_conf.py creates __pycache__ directory

### ISSUE THREAD

**Issue by ChuckDaniels87** [Valloric/ycmd#618]
I'm not sure if this is the intended behaviour. When YCM reads configuration creates a compiled version in `__pycache__`. I know that this behaviour can be disabled passing to `python` the `-B` argument or setting `PYTHONDONTWRITEBYTECODE=1` environmental variable. I don't want to disable global bytecode generation but I want to disable for `.ycm_extra_conf.py` because I feel it pollutes my project directory. 

Is there a easy/reliable way to disable it in the YCM config?

**Comment by micbou** [comment]
We could disable the compiled version with [the `sys.dont_write_bytecode` variable](https://docs.python.org/3/library/sys.html#sys.dont_write_bytecode) before loading the `.ycm_extra_conf.py` file then re-enable it just after. Seems to work in my tests.

I don't think we should add an option for that. Instead, we should always disable it as the only benefit of the compiled version is to improve loading time by skipping the compilation step but in practice the time to compile a `.ycm_extra_conf.py` file is negligible (~8ms for YCM's `.ycm_extra_conf.py` file) and is only done once by editing session.

**Comment by ChuckDaniels87** [comment]
Short after opening this issue, I added `sys.dont_write_bycode` to my `ycm_extra_conf.py` and it also seems to work. Nevertheless, I agree with you, if there is not noticeable improvement it should be disabled by default.

**Comment by Valloric** [comment]
@micbou SGTM

**Comment by micbou** [comment]
@ChuckDaniels87 Could you try PR #623? It works for me but I'd like some confirmation.

**Comment by ChuckDaniels87** [comment]
@micbou It seems it is working fine. Thanks for the quick fix! :+1:
