### ISSUE TITLE
ycmd-get-parent doesn't show the return type of function in C 

### ISSUE THREAD

**Issue by zijianyue** [Valloric/ycmd#620]
e.g. : a function like below
int func(int a, short b) 
ycmd-get-parent will show func(int, short).
Wish to improve that :)

I've submitted the same issue to emacs-ycmd, but they said I should submit it here.
https://github.com/abingham/emacs-ycmd/issues/363

**Comment by vheon** [comment]
A little more information would be helpful:

- Can you show a minimal example?
- What did you expect `ycmd-get-parent` should have returned?

**Comment by zijianyue** [comment]
int func(int a, short b)
{
    TABB aaaa;
    return 0;
}
ycmd-get-parent show:
func(int, short)
expect:
int func(int, short)

**Comment by micbou** [comment]
This is what [`clang_getCursorDisplayName`](http://clang.llvm.org/doxygen/group__CINDEX__CURSOR__XREF.html#gac3eba3224d109a956f9ef96fd4fe5c83) is returning to us. Would you prefer to get the type of the parent? In your example, it would be:
```c
int (int, short)
```
instead of
```c
func(int, short)
```
or do you really want:
```c
int func(int, short)
```
?

**Comment by puremourning** [comment]
The name is the most important here, and the reason the feature was added.

You can't overload on return type, so it does not create ambiguity.

The purpose of the feature is to see where you are in a large file. I think it serves that purpose?

**Comment by zijianyue** [comment]
@micbou int func(int, short) is needed
@puremourning the function name is most important here,but the return type is useful when coding I think. For I can decide what type to return without jump to the beginning of the function to see the return type.

**Comment by puremourning** [comment]
That's a different use case. And I sincerely object to any change which removes the actual context for which this feature was designed.
