### ISSUE TITLE
UnicodeEncodeError thrown when the path contains non-ASCII characters

### ISSUE THREAD

**Issue by ekd123** [Valloric/ycmd#633]
Hi!
I'm using YCM for a project, and the path name contains some non-ASCII characters (in this case, CJK characters).
If I choose to load .ycm_extra_conf.py, UnicodeEncodeError is thrown saying 'ascii' codec can't encode characters in position xx-xx: ordinal not in range(128)
I hope this can be fixed soon! Thanks!

**Comment by ekd123** [comment]
For example, a folder called プログラミング or 项目 can reproduce this problem easily.

**Comment by micbou** [comment]
You should report this issue [on YCM repository](https://github.com/Valloric/YouCompleteMe). Follow the instructions in [CONTRIBUTING.md](https://github.com/Valloric/YouCompleteMe/blob/master/CONTRIBUTING.md#writing-good-issue-reports).
