### ISSUE TITLE
Completion doesn't work in ifdefs

### ISSUE THREAD

**Issue by beojan** [Valloric/ycmd#648]
Completion isn't working for variables defined within an `#ifdef` section.

These are used for choosing code paths at compile time (by defining the macro in the build system), so completion should be available in these sections.

**Comment by vheon** [comment]
We use libclang and the flags that you specify in the `.ycm_extra_conf.py` to provide the completion and to do that libclang actually compile your code so, if you didn't specify the `#define` required by that `#ifdef` branch I don't think is possible to give you the autocompletion you expect.

**Comment by Valloric** [comment]
@vheon provided a good explanation. Whether you get semantic completion for stuff inside an `#ifdef` depends entirely on the flags you provide to libclang through `.ycm_extra_conf.py`.

Please provide a detailed test case demonstrating the problem in case we've misunderstood the issue.
