### ISSUE TITLE
can't go-to-definition in atom editor

### ISSUE THREAD

**Issue by xuweitz** [Valloric/ycmd#653]
Can't jump to definition or declaration.
Traceback (most recent call last):
File "/home/xw/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 861, in _handle
return route.call(**args)
File "/home/xw/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
rv = callback(*a, **ka)
File "/home/xw/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 109, in wrapper
return callback( *args, **kwargs )
File "/home/xw/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/hmac_plugin.py", line 72, in wrapper
body = callback( *args, **kwargs )
File "/home/xw/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/handlers.py", line 82, in RunCompleterCommand
request_data ) )
File "/home/xw/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 336, in OnUserCommand
return command( self, request_data, arguments[ 1: ] )
File "/home/xw/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 125, in 
self._GoTo( request_data ) ),
File "/home/xw/.vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 200, in _GoTo
raise RuntimeError( 'Can't jump to definition or declaration.' )
RuntimeError: Can't jump to definition or declaration.

**Comment by micbou** [comment]
You need to tell us in which context. It's not always possible to jump to a definition or a declaration.

**Comment by Valloric** [comment]
@xuweitz Please provide a detailed, reproducible test case.

**Comment by xuweitz** [comment]
![2016-11-22 09-41-37](https://cloud.githubusercontent.com/assets/16414822/20507783/f99d1b04-b097-11e6-85f1-64dac9d57dbf.png)
When I Ctal+click a function name to go to definition, it has been such a mistake that RuntimeError. 
PS. It's in atom editor

**Comment by xuweitz** [comment]
![2016-11-22 09-50-52](https://cloud.githubusercontent.com/assets/16414822/20507982/6694ce18-b099-11e6-9bc9-3d283369f866.png)
![2016-11-22 09-51-25](https://cloud.githubusercontent.com/assets/16414822/20507993/6afc8252-b099-11e6-9ef7-3e80bbbfbc56.png)
In the atom editor installed you-complete-me plugin, the figure for the plugin details.

**Comment by xuweitz** [comment]
In the ycm_build directory the Makefiles files generated and then Execute command: make ycm_support_libs, but had a error, the detail is: make: * * * rule to make target No'ycm_support_libs'. Stop.
However, I execute command : make ycm_core, succeed.There is no mistake. YCM normal operation in vim.

**Comment by vheon** [comment]
> In the ycm_build directory the Makefiles files generated and then Execute command: make ycm_support_libs, but had a error, the detail is: make: * * * rule to make target No'ycm_support_libs'. Stop. 
However, I execute command : make ycm_core, succeed.There is no mistake.

We don't have the `ycm_support_libs` rule anymore (and it has been a while) because we don't need any compiled binary on the client side (it was needed by the vim client for the `omnifunc` completer). Are you sure you are reading the latest doc? Where are you reading this?

>  YCM normal operation in vim.

This means that `ycmd` works fine, so it is either a configuration or env problem, or a problem with the Atom client.

**Comment by micbou** [comment]
I think the main issue here is that the Atom client should not display the Python traceback to the user but only the `Can't jump to definition or declaration` text.

About the error itself, there are multiple reasons for not being able to jump: cursor position is not valid, compilation errors in the current file, definition is not in the current translation unit, etc. Without the C++ code and the `.ycm_extra_conf.py` file, we can only guess.

**Comment by xuweitz** [comment]
Thank you for reminding me. I'll try this method.

**Comment by primitivorm** [comment]
I was have the same error with alt+y g, I installed https://atom.io/packages/goto and works fine for me.
right click->goto declaration

**Comment by micbou** [comment]
Let's close as an Atom client issue.
