### ISSUE TITLE
CXTranslationUnit_KeepGoing not available in clang 3.8.1

### ISSUE THREAD

**Issue by booooh** [Valloric/ycmd#654]
In the documentation you specify that the latest version of clang should be used, but you mention that clang 3.8.0 or newer should be OK.

However, it seems that 3.8.1 does not include the flag:
CXTranslationUnit_KeepGoing

which was added in issue #590 (I think).

Please either update the documentation, or enable this via a compilation flag...

P.S.
I chose clang 3.8.1 since my development work is on a machine with SLES11sp3, and this is the latest binary version available for that platform.

**Comment by Valloric** [comment]
Thanks for pointing this out.

@micbou Seems like this is biting us in the ass now. Weird that libclang would remove this flag...

@r4nt @d0k Would either of you know why was this flag removed in 3.8.1?

**Comment by micbou** [comment]
I think there is a misunderstanding here. This flag was never removed but introduced in Clang 3.9. We need to bump the Clang version requirement in the documentation. I am preparing a PR.

**Comment by booooh** [comment]
@micbou yes that's what I meant.

**Comment by micbou** [comment]
@booooh As mentioned in PR https://github.com/Valloric/YouCompleteMe/pull/2445, you should be able to compile against Clang 3.8.1 using the `-DEXTERNAL_LIBCLANG_PATH` flag.

**Comment by booooh** [comment]
ok, thanks - I may give that a try.

**Comment by Valloric** [comment]
@micbou Thanks for clarifying; there was indeed lots of misunderstanding here on my part. :D
