### ISSUE TITLE
AttributeError: 'module' object has no attribute 'OrderedDict'

### ISSUE THREAD

**Issue by haifengkao** [Valloric/ycmd#660]
I am following https://github.com/Valloric/ycmd/blob/master/TESTS.md to execute the test cases.
However, when I execute `./run_tests.py`, I got 
```
AttributeError: 'module' object has no attribute 'OrderedDict'
```
The vagrant intentionally installs python 2.6.6, but `flake8` uses `OrderedDict` which is not available until python 2.7.

I guess we need some patch for the `vagrant_bootstrap.sh`

**Comment by micbou** [comment]
You can disable `flake8` with the `--no-flake8` flag. This is what we do on Travis.

**Comment by haifengkao** [comment]
Why don't you upgrade the python to 2.7.11?
 `ycmd` and `flake8` are running fine with it.

**Comment by micbou** [comment]
Because `ycmd` supports Python 2.6. What we could do is update our `test_requirements.txt` file to use a working version of Flake8 on Python 2.6. This way we don't have to disable Flake8 for this version of Python on Vagrant and Travis. Reopening.

**Comment by puremourning** [comment]
Also, you can (should?) use pyenv to get a python 2.7 or python 3 setup in vagrant.
