### ISSUE TITLE
Add option to fall-back to identifier completion during parsing

### ISSUE THREAD

**Issue by r4nt** [Valloric/ycmd#67]
See:
https://github.com/abingham/emacs-ycmd/issues/121#issuecomment-67377618

**Comment by puremourning** [comment]
there is some ongoing talk about this over here: https://github.com/Valloric/YouCompleteMe/issues/1506

@r4nt I'd appreciate your input on the approach suggested. It _does_ involve an API change, but it would also cover this use case.

**Comment by r4nt** [comment]
Lots of good arguments for both approaches. I'm not sure what the right
approach is. Perhaps making c++ faster to parse *is* the right solution :)

**Comment by vheon** [comment]
Shouldn't this be resolved?

**Comment by puremourning** [comment]
Yup. Fixed by https://github.com/Valloric/ycmd/commit/74a62c3ee3911c5a703b22a1b1599336195eb39d
