### ISSUE TITLE
Javascript strings completion does not include the initial quote

### ISSUE THREAD

**Issue by arthurflachs** [Valloric/ycmd#671]
Autocompleting javascript string (including required modules) with YCM does not happen as expected in Vim. The same behavior should be met with other clients.

**Steps to reproduce**
* Enter the following : require('re<C-Space>
* Select 'react'
*Expected result:* require('react'
*Actual result:* require(''react'

*Solution to the problem*
The ternjs server includes the quote in the completions result. Therefore the first call to the omnifunc function should return the index of the quote, not the index of the fist alphabetic character.
The part to change to make this working is to include the quote in the javascript FILETYPE_TO_IDENTIFIER_REGEX here : [identifiers_utils.py](https://github.com/Valloric/ycmd/blob/4c6c66d7a6c494fef56976fa61e019bf00c211a6/ycmd/identifier_utils.py#L71)  

This solves the problem in this specific case in Vim, but I don't know if this might have unexpected side effects.

**Comment by puremourning** [comment]
Could you post your `.tern-project` file ?

I can't get tern to complete the paths in `require` in my testing.

**Comment by arthurflachs** [comment]
The node plugin needs to be enabled

```
{
  "plugins": {
    "node": {}
  }
}
```

**Comment by puremourning** [comment]
OK thanks, I can reproduce.

I suspect we should actually strip the `'` because i don't think `'` is actually valid in a javascript identifier (i.e. you can't have a variable named `'`)

**Comment by puremourning** [comment]
Steps to reproduce:

- `mkdir ~/tmp/js`
- create `~/tmp/js/.tern-project` with the following contents:

```json
{
  "plugins": {
    "node": {}
  }
}
```

- save/quit
- `vim test.js`
- insert `require( 're` and press `<ctrl+space>`
- select an item "`repl`"
- expect: `require( 'repl'`
- actual `require( ''repl'`

**Comment by bstaletic** [comment]
I'm not a javascript developer, so I am not quite sure my patch is sufficient, but it does solve the ssue described in the previous @puremourning's post.

Here's what I came up with:
```diff
diff --git a/ycmd/identifier_utils.py b/ycmd/identifier_utils.py
index 6f51fe6b..e64cf4a5 100644
--- a/ycmd/identifier_utils.py
+++ b/ycmd/identifier_utils.py
@@ -68,7 +68,7 @@ FILETYPE_TO_IDENTIFIER_REGEX = {
     # Spec:
     # http://www.ecma-international.org/ecma-262/6.0/#sec-names-and-keywords
     # Default identifier plus the dollar sign.
-    'javascript': re.compile( r"([^\W\d]|\$)[\w$]*", re.UNICODE ),
+    'javascript': re.compile( r"([^\W\d]|\$|')[\w$]*", re.UNICODE ),

     # Spec: http://www.w3.org/TR/CSS2/syndata.html#characters
     # Good summary: http://stackoverflow.com/a/449000/1672783
```
Is that all that is needed to fix the issue and not create a different problem somewhere else? If so I could submit a PR.

**Comment by puremourning** [comment]
Like i said above

> i don't think `'` is actually valid in a javascript identifier (i.e. you can't have a variable named `'`)

**Comment by bstaletic** [comment]
Would changing `r"([^\W\d]|\$)[\w$]*"` to `r"(([^\W\d]|\$)[\w$]*|'([^\W\d]|\$)[\w$]*')"` work?

This is essentially changing "default plus the dollar sign" to "default plus the dollar sign or the same, but surrounded with single quotes".

If not, would changing the order of the "or" operands make a difference?

**Comment by puremourning** [comment]
Changing the identifier regex is not the solution. It might work around this issue but causes many more serious ones.
