### ISSUE TITLE
Use identifier engine automatically, semantic manually

### ISSUE THREAD

**Issue by quicknir** [Valloric/ycmd#674]
I'd like to achieve this if possible. I don't want semantic to start automatically because, while reasonably quick, it's not fast enough to give a good experience while typing. I could use a different backend for automatic completion and ycmd for manual (note that is via emacs-ycmd & company), but then I don't get nice completion for my #includes; I have to keep hitting auto complete manually after every directory.

Is there any way to get non-semantic completions automatically, and semantic ones only when I ask for them? In other words, remove the semantic triggers . and -> (this is for C++).

**Comment by vheon** [comment]
Which client are you using? vim, emacs, Sublime Text etc?

**Comment by vheon** [comment]
If you're using Vim se https://github.com/Valloric/YouCompleteMe#the-gycm_auto_trigger-option. If you're not using vim you have to ask at the maintainer of the client you're using.

**Comment by quicknir** [comment]
I'm using emacs-ycmd. According to the description for auto trigger, it turns off the identifier based engine as well. I'd like the identifier engine to be on and to be used for everything, including after `.`/`->`, and only get semantic when I ask for it.

**Comment by quicknir** [comment]
It seems like despite the description, this does indeed work. Maybe the docs can be clarified?

**Comment by vheon** [comment]
The one that I showed is the setting for Vim. If you are using emacs-ycmd you have to ask over their repo.
