### ISSUE TITLE
Confusing error message when stating gVim

### ISSUE THREAD

**Issue by carlca** [Valloric/ycmd#694]
Windows 10 64 bit Insider Preview build 15007
gVim 8.0.69
Python 3.5
as part of the Anaconda suite (is this the problem?)

Hello, I have just completed the installation of YCM as per the Windows instructions. I assembled the various requisites and finally issued the 
`
python install.py --gocode-completer
`
command. After a hive of activity my machine finally settled down with 15 warnings but no errors. I decided that it might be worth trying to launch gVim. I should be so lucky. I got the following message:
`
YouCompleteMe unavailable: requires Vim compiled with Python 
(2.6+ or 3.3+) support
`
Here's the thing that really grinds my gears when faced with this type of debacle - it was compiled with Python 3.5. I guess I could install an earlier version of Python (as long as there is a way to select which version is being used), but I shouldn't have to. Python 3.5 has been around long enough.

What should my next steps be?

Thanks in advance

**Comment by puremourning** [comment]
https://github.com/Valloric/YouCompleteMe/issues/2509

Duplicate
