### ISSUE TITLE
Racerd not update to v0.3.3

### ISSUE THREAD

**Issue by james50428** [Valloric/ycmd#703]
My racerd are not update to v0.3.3
after v0.3.1 [this issue](https://github.com/jwilm/racerd/issues/60) were fixed
so now i can't compile racerd

any solution?

**Comment by james50428** [comment]
Sorry opened at the worng repo!

**Comment by james50428** [comment]
Update the problem is when i clone YCM it will also clone ycmd's older version which do not contain newer version of racerd please fix :)

**Comment by tqoitc** [comment]
I will submit a PR for this.

**Comment by micbou** [comment]
Fixed by PR https://github.com/Valloric/YouCompleteMe/pull/2531.
