### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 27: ordinal not in range(128)

### ISSUE THREAD

**Issue by piranna** [Valloric/ycmd#727]
I'm using the [you-complete-me Atom package](https://atom.io/packages/you-complete-me) and don't know why I'm getting the next error:

```python
'ascii' codec can't encode character u'\xf3' in position 27: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/dist-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 109, in wrapper
    return callback( *args, **kwargs )
  File "/usr/lib/ycmd/ycmd/../ycmd/hmac_plugin.py", line 72, in wrapper
    body = callback( *args, **kwargs )
  File "/usr/lib/ycmd/ycmd/../ycmd/handlers.py", line 191, in LoadExtraConfFile
    extra_conf_store.Load( request_data[ 'filepath' ], force = True )
  File "/usr/lib/ycmd/ycmd/../ycmd/extra_conf_store.py", line 174, in Load
    module = LoadPythonSource( _RandomName(), module_file )
  File "/usr/lib/ycmd/ycmd/../ycmd/utils.py", line 389, in LoadPythonSource
    return imp.load_source( name, pathname )
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 27: ordinal not in range(128)
```

It's a vanilla installation, so this would not be a problem. I've also added `# -*- coding: utf-8 -*-` to the begin of the `.ycm_extra_config.py` file and didn't get any progress. Any suggestion what could be happening?

**Comment by vheon** [comment]
Do you have any strange char in the path where `.ycm_extra_conf.py` is saved?

**Comment by piranna** [comment]
You are right, I have an accent. The full path is `/home/piranna/Trabajo/Telefónica I+D/cdn-node`. Maybe should `ycmd` allow Unicode strings for the paths?

**Comment by vheon** [comment]
@micbou didn't you had a branch that fixed this?

**Comment by micbou** [comment]
@vheon I am currently working on it. I'll send a PR soon.

**Comment by micbou** [comment]
@piranna Could you try the changes in PR #728? Should fix the issue.

**Comment by piranna** [comment]
Cool, thank you! :-) I was using the `ycmd` Ubuntu package, but I'll change it for latest code to have this patch.
