### ISSUE TITLE
How to determine why GoToDefinition is not working?

### ISSUE THREAD

**Issue by abingham** [Valloric/ycmd#73]
I'm trying to understand why I can't make "GoToDefinition" work with the clang completer. The general "GoTo" works fine, but it only ever seems to take me to a declaration. I'd like to be able to jump to a definition. Should I expect this to work? If so, how can I figure out what I'm doing wrong?

**Comment by Valloric** [comment]
> Ah, I see in the YouCompleteMe documentation that GoToDefinition only works for definitions in the same translation unit. That's almost certainly explains what's going on here. If that sounds correct to you, then go ahead and close this.

That's it. To make GoToDef work across TUs, you'd have to build an index of all the source code in the project (something like what ctags does). It would be a ton of work.
