### ISSUE TITLE
High memory usage for ycm server process under different clients

### ISSUE THREAD

**Issue by agauniyal** [Valloric/ycmd#740]
Hi, I use both vim as well as vscode client of ycm plugin and for some specific sources, I'm seeing a memory usage difference of about 5x times. I can email the files if someone wants to take a look at them, but can't paste them here. The vim plugin works fine and takes upto 10% of my system memory (which is expected since it uses Boost Geometry) while the vscode plugin takes upto 50-55% of my system memory for same single source file. Please note that the plugin process of vscode itself isn't taking that much memory, it's the ycm server process that was launched by it that takes 50-55% memory.

Please read the relevant discussion here too - https://github.com/richard1122/vscode-youcompleteme/issues/32

Since the plugin developer asked, I opened an issue here too.

**Comment by vheon** [comment]
One possibility is that vscode is calling ycmd APIs more than needed. To check this what we could do is:

- create a sample.cpp with the code you're seeing this problem
- open this in vim and make a set of steps.
- save the ycmd logs
- do the same with vscode
- compare the calls to the ycmd api and check where they differ

**Comment by agauniyal** [comment]
@vheon where are ycmd logs stored for vim plugin?

**Comment by bstaletic** [comment]
@agauniyal Somewhere in /tmp. While in Vim type `:YcmToggleLogs` to see the log paths. There is also an option for YCM you need to enable to make it keep the logs after exiting Vim called `g:ycm_keep_logfiles`.

**Comment by vheon** [comment]
@agauniyal in [CONTRIBUTING.md](https://github.com/Valloric/YouCompleteMe/blob/master/CONTRIBUTING.md) you'll find all the info you need to keep and find the log files 👍

**Comment by micbou** [comment]
No answer from OP. Closing.
