### ISSUE TITLE
Ycmd server is not running. Can’t send ‘semantic_completion_available’ request! 

### ISSUE THREAD

**Issue by asdyjd** [Valloric/ycmd#768]
ENV:
win10 x64, emacs 25, python3.6.1 64bit(anaconda), and latest ycmd successfuly built under visual studio 2017.
problem:
In emacs c++-mode, whatevet I type, it hints me ```Ycmd server is not running. Can’t send ‘semantic_completion_available’ request!```
*ycmd-buffer* show ```2017-06-01 20:21:29,995 - DEBUG - Global extra conf not loaded or no function YcmCorePreload```
And it's set like this:
```
(setq ycmd-global-config "D:/emacs/ycmd/cpp/ycm/.ycm_extra_conf.py")
(setq ycmd-server-command '("python" "D:/emacs/ycmd/ycmd"))
```

**Comment by puremourning** [comment]
Would you mind please raising hthis with the emacs-ycmd guys in the first instance? They may refer you back here with more info of course, but they are best to diagnose issues that manifest in emacs. for now closing ycmd issue. If you get referred back, just raise a new one (and include the ycmd log file too please :))
