### ISSUE TITLE
Add endpoint for listing languages that support semantic completion

### ISSUE THREAD

**Issue by abingham** [Valloric/ycmd#77]
Currently the emacs-ycmd client hard codes a list of languages for which ycmd supports semantic completion. It would be a bit more future-proof if the client could request that list from ycmd whenever the server is started.

This is far from critical, just a nice-to-have.

**Comment by Valloric** [comment]
Agreed, we should have this.

**Comment by micbou** [comment]
It's better to rely on [the `/semantic_completer_available` endpoint](https://valloric.github.io/ycmd/#path--semantic_completer_available) than hard coding the list of languages supported by ycmd. [This is what the YCM client does](https://github.com/Valloric/YouCompleteMe/blob/c25e449f4e72667aca3d18d8bfccd7b289b2e9a1/python/ycm/youcompleteme.py#L365-L376) (the result of the request is then cached). Adding an endpoint returning all the supported languages doesn't seem useful as a client is unlikely to use all of them during a session. Closing as won't be implemented.
