### ISSUE TITLE
MAC:no LC_RPATH load command with path: @executable_path/../lib

### ISSUE THREAD

**Issue by GumpCode** [Valloric/ycmd#776]
Hi, I try to build ycmd in my mac pro, but there was an error

macOS SIERRA

`error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: no LC_RPATH load command with path: @executable_path/../lib found in: /path/to/.vim/bundle/YouCompleteMe/third_party/ycmd/libclang.dylib (for architecture x86_64), required for specified option "-delete_rpath @executable_path/../lib"`

I found this _https://github.com/Valloric/ycmd/pull/406_
but it is a warning not an error

thank you

**Comment by micbou** [comment]
Are you using the latest version of ycmd? The command `install_name_tool -delete_rpath` was removed in commit https://github.com/Valloric/ycmd/commit/907ba68a0867a76d4cb168c22821a0586f254e72.

**Comment by GumpCode** [comment]
@micbou I have checked it, it solved, thank you!
