### ISSUE TITLE
Unable to use -include-pch after updating.

### ISSUE THREAD

**Issue by tnielsen** [Valloric/ycmd#782]
I've been using ycm with precompiled headers, but after updating it's no longer working.  I have compiler_commands.json setup, and when I have the flags `['-include-pch', '/home/.../precomp.h.pch']`, they are getting corrupted.  From the debug log I see it pass in: `'-include/home/my/working/directory/-pch'`.

It looks like what's happening is that in completers/cpp/flags.py, `_MakeRelativePathsInFlagsAbsolute` is looking at the flags with `startswith`.  This is finding the -include, and assuming that -pch is a relative file that needs to be modified to be absolute.

I have a local workaround, by modifying the line from:
`if flag.startswith( path_flag ):`
to:
`if flag != '-include-pch' and flag.startswith( path_flag ):`
This makes my setup work again, but is probably not a very reasonable solution.

**Comment by micbou** [comment]
Thanks for reporting the issue.  This should be fixed by PR #783. The solution consists to check the `-include-pch` flag before the `-include` one.
