### ISSUE TITLE
autocomplete missing in python for "from x import"

### ISSUE THREAD

**Issue by jogo** [Valloric/ycmd#788]
Based on testing with YouCompleteMe, autocomplete works for things like `import os.` but not for `from os import `.

jedi supports autocomplete for things like `from collections import ` but ycmd doesn't trigger a lookup for the `from ... import` syntax.

```python
>>> len(jedi.Script('from collections import ').completions())
44
```

Can autocomplete be added for this case by adding a new default python trigger in https://github.com/Valloric/ycmd/blob/master/ycmd/completers/completer_utils.py#L188 ?

**Comment by puremourning** [comment]
When using the YouCompleteMe client, you can force semantic completion with `<Ctrl-Space>`

![ycm-import-python](https://user-images.githubusercontent.com/10584846/27773964-6c359c78-5f7e-11e7-942b-637af79ac9b4.gif)

So this does work. I think you're asking for automatic triggering in that case, but it's a little niche.

You can [customise the triggers in YouCompleteMe](https://github.com/Valloric/YouCompleteMe#the-gycm_semantic_triggers-option).

**Comment by jogo** [comment]
Yes I was asking for automatic triggering by default. But adding a line to my config file works too.

I added `let g:ycm_semantic_triggers = {'python': ['re!from\s+\S+\s+import\s']}` to my `.vimrc` file and looks like it's working nicely.

Thank you! YouCompleteMe incredibly useful.
