### ISSUE TITLE
Couldn't create name generator Visual Studio 15

### ISSUE THREAD

**Issue by moyotar** [Valloric/ycmd#794]
D:\app\emacs\extraBin\ycmd>build.py --all
Searching Python 2.7 libraries...
Found Python library: D:\app\emacs\extraBin\Python27\libs\python27.lib
Found Python headers folder: D:\app\emacs\extraBin\Python27\include
CMake Error: Could not create named generator Visual Studio 15

Generators
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Visual Studio 8 2005 [arch]  = Generates Visual Studio 2005 project files.
                                 Optional [arch] can be "Win64".
  Visual Studio 7 .NET 2003    = Deprecated.  Generates Visual Studio .NET
                                 2003 project files.
  Borland Makefiles            = Generates Borland makefiles.
  NMake Makefiles              = Generates NMake makefiles.
  NMake Makefiles JOM          = Generates JOM makefiles.
  Green Hills MULTI            = Generates Green Hills MULTI files
                                 (experimental, work-in-progress).
  MSYS Makefiles               = Generates MSYS makefiles.
  MinGW Makefiles              = Generates a make file for use with
                                 mingw32-make.
  Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Watcom WMake                 = Generates Watcom WMake makefiles.
  CodeBlocks - MinGW Makefiles = Generates CodeBlocks project files.
  CodeBlocks - NMake Makefiles = Generates CodeBlocks project files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - MinGW Makefiles   = Generates CodeLite project files.
  CodeLite - NMake Makefiles   = Generates CodeLite project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Eclipse CDT4 - MinGW Makefiles
                               = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - NMake Makefiles
                               = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
  Kate - MinGW Makefiles       = Generates Kate project files.
  Kate - NMake Makefiles       = Generates Kate project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Sublime Text 2 - MinGW Makefiles
                               = Generates Sublime Text 2 project files.
  Sublime Text 2 - NMake Makefiles
                               = Generates Sublime Text 2 project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.

ERROR: the build failed.

NOTE: it is *highly* unlikely that this is a bug but rather
that this is a problem with the configuration of your system
or a missing dependency. Please carefully read CONTRIBUTING.md
and if you're sure that it is a bug, please raise an issue on the
issue tracker, including the entire output of this script
and the invocation line used to run it.

**Comment by moyotar** [comment]
I have installed Visual Studio 2015.

**Comment by micbou** [comment]
You need a version of CMake that supports the `Visual Studio 15` generator. Which version are you using (`cmake --version`)? You need at least CMake 3.7. See https://github.com/Valloric/ycmd/issues/736.

**Comment by moyotar** [comment]
D:\app\emacs\extraBin\ycmd>build.py --all
Searching Python 2.7 libraries...
Found Python library: D:\app\emacs\extraBin\Python27\libs\python27.lib
Found Python headers folder: D:\app\emacs\extraBin\Python27\include
CMake Error at CMakeLists.txt:26 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:





-- Configuring incomplete, errors occurred!
See also "C:/Users/gzzhongzuolv/AppData/Local/Temp/ycm_build_kcfboa/CMakeFiles/CMakeOutput.log".
ERROR: the build failed.

NOTE: it is *highly* unlikely that this is a bug but rather
that this is a problem with the configuration of your system
or a missing dependency. Please carefully read CONTRIBUTING.md
and if you're sure that it is a bug, please raise an issue on the
issue tracker, including the entire output of this script
and the invocation line used to run it.

**Comment by moyotar** [comment]
After I updated `cmake` version to 3.9. I got errors above.

**Comment by micbou** [comment]
Did you select **Desktop development with C++** in **Workloads** when installing Visual Studio 2017?

**Comment by moyotar** [comment]
I forgot it.

**Comment by moyotar** [comment]
I forget whether if I chose.

**Comment by micbou** [comment]
Run again the Visual Studio installer (you can download it [here](https://www.visualstudio.com/downloads/) in case you removed it), click on the button **Modify** and check if **Desktop development with C++** is selected in **Workloads**.

**Comment by moyotar** [comment]
![image](https://user-images.githubusercontent.com/22092607/28263399-2e542c5c-6b19-11e7-984c-b2edf38c9ea0.png)

**Comment by micbou** [comment]
I see. You don't have Visual Studio 15 (also named Visual Studio 2017) but Visual Studio 14 (2015). In that case, you need to select **Visual C++** in your screenshot then click on **UPDATE**. Once that's done, run the build script by specifying the right version of Visual Studio with the `--msvc` option:
```
build.py --all --msvc 14
```

**Comment by moyotar** [comment]
![image](https://user-images.githubusercontent.com/22092607/28264997-2bfdae5e-6b20-11e7-8894-809fd2faf4b5.png)

**Comment by moyotar** [comment]
It works. Thanks!

**Comment by MonikaPa** [comment]
@micbou  I am trying to install cucumber .. I am getting the same error..
Configuration for Visual studio in my PC is as attached. 
![image](https://user-images.githubusercontent.com/43199205/45408138-1c843000-b689-11e8-941f-5b7174b86d2d.png)

I am getting this error

CMake Error: Could not create named generator Visual Studio 14″ -DCUKE_ENABLE_EXAMPLES=on -DBOOST_ROOT=c:\Boost...

Generators
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.

Please suggest.

**Comment by bstaletic** [comment]
> Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
Optional [arch] can be "Win64" or "ARM".

According to your cmake output, the generator you want is `"Visual Studio 14 2015"` or `"Visual Studio 14 2015 Win64"`.

**Comment by bstaletic** [comment]
"Doesn't work" is not a useful diagnostic. Post the command line you used and the complete cmake output you got. Also, this is a question for https://gitter.im/Valloric/YouCompleteMe, not a bug tracker.

**Comment by MonikaPa** [comment]
I used "cmake -E chdir vsprj cmake -G "Visual Studio 14 2015 Win64″ -DCUKE_ENABLE_EXAMPLES=on -DBOOST_ROOT=c:\Boost..." this command.
Got this output
C:\Cucumber\cucumber-cpp>cmake -E chdir vsprj cmake -G "Visual Studio 14 2015 [Win64]″
CMake Error: Could not create named generator Visual Studio 14 2015 [Win64]″

Generators
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.
                                 Optional [arch] can be "Win64" or "IA64".
  Borland Makefiles            = Generates Borland makefiles.
  NMake Makefiles              = Generates NMake makefiles.
  NMake Makefiles JOM          = Generates JOM makefiles.
  Green Hills MULTI            = Generates Green Hills MULTI files
                                 (experimental, work-in-progress).
  MSYS Makefiles               = Generates MSYS makefiles.
  MinGW Makefiles              = Generates a make file for use with
                                 mingw32-make.
  Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  Watcom WMake                 = Generates Watcom WMake makefiles.
  CodeBlocks - MinGW Makefiles = Generates CodeBlocks project files.
  CodeBlocks - NMake Makefiles = Generates CodeBlocks project files.
  CodeBlocks - NMake Makefiles JOM
                               = Generates CodeBlocks project files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - MinGW Makefiles   = Generates CodeLite project files.
  CodeLite - NMake Makefiles   = Generates CodeLite project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Sublime Text 2 - MinGW Makefiles
                               = Generates Sublime Text 2 project files.
  Sublime Text 2 - NMake Makefiles
                               = Generates Sublime Text 2 project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.
  Kate - MinGW Makefiles       = Generates Kate project files.
  Kate - NMake Makefiles       = Generates Kate project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Eclipse CDT4 - NMake Makefiles
                               = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - MinGW Makefiles
                               = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.

**Comment by bstaletic** [comment]
Those brackets are what's causing the error.  It's `Win64`, not `[Win64]`.

**Comment by puremourning** [comment]
> cmake -E chdir vsprj cmake -G "Visual Studio 14 2015 Win64″ -DCUKE_ENABLE_EXAMPLES=on -DBOOST_ROOT=c:\Boost..." 

What does this have rondo with YCM?

**Comment by MonikaPa** [comment]
As you can see, I used this command , I used "cmake -E chdir vsprj cmake -G "Visual Studio 14 2015 Win64″ -DCUKE_ENABLE_EXAMPLES=on -DBOOST_ROOT=c:\Boost..." this command. It is not having any brackets with [Win64].

**Comment by puremourning** [comment]
I still don’t see what this has to do with YCM. Unless that is addressed I am inclined to lock this thread.

**Comment by zie-1** [comment]
![screenshot 2](https://user-images.githubusercontent.com/36835435/47331993-817f6c80-d6b0-11e8-8e87-d1794b3a4897.png)

hi guys! I am hoping that you can help me with my problem. So, I am following the instruction with this screenshot and I encounter a problem or is it a bug? Anyway, So I am using cmd instead of powershell so I change the backticks (`) to carets (^) and it works well except when i input these commands:

cmake -G "Visual Studio 14 2015 Win64" `
-DJPEG_INCLUDE_DIR=..\dlib\external\libjpeg `
-DJPEG_LIBRARY=..\dlib\external\libjpeg `
-DPNG_PNG_INCLUDE_DIR=..\dlib\external\libpng `
-DPNG_LIBRARY_RELEASE=..\dlib\external\libpng `
-DZLIB_INCLUDE_DIR=..\dlib\external\zlib `
-DZLIB_LIBRARY_RELEASE=..\dlib\external\zlib `
-DCMAKE_INSTALL_PREFIX=install ..

it gives me an error that " CMake Error: Could not create named generator Visual Studio 14 2015 Win64-DJPEG_INCLUDE_DIR=..\dlib\external\libjpeg-DJPEG_LIBRARY=..\dlib\external\libjpeg-DPNG_PNG_INCLUDE_DIR=..\dlib\external\libpng-DPNG_LIBRARY_RELEASE=..\dlib\external\libpng-DZLIB_INCLUDE_DIR=..\dlib\external\zlib-DZLIB_LIBRARY_RELEASE=..\dlib\external\zlib-DCMAKE_INSTALL_PREFIX=install " and i do not really understand since I'm only a beginner..  What should I do? Thankyou in advance for helping me.

**Comment by zie-1** [comment]
![screenshot 3](https://user-images.githubusercontent.com/36835435/47332448-eb4c4600-d6b1-11e8-9716-8984d35b3292.png)
![screenshot 4](https://user-images.githubusercontent.com/36835435/47332449-eb4c4600-d6b1-11e8-9b04-966e05bdda7f.png)
and this is the whole error I got.. :(
