### ISSUE TITLE
Problem in completion of c#.

### ISSUE THREAD

**Issue by moyotar** [Valloric/ycmd#797]
> OS: win10
> Emacs: 24.5.1

When editing a `c#` file, I got this from `*ycmd-server*`.

RuntimeError: OmniSharp server binary not found at D:\app\emacs\extraBin\ycmd\third_party\OmniSharpServer\OmniSharp\bin\Release\OmniSharp.exe. Did you compile it? You can do so by running "./install.py --omnisharp-completer".

And I couldn't find `install.py` to install `OmniSharp`.

**Comment by micbou** [comment]
Use the `build.py` script:
```
build.py --omnisharp-completer
```

**Comment by moyotar** [comment]
![image](https://user-images.githubusercontent.com/22092607/28358014-e0c4054c-6c9f-11e7-91f4-ee3fb5faf8b9.png)
How to solve it?

**Comment by puremourning** [comment]
The YCM docs explain the dependencies you need to install. Just replace install.py with build.py when building ycmd directly.

**Comment by micbou** [comment]
You need to [add MSBuild to your PATH](https://stackoverflow.com/a/12608705).

**Comment by moyotar** [comment]
@micbou Yes! Thanks a lot.
