### ISSUE TITLE
build.py on Linux via pyenv virtualenv broken in ff770b4 

### ISSUE THREAD

**Issue by aldanor** [Valloric/ycmd#798]
I'm trying to build YCM on Ubuntu with pyenv-installed Python 3 (built with `--enable-shared`), in a separate virtualenv (so `libpython3.so` is not located in the prefix directory, but in the parent lib directory).

However, it complains that it can't find dynamic libraries. I've checked, it used to work fine up until and including commit 5ffe1bfdc9c026d289081e9442f07ab03021189f, but is then broken starting from commit ff770b4f47e793a7c7e839f41861e564ef6a7caf ("Search Python library in lib64").

The reason for that being is that both `sys.prefix` and `sys.base_prefix` point to the virtualenv's lib directory, while `distutils.sysconfig.get_python_lib(standard_lib=1)` (the one which was removed in that commit) points to the parent lib directory where the .so file is located. Could it be please added back? (and the submodule bumped in YCM)

**Comment by micbou** [comment]
Thanks for the report. This should be fixed by PR #799. Could you try it?
