### ISSUE TITLE
How to auto complete with only pyd file but without .py file?

### ISSUE THREAD

**Issue by moyotar** [Valloric/ycmd#806]

**Comment by vheon** [comment]
I'm not sure if [jedi](https://github.com/davidhalter/jedi) can, but if it can't we can't do it either.

**Comment by micbou** [comment]
This can be done by adding the folders containing the `.pyd` files to the `PYTHONPATH` environment variable. However, I think it would be more convenient if there was a way to manipulate Jedi search path  (`sys.path`) at a project level. It could be through the `.ycm_extra_conf.py` file similarly to what was suggested in PR https://github.com/Valloric/ycmd/pull/425:
```python
def PythonSettings( **kwargs ):
  return {    
    'additional_search_paths': [ ... ] # List of paths.  
  }
```

**Comment by vheon** [comment]
@micbou you had a prototype for the `.ycm_extra_conf.py` right? how about we discuss it further in a PR? 😜

**Comment by moyotar** [comment]
@micbou Thanks a lot! How about a `*.dll` file

**Comment by micbou** [comment]
A `.dll` file? Can you give an example?

**Comment by moyotar** [comment]
There's a `.dll` file written by `c++`. Now to import it in `python`, is there a way to complete it's `api`

**Comment by micbou** [comment]
How are you importing the `.dll` in Python?

**Comment by moyotar** [comment]
Use [ctypes](https://docs.python.org/2/library/ctypes.html?highlight=ctypes#module-ctypes) module.

**Comment by micbou** [comment]
I've built the library `hello.dll` from the following source:
```c++
#include <iostream>

extern "C" void __declspec(dllexport) hello();

void hello() {
    std::cout << "Hello world!" << std::endl;
} 
```
then tried to complete it by loading the library with `ctypes` through the Jedi API:
```python
import jedi

completions = jedi.Script( """
from ctypes import cdll
cdll.LoadLibrary('hello.dll').""" ).completions()

for completion in completions:
  print( completion )
```
Jedi returns a bunch of candidates but not the `hello` function so I guess that's a Jedi limitation.

**Comment by davidhalter** [comment]
@vheon You can probably close this one. Discussions should be in davidhalter/jedi#949.

It's definitely not a ycmd issue, it's 100% Jedi.

**Comment by puremourning** [comment]
Ok thanks!
