### ISSUE TITLE
Tags for custom languages?

### ISSUE THREAD

**Issue by Skiouros** [Valloric/ycmd#809]
Unless I'm doing something wrong, ycmd doesn't seem to be adding tag completion to my output for moonscript. I'm using  [emacs-ycmd](https://github.com/abingham/emacs-ycmd) for the completion. I'm generating the tag file using `--fields=+l` but it doesn't want to work. It works fine with lua, so I'm not sure what else I need to do. 

This is the generated tag file:
```!_TAG_FILE_FORMAT       2       /extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED       1       /0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR    Darren Hiebert  /dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME      Exuberant Ctags //
!_TAG_PROGRAM_URL       http://ctags.sourceforge.net    /official site/
!_TAG_PROGRAM_VERSION   5.9~svn20110310 //
API     test.moon     /^        class TEST $/;"       c       language:moonscript
DELETE  test.moon     /^        DELETE:  =>$/;"   m       language:moonscript

**Comment by micbou** [comment]
Thanks to PR #810, ycmd now supports custom languages from tags. However, I think that some changes in emacs-ycmd are required to take advantage of that. You'll need to recompile ycmd too.
