### ISSUE TITLE
sha256 value mismatching(file——./third_party/ycmd/clang_archives/clang+llvm-4.0.1-x86_64-apple-darwin.tar.xz)

### ISSUE THREAD

**Issue by zuohai0** [Valloric/ycmd#813]
sha256 value
CMakeLists.txt-line 38: 5f697801a46239c04251730b7ccccd3ebbacb9043ad381a061ae6812409e9eae
actual：e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

It caused installation failed(I modified CMakeLists.txt , and succeeded , but now I worry about its security  a little) , please have it examined。

Thanks！

**Comment by Valloric** [comment]
If you're in China, this is likely the GFW messing with your downloads. Nothing we can do about it.
