### ISSUE TITLE
Allow getting hmac_secret from a command rather than a file

### ISSUE THREAD

**Issue by diamond-lizard** [Valloric/ycmd#828]
It would be great if the hmac_secret could be read from the stdout of a command rather than from a file.  That way the user would not have to take any special precautions for storing the ycmd settings file, and could rely on a tool like [pass](https://www.passwordstore.org/) to securely store and retrieve the secret.

**Comment by micbou** [comment]
Sorry but this doesn't seem worth implementing (and maintaining) especially since the only precaution you need with the options file is to create it with permissions 600.
