### ISSUE TITLE
Error merging unrelated history

### ISSUE THREAD

**Issue by duytrung** [Valloric/ycmd#836]
Hi,

I have the following error running "PlugUpdate" with neovim and "vim plug" on windows 10, for "ycmd":

![image](https://user-images.githubusercontent.com/2046672/30541340-215375a8-9cba-11e7-93fd-7ce0509fff31.png)

Please tell me how to fix this.

Thanks

TN

**Comment by puremourning** [comment]
That gives us _nothing_ to go on.

Here's a start: what is the output of the following commands in your 'ycmd' directory. It should be under `third_party/ycmd` within your `YouCompleteMe` directory created by your plugin manager:

* `git status`
* `git remote -v`
* `git pull`

What is the vim-plug configuration you are using for YouCompleteMe?

**Comment by micbou** [comment]
No answer. Closing.
