### ISSUE TITLE
Add a PHP completer

### ISSUE THREAD

**Issue by cweagans** [Valloric/ycmd#84]
CodeIntel, the code completion engine from Komodo Edit and Komodo IDE, supports completing PHP (and some other languages too). There's already a Sublime Text plugin that uses it, and it includes binaries for the native components for Windows, Mac, and Linux.

The new version of CodeIntel should be coming out soon (Komodo IDE is in beta), and when it does, it will also include Go support.

The Sublime Text plugin with the included binaries and such can be found here: https://github.com/SublimeCodeIntel/SublimeCodeIntel. Basically, ignore everything in the root of the repo except the "arch" and "libs" directories. I'd be willing to maintain a fork of this repository that's just the CodeIntel part if that would make it more interesting to include in YCMD!

**Comment by oblitum** [comment]
@cweagans Are you going to create some implementation proposal for a PHP semantic completer or just fork that repository?

**Comment by cweagans** [comment]
My Python skills aren't that great, as I'm a PHP developer (hence the desire for PHP autocompletion). The builds of CodeIntel with the Sublime Text plugin are all automated, so I'm happy to maintain a repo that has only CodeIntel and the platform-specific binaries if somebody else wants to integrate it with ycmd. Eventually, I might get around to learning Python, but it's going to be a while if it happens at all. I could also contribute financially a bit if that would incentivize work on this.

**Comment by cweagans** [comment]
Actually, this is even easier than I thought. We don't need CodeIntel. HHVM has built-in autocomplete functionality. See https://github.com/hhvm/vim-hack/blob/master/autoload/hackcomplete.vim#L33 for an implementation example. I just gave it a try and it's really solid. Basically just call "hh_client --auto-complete --json" and pass in the buffer and it'll do it's thing and give you back your suggestions.

**Comment by oblitum** [comment]
@cweagans that's nice, you should look whether it provides a library interface for code-completion instead of just a command-line interface. It turn things much faster and easy to handle internally.

**Comment by oblitum** [comment]
@cweagans starting a process for each and every completion is expensive and wasteful. Not a good design at all.

**Comment by cweagans** [comment]
No, it's not great as it is right now. However, hh_client (as you can probably guess) is a client to hh_server, which is what's doing all the heavy lifting. I bet it wouldn't be too difficult to just write some Python that connects directly to hh_server to get the autocomplete suggestions.

**Comment by oblitum** [comment]
@cweagans it's good to know about alternatives but I find hard that current mantainers are going to implement a PHP completer, or any, just based on a random request. Ideally contributions of this size comes through a pull-request process.

**Comment by vheon** [comment]
Speaking of alternatives: @Valloric is it handle in any way the possibility to have multiple semantic engine for a particular language and have the user specify which one they want? For example here for PHP we have more than one solution: hhvm, CodeIntel or eclim for what matters. If we don't support the user choosing the one he wants, who decides which engine is the best one?

**Comment by Valloric** [comment]
@vheon Eclim isn't really a semantic engine in YCM; we can talk to it through the omnifunc though, but I've always considered that a massive hack.

For a "real" semantic engine, I'd recommend going with either CodeIntel or HHVM. The idea is to have _one_ engine that works for everyone, like we have with libclang, Jedi and OmniSharp. I'm against the idea of supporting multiple engines; that just sounds like a massive hassle for little benefit.

**Comment by cweagans** [comment]
Personally, I'd lean toward HHVM. I've been testing the autocompletion and HHVM is by far the best of the three. Plus, you also get support for the Hack language.

**Comment by Valloric** [comment]
@cweagans Thanks for sharing your experience! HHVM sounds like a fine choice.

I personally don't use PHP and don't have time to write a semantic completer that connects HHVM to ycmd, but it really shouldn't be difficult to do. For instance, [this is the entirety of the Python semantic completer that connects to Jedi](https://github.com/Valloric/ycmd/blob/master/ycmd/completers/python/jedi_completer.py).

**Comment by cweagans** [comment]
Okay, so I did some further testing, and it looks like HHVM has a hard time with autocompleting regular PHP. It works great for Hack, though, so that might be a good option in the future.

Since I'm having a hard time finding any good autocomplete providers for PHP, I decided to write one. It's over at https://github.com/cweagans/theforce. It's definitely a work in progress, a little slow, and pretty clunky, but I'm hoping to have it in a workable state by the beginning of March. Not sure how realistic that is, but that's my goal. When it's at that stage, I'll be working on a completer for ycmd.

**Comment by Valloric** [comment]
@cweagans Thanks for working on that! The best advice I can give you is to make your semantic engine a library, and then wrap that library with a REST+JSON server (so like OmniSharp, Tern.js etc). After having integrated several semantic engines into ycmd, the approach I described is the most flexible and maintainable.

**Comment by cweagans** [comment]
Closing in favor of #96. I'll open a separate issue for adding Hack support via hhvm.
