### ISSUE TITLE
Xcode 9 Support

### ISSUE THREAD

**Issue by rbit** [Valloric/ycmd#844]
Xcode 9 modifies system header include paths. ycmd/completers/cpp/flags.py no longer produces a proper system include path sequence on systems that have upgraded to/installed Xcode 9.

On my system, `clang -v -E -x c++ -` produces the following:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1,
/usr/local/include,
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include,
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include,
/usr/include,
/System/Library/Frameworks,
/Library/Frameworks
```

**Comment by mellery451** [comment]
cpp completion is completely broken for my on my system with the latest XCode installed (apple-clang 9.0.0). All my compilation units fail to find stdlib headers/symbols when YCM tries to build them. On the other hand, the CU's build just fine under the actual XCode clang compiler. Strange.
