### ISSUE TITLE
start ycmd automatically without vim

### ISSUE THREAD

**Issue by iamkarlson** [Valloric/ycmd#845]
ycmd server is starting quite long on my machine. is it any way to run this server with system and then just "connect" to already started instance?

**Comment by micbou** [comment]
No, ycmd is not designed to be started without a client. How long does it take on your machine? It takes about ~220ms on mine. You can measure the startup time by running the `startup.py` script in [this branch](https://github.com/micbou/ycmd/tree/profiling-startup).

**Comment by micbou** [comment]
It would have been interesting to have some measurements on startup time. Though, I would be surprised if it took more than a few seconds.
