### ISSUE TITLE
Can't get semantic completion in c++ file.

### ISSUE THREAD

**Issue by moyotar** [Valloric/ycmd#846]
For more detail [here](https://github.com/abingham/emacs-ycmd/issues/447)

**Comment by bstaletic** [comment]
Let's make things clear first. Ycmd downloads a precompiled `libclang.so` unless you pass `--system-libclang` to the `build.py` script. So if you've built ycmd with `./build.py --clang-completer`, you are using whatever version of libclang ycmd downloaded, not your system libclang.

Now libclang 4.0 had problems on Windows. Asserts were all too easy to fail for whatever reason. If you are on Windows kindly ask the maintainer of the emacs-ycmd to update the ycmd dependency.

**Comment by ptrv** [comment]
emacs-ycmd does not have ycmd as submodule like YouCompleteMe. The user has to update ycmd him/herself

**Comment by bstaletic** [comment]
@moyotar Can you try building the latest ycmd and trying it inside emacs?
Even though I am fairly certain it's just libclang misbehaving, it would be nice to have it either confirmed or disproved.

**Comment by moyotar** [comment]
It works. Thanks a lot!
