### ISSUE TITLE
Using TypeScript for filetype javascript

### ISSUE THREAD

**Issue by maximus8891** [Valloric/ycmd#847]
Method [PathToFiletypeCompleterPluginLoader](https://github.com/Valloric/ycmd/blob/master/ycmd/completers/completer_utils.py#L162) searches for completers for a given filetype by their folder names. This way you can't have several completers handling one filetype.

I discovered this while I was looking for ways to apply the TypeScript completer for javascript files abandoning Tern altogether (it does not support class parameters).

Since each completer has method `SupportedFiletypes`, I see it as a better place to test if a completer can be used for a filetype. I would have to extend `[ 'typescript' ]` to `['typescript', 'javascript']`.  Of course, you wouldn't want to instantiate each completer to do this check. It makes more sense to make this method static.

**Comment by bstaletic** [comment]
> This way you can't have several completers handling one filetype.

The thing is, we don't want to support more then one completer per filetype.  It would be a big maintainance burden.

What we do want, though, is having the best available completer for a certain filetype. So even though we won't be making the suggested change, I think this is a good opportunity to discuss if we should use TSserver for javascript and abandon Tern.

Let me ask the first question. Is there anything TSserver does worse than Tern?

**Comment by maximus8891** [comment]
Tern does not support class properties: https://babeljs.io/docs/plugins/transform-class-properties/. They are in-built in Typescript.

For me TSserver required no config, unlike Tern, which wanted for some reason to have .tern-project file. I found it hard to find docs and examples for Tern.

With my js project setup TSserver found definitions in various files, while Tern could not handle it.

These points might sound a bit random, but I had a better experience with TS.

**Comment by micbou** [comment]
I created [a branch that enables TSServer for JS files](https://github.com/micbou/YouCompleteMe/tree/tsserver-javascript) so that we can easily compare both engines ([TSServer](https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-(tsserver)) and [Tern](http://ternjs.net/)). Feel free to try it and report back.

An obvious advantage for TSServer is that it has built-in diagnostics while Tern doesn't (there is [a lint plugin for Tern](https://github.com/angelozerr/tern-lint) but it doesn't seem to be maintained).

**Comment by maximus8891** [comment]
Thanks @micbou, I'll give it a whirl.
I also managed to make it work by copying the content of typescript folder into the javascript folder.

**Comment by puremourning** [comment]
Are class properties a JavaScript language feature? Have you asked the tern people about supporting it?

**Comment by maximus8891** [comment]
@puremourning Class properties are part of the [unified class features proposal](https://github.com/tc39/proposal-unified-class-features#field-declarations).

No, I haven't asked for the feature at the Tern repo.

**Comment by maximus8891** [comment]
The [branch](https://github.com/micbou/YouCompleteMe/tree/tsserver-javascript) has stopped working with the new version of TS.

I wonder if the code could be updated. I have been using TS for JS files successfully.

**Comment by micbou** [comment]
Strange, it's working for me. Which version of TypeScript are you using? I tried with 2.7.1. Anyway, I've updated the branch with the latest version of ycmd. Could you give it a try?

**Comment by maximus8891** [comment]
Thanks @micbou. Will update it on my side.

I had it at 2.6.1.

**Comment by maximus8891** [comment]
Works okay now with TS 2.7.1! 👍

**Comment by bstaletic** [comment]
@micbou Didn't you say Tern is not maintained as of recently?

This isn't the first time a user asked us to allow typescript server for javascript. We probably should switch either to TSServer only or to the LSP server.

As a bonus to the LSP option, if we switch C and typescript to LSP, we could get rid of handling diagnostics on `OnFileReadyToParse` as there would be nothing left using it.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by meritozh** [comment]
Can YCM provide a option to let user choose to use Tern or TSServer for Javascript ?

**Comment by maximus8891** [comment]
Is there any progress with the transition to TS? :smile:

**Comment by bstaletic** [comment]
Here's the status... There are a lot of users who need Tern for javascript, so the only way to satisfy both sides is to provide some way of using either Tern or TSServer for javascript. However, no one stepped in and implemented the solution.

@meritozh mentioned a configuration option, which is a simple solution that would require the user to read the docs and figure out which one the user wants.
@micbou proposed that ycmd should check if Tern is installed and if it is (for backwards compatibility) user that. If it isn't try to use TSServer. Failing that... well, the user doesn't have a valid setup.

**Comment by maximus8891** [comment]
Thanks for the update! Either of the options sounds good to me.

**Comment by meritozh** [comment]
A configuration option is a most easy way. Because maybe I installed tern in my `PATH` but for other editor's extension, when I use vim to coding, I want still use TSServer instead of tern.

**Comment by micbou** [comment]
See PR #1036.
