### ISSUE TITLE
Expose CXCodeCompleteResults object and wrappers for clang_codeCompleteGet* to Python 

### ISSUE THREAD

**Issue by froody** [Valloric/ycmd#866]
Currently CXCodeCompleteResults is hidden from Python, but I'd like to be able to access it to provide more accurate completions, for example:

- Inspecting clang_codeCompleteGetContexts in ShouldUseNowInner, I can test for CXCompletionContext_ObjCInstanceMessage and then return True, showing a completion for the current objc selector
- Calling clang_codeCompleteGetObjCSelector allows me to strip the already-typed selector from the completion path

Example:
![out](https://user-images.githubusercontent.com/241317/32151447-1fe2cc2e-bcda-11e7-9247-24b561e1047b.gif)

See this patch for a rough prototype:
https://github.com/froody/ycmd/commit/e9c779e9727a9da69b0ea5d5bce95c62db8783fa

**Comment by micbou** [comment]
There are a number of issues with your changes:
 - you are parsing the translation unit in the `ShouldUseNowInner` function. In practice, this means that the translation unit will be parsed at each key press. That's not going to work well with big projects. There is also the argument that if we are going to parse the translation unit at each key press, we might as well always use semantic completion (i.e. always returning `True` in `ShouldUseNowInner`);
 - most of the changes could be done in the C++ layer. There is no need to expose all these functions;
 - the `_cxresult` and `_cxcontext` variables are subject to race condition.

As such, I don't see these changes being included.
