### ISSUE TITLE
c++ include autocomplete working only if triggered via Ctrl+space and autocomplete not working, debug log has no errors.

### ISSUE THREAD

**Issue by ngmgit** [Valloric/ycmd#867]
I followed the readme and faq to setup ymcd with vscode.
I compiled it with --clang-completer and everyhing went well and vscode can successfully establish connection with ymcd in the provided path.

statements like `include <vec` doest work and no results are shown and the debug log says 200 success.
The local headers auto completion works fine.

I even followed the faq to setup the include path for the flags but it doesnt work.

Iam attaching the log along with my config. [ycm_extra_conf.py](https://gist.github.com/ngmgit/b392e85491d24b28866e5dc49d51dcf7)
This is the part of the log when i type `#incldue <vec` and press crtrl+ space. [Debug log](https://gist.github.com/ngmgit/dce51eb13bb593fcb77ecdef4b4a4a61)

Update:
gist updated with typo fix for config link.

**Comment by micbou** [comment]
There is an error in your `.ycm_extra_conf.py` file. You are appending [the system includes to `flags` instead of `final_flags`](https://gist.github.com/ngmgit/b392e85491d24b28866e5dc49d51dcf7#file-ycmd-conf-L153-L155).

**Comment by ngmgit** [comment]
@micbou iam really sorry for that. Yes now it works but for std c++ includes i have to press Ctrl+space.

**Comment by ngmgit** [comment]
![screenshot_20171101_230707](https://user-images.githubusercontent.com/10939602/32288289-74569f8e-bf59-11e7-81d6-d0d91d61e290.png)

**Comment by micbou** [comment]
> In addition to GLSL files i get other suggestions which are not in the directory.

These suggestions are in the `/usr/include` folder (at least `GLES2` and `GLES3`) which is included in your flags. Nothing wrong here.

> here iam trying to test the autocomplete after including SDL2 header and i get no suggestions.

Works fine for me with the Vim client (using `<C-Space>` to force semantic completion after typing `SDL_`):

![sdl-completion](https://user-images.githubusercontent.com/10026824/34059163-1fe3d7c6-e1de-11e7-8278-231d97989111.gif)
I would suggest to raise an issue on [the VS Code client repository](https://marketplace.visualstudio.com/items?itemName=RichardHe.you-complete-me).

Closing as this doesn't seem to be an issue with ycmd.
