### ISSUE TITLE
OnInsertCompletion event?

### ISSUE THREAD

**Issue by dseuss** [Valloric/ycmd#871]
I am currently writing a completer for ycmd, which needs to perform an additional action once the user has inserted a completion from the list of candidates. What would be the best approach to this:

1. add a `OnInsertCompletion` function to the `Completer` base class, which then get's called.
2. add a user command, which get's called through some editor-specifc code, e.g. write a vimscript that calls the user command when a completion has been selected.

I understand that this is quite an uncommon case for the general use of YCM and 1) might be overkill for this kind of problem.

**Comment by puremourning** [comment]
It really depends on what sort of action do you need to perform?

ycmd protocol supports an `extra_data` parameter on the `completion` response. This can be used to perform additional _stuff_ in the client.

YCM (the Vim client) supports this currently for automatically adding import statements for c-sharp, and in the (upcoming) [Language Server - Java](https://github.com/Valloric/ycmd/pull/857) PR we're using it to apply "additional text edits" when you select an item in the client.

Client code is completer-specific unfortuantely, but here it is in all of its glory: 
 - https://github.com/puremourning/YouCompleteMe/blob/language-server-java/python/ycm/youcompleteme.py#L132-L135
 - https://github.com/puremourning/YouCompleteMe/blob/language-server-java/python/ycm/youcompleteme.py#L571-L582

**Comment by dseuss** [comment]
Thanks, I'll have a look. It is probably already what I am looking for.

Here is some background info: It's supposed to be a completer for LaTeX/Bib (bib is a format for handling citations in LaTeX). The candidates are pulled from a database (such as Zotero). When we have selected a candidate, we need to put it's details into a separate file (the bib file).

**Comment by bstaletic** [comment]
Considering no further input has been received from @dseuss, I take it this has been resolved.
Closed.
