### ISSUE TITLE
-idirafter is missing from the supported INCLUDE_FLAGS for the cpp completer

### ISSUE THREAD

**Issue by ekratzer** [Valloric/ycmd#874]
"-idirafter" is a valid clang include flag but is not supported by ycmd's cpp completer.  This causes problems when compilation databases use things like "-nostdinc" and try to specify alternate includes using "-idirafter".

The fix is to add "-idirafter" to the INCLUDE_FLAGS list in ycmd/completers/cpp/flags.py:

INCLUDE_FLAGS = [ '-idirafter', '-isystem', '-I', '-iquote', '-isysroot', '--sysroot',
                  '-gcc-toolchain', '-include', '-include-pch', '-iframework',
                  '-F', '-imacros' ]

**Comment by bstaletic** [comment]
Thanks for reporting this. Would you open a PR with this fixed? Some tests would be required as well.

**Comment by micbou** [comment]
Implemented by PR https://github.com/Valloric/ycmd/pull/877.
