### ISSUE TITLE
Youcompleteme server shutdown

### ISSUE THREAD

**Issue by dendisuhubdy** [Valloric/ycmd#881]
I keep getting Youcompleteme server shutdown with exit code -6. So I did `YcmRestartServer` but the error keeps coming. I tried to run `./run_tests.py` and [here is the result (too long to paste here on the issue page)](https://gist.github.com/dendisuhubdy/74b3789e8b557e07c589ac933b81c2b6)

**Comment by puremourning** [comment]
Please can you include the `ycmd` stdout and stderr when the server fails to start? What client are you using?

Btw for the tests you need to run ‘pip install -r test_requirements.txt’. See DEV_SETUP file.

**Comment by micbou** [comment]
No answer. Closing.
