### ISSUE TITLE
default hidden symbol cause hidden PyInit_ycm_core

### ISSUE THREAD

**Issue by kitech** [Valloric/ycmd#893]
>   1477: 0000000000088b06   144 FUNC    LOCAL  DEFAULT   12 PyInit_ycm_core

**Comment by bstaletic** [comment]
Yes, but only on boost 1.65. Since ycmd upgraded to 1.66 this isn't an issue.

Are you using `--system-boost`?

**Comment by kitech** [comment]
yes i'am using system boost 1.65.
thanks
