### ISSUE TITLE
Build with mingw-w64 using msys2

### ISSUE THREAD

**Issue by gokhanettin** [Valloric/ycmd#915]
[This](https://github.com/gokhanettin/ycmd/commit/afc442c7939ba097052cee986fea255b9bdd7ac3) commit builds with mingw-w64 when we build YouCompleteMe with 

```
python installer.py --clang-completer --system-libclang
```

after installing libclang, python2 and ninja using msys2's pacman. Do we have any plan to support mingw-w64? The only problem I can think of is the use of ` --system-libclang`. The libclang we download from  llvm.org -not surprisingly- won't work. I have not tried with other languages.

**Comment by micbou** [comment]
No, there is no plan to officially support MSYS2 (as well as MinGW, Cygwin, and WSL). See [that comment](https://github.com/Valloric/YouCompleteMe/issues/2092#issuecomment-204707013) for the rational.
