### ISSUE TITLE
Shutdown ycmd if the editor is gone?

### ISSUE THREAD

**Issue by sam-mccall** [Valloric/ycmd#927]
If I start vim + YCM, ycmd is a child of vim.

Then if vim exits uncleanly, ycm keeps running as a child of `init`.
Can ycmd detect this and shut down?

I'm still trying to debug why vim+ycm isn't shutting down ycmd in my setup, but this seems like a reasonable robustness/defense-in-depth measure. When I noticed the problem I had 10s of ycmds running, each with a language server hanging off it...

**Comment by bstaletic** [comment]
After some time of inactivity, ycmd is supposed to shut itself down. Is
this not happening? I can't check what is the timeout we specified right
now.

**Comment by micbou** [comment]
[YCM sets the time to shutdown after inactivity to 30 minutes](https://github.com/Valloric/YouCompleteMe/blob/master/python/ycm/youcompleteme.py#L102).

**Comment by micbou** [comment]
By the way, ycmd not shutting down after exiting Vim could be due to a bad interaction with another plugin. See [this entry in the FAQ](https://github.com/Valloric/YouCompleteMe#ycm-does-not-shut-down-when-i-quit-vim).

**Comment by puremourning** [comment]
> When I noticed the problem I had 10s of ycmds running, each with a language server hanging off it...

I take it you’re using the java completer? Could you post the logs please ?

**Comment by sam-mccall** [comment]
Thanks, I did find the FAQ entry and eventually tracked it down to an old script I had installed. That makes VimLeave seem like a pretty fragile mechanism to rely on, so I guess I should expect the timeout to be the way ycmd shuts down for some fraction of users.

I guess the timeout works well enough. I was remembering it being ~a day, but looks like that changed years ago. 30 minutes is still a bit inconvenient:
  - the language server eats multiple GB of ram (it didn't free any because it doesn't know the docs are closed)
  - a workflow that ends up opening and closing vim a lot can end up with a lot of ycmds in 30 minutes (I ended up with 15 running when I checked)

It seems like losing the parent could result in shutdown within seconds instead of minutes, but maybe this isn't worth fixing.

@puremourning  It's not the Java language server, but rather clangd with a fairly simple out-of-tree completer (would be nice to upstream it at some point, but my attempts to slot clangd into the LSP completer framework didn't work well so far). Happy to share our completer and my attempt at using the upstream LSP support if that'd be helpful.

**Comment by bstaletic** [comment]
> Clangd

I managed to get Clangd to work with ycmd using the LSP completer. The
reason there isn't a PR yet is that it's not at feature parity with the
current implementation.

**Comment by sam-mccall** [comment]
Sorry, this is way off topic. I'll open a new issue for clangd support tomorrow unless someone gets there first.

**Comment by puremourning** [comment]
> clangd... upstream...

I wrote a [clangd completer implementation](https://github.com/puremourning/ycmd-1/commit/787cc8812609c524fd4bd64869aebdb035048ed7) as part of the development of the java completer.

this was working at one point, and took about 30 minutes to integrate with [our LSP implementation](https://github.com/Valloric/ycmd/blob/master/ycmd/completers/language_server/language_server_completer.py#L571). I doubt it works now, due to API changes during code review

full details on the [java PR description](https://github.com/Valloric/ycmd/pull/857)

**Comment by bstaletic** [comment]
@puremourning It doesn't work anymore, it was easier for me to write one
from scratch than to fix the existing one.

**Comment by puremourning** [comment]
I realise that, i was responding to:

> but my attempts to slot clangd into the LSP completer framework didn't work well so far

**Comment by puremourning** [comment]
> Thanks, I did find the FAQ entry and eventually tracked it down to an old script I had installed

Given that the server shuts down after 30 mins of inactivity and you're not using an "official" completer, and the problem was with another plugin... I think we can close this.
