### ISSUE TITLE
Versionized release

### ISSUE THREAD

**Issue by xu-cheng** [Valloric/ycmd#93]
Any plan to release ycmd with version? It can be helpful for packaged distribution.

If so, I'm willing to help to create a Homebrew formula for it.

**Comment by Valloric** [comment]
I do want to start versioning ycmd at some point, but I want to see the emacs-ycmd client progress a bit more so that we can confirm that there's nothing overly vim-specific about the current API. 

When I'm confident we're good on that front, we'll see ycmd 1.0.0 and from then on, semver.
