### ISSUE TITLE
not all standard headers appear in completion list

### ISSUE THREAD

**Issue by Braber01** [Valloric/ycmd#930]
I could just be doing something wrong or have something wrong with my .ycm_extra_conf
I've noticed that the C++ headers Iḿ looking for are located in
/usr/include/c++/5/ is there a way to include that in my ycm as well?

but after running the command 'locate iostream.h
I got these results
/usr/include/glib-2.0/gio/gfilestream.h
/usr/include/glib-2.0/gio/giostream
and
/usr/include/glib-2.0/gio/gsimpleiostream

I've attached my .ycm_extra_conf
[ycm_extra_conf_py.txt](https://github.com/Valloric/ycmd/files/1734299/ycm_extra_conf_py.txt)

**Comment by puremourning** [comment]
I'm sorry, but it's really unclear to me what problem you are reporting or what question you are asking :/

> is there a way to include that in my ycm as well?

You can add include paths by adding `-isystem` or something to your flags. There's also an FAQ entry about system includes.

If you're using YCM (the Vim client), could you please raise the issue on the YCM repository and complete the issue template?

**Comment by micbou** [comment]
> but after running the command 'locate iostream.h

There is no header in the standard library named `iostream.h`. It's `iostream` without the extension.

**Comment by Braber01** [comment]
I fixed it anyway feel free to close the issure
