### ISSUE TITLE
[Help] Web client

### ISSUE THREAD

**Issue by bikram-choudhury** [Valloric/ycmd#943]
I am in process of developing node based web-application, that will communicate to YCMD server to get code suggestions. This web-applications will be used by multiple users at same time to get code suggestions.
Wondering if YCMD can serve multiple users with different code contexts.
Please kindly advice if I can use YCMD sever to serve multiple users.

**Comment by bstaletic** [comment]
Ycmd was never developed with that use case in mind. There are known problems with multi-user ycmd. So while it *may* work in majority of the cases, I wouldn't recommend it. More specifically, the completion cache will most likely get in your way.

**Comment by bstaletic** [comment]
This is not likely to ever be supported. Closing.
