### ISSUE TITLE
YCM loaded error "ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=34172): Max retries exceeded with url"

### ISSUE THREAD

**Issue by wanglewili** [Valloric/ycmd#988]
Hi Supporter,
After configured ycm, it always reports one error while vim loading as following.

ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=47983): Max retries exceeded with url: /shutdown (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x9fdf34c>: Failed to establish a new connection: [Errno 111] Connection refused',))

Could you please help to check this issue?

Thanks,
Zach.

**Comment by micbou** [comment]
Please report the issue on [the YCM repository](https://github.com/Valloric/YouCompleteMe) by completing the steps in [the issue template](https://github.com/Valloric/YouCompleteMe/blob/master/.github/ISSUE_TEMPLATE.md).
